import {test} from 'node:test';
import assert from 'node:assert/strict';
import {fresh,dayKey,validMove,nextMove,ensureOrder,propose,undo,normalize,similarity,keepPassed} from '../lib/domain';
import {act,applyParsed} from '../lib/reducer';
import {jsonSchema,schema,summarySchema} from '../lib/llm';
const item=(title:string,type:'course'|'lane'|'application'='course')=>({id:null,title,type,complete:false,completedMoveId:null,moves:[`${title} için ders sayfasını aç ve konuları listele.`],where:null,question:null});
const parsed=(items:ReturnType<typeof item>[])=>({items,question:null,summary:'İşlendi'});
test('Istanbul 04:00 boundary',()=>{assert.equal(dayKey(new Date('2026-10-12T00:59:00Z')),'2026-10-11');assert.equal(dayKey(new Date('2026-10-12T01:00:00Z')),'2026-10-12');});
test('Turkish normalization and concrete moves',()=>{assert.equal(normalize('İSTATİSTİK'),'istatistik');assert.equal(similarity('Tez','tez'),1);assert.ok(validMove('İstatistik ders sayfasını aç ve vizeye kadarki konuları listele.'));assert.ok(!validMove('İstatistik için biraz daha çalış.'));assert.ok(validMove('Makaleyi oku.'));});
test('No duplicate fronts, raw history and partial/full undo',()=>{const s=applyParsed(fresh(),parsed([item('İstatistik'),item('Fizik')]),'Ham dikte');const again=applyParsed(s,parsed([item('İstatistik')]),'Yeni not');assert.equal(Object.keys(again.fronts).length,2);assert.throws(()=>undo(again,s.changes[0].id),/daha yeni/);const back=undo(again,again.changes.at(-1)!.id);const partial=undo(back,s.changes[0].id,0);assert.equal(Object.keys(partial.fronts).length,1);const all=undo(partial,s.changes[0].id);assert.equal(Object.keys(all.fronts).length,0);});
test('Unlimited and zero orders; held lanes excluded',()=>{let s=applyParsed(fresh(),parsed([...Array.from({length:16},(_,i)=>item('Ders '+i)),item('Tez','lane')]),'test');assert.equal(ensureOrder(s).slots.length,16);s=act(s,{id:'a',kind:'setup',ids:[]});s=act(s,{id:'b',kind:'select',ids:[]});s=act(s,{id:'c',kind:'approve'});assert.equal(ensureOrder(s).slots.length,0);assert.ok(ensureOrder(s).approvedAt);});
test('Approved order is unchanged after new dictation and status changes',()=>{let s=applyParsed(fresh(),parsed([item('İstatistik')]),'one');s=act(s,{id:'1',kind:'approve'});const snapshot=structuredClone(ensureOrder(s));s=applyParsed(s,parsed([item('Fizik')]),'two');assert.deepEqual(ensureOrder(s),snapshot);s=act(s,{id:'2',kind:'status',frontId:Object.keys(s.fronts)[0],status:'closed'});assert.deepEqual(ensureOrder(s),snapshot);});
test('Complete marks the slot as passed and undo restores it',()=>{let s=applyParsed(fresh(),parsed([{...item('İstatistik'),moves:['İstatistik ders sayfasını aç ve konuları listele.','İstatistik ilk konusundaki 3 örnek soruyu çöz.']}]),'one');s=act(s,{id:'1',kind:'approve'});const id=Object.keys(s.fronts)[0],old=nextMove(s.fronts[id])!.id;s=act(s,{id:'2',kind:'complete',frontId:id});assert.notEqual(nextMove(s.fronts[id])!.id,old);const slot=ensureOrder(s).slots[0];assert.equal(slot.moveId,old);assert.equal(slot.text,'İstatistik ders sayfasını aç ve konuları listele.');assert.ok(slot.doneAt);s=undo(s,s.changes.at(-1)!.id);assert.equal(nextMove(s.fronts[id])!.id,old);assert.equal(ensureOrder(s).slots[0].doneAt,undefined);});
test('A passed camp stays today and its front moves on tomorrow',()=>{let s=applyParsed(fresh(),parsed([{...item('Fizik'),moves:['Fizik ders sayfasını aç ve konuları listele.','Fizik ilk konunun sorularını çöz.']},item('Kimya')]),'one');const id=Object.values(s.fronts).find(f=>f.title==='Fizik')!.id;s=act(s,{id:'a',kind:'approve'});s=act(s,{id:'b',kind:'complete',frontId:id});assert.equal(ensureOrder(s).slots.length,2);assert.ok(ensureOrder(s).slots.find(x=>x.frontId===id)!.doneAt);const tomorrow=new Date(Date.parse(dayKey()+'T12:00:00Z')+86400000).toISOString().slice(0,10),next=propose(s,tomorrow).slots.find(x=>x.frontId===id)!;assert.equal(next.moveId,nextMove(s.fronts[id])!.id);assert.notEqual(next.reason,'Önceki onaylı emirden devreden hamle.');let last=applyParsed(fresh(),parsed([item('Biyoloji')]),'one');const only=Object.keys(last.fronts)[0];last=act(last,{id:'a',kind:'approve'});last=act(last,{id:'b',kind:'complete',frontId:only});assert.equal(nextMove(last.fronts[only]),undefined);assert.equal(ensureOrder(last).slots.length,1);assert.equal(propose(last,tomorrow).slots.length,0);});
test('First completion stores an unapproved suggestion without approving it',()=>{let s=applyParsed(fresh(),parsed([item('Fizik'),item('Kimya')]),'one');const [a,b]=ensureOrder(s).slots;assert.equal(s.orders[dayKey()],undefined);s=act(s,{id:'c',kind:'complete',frontId:a.frontId});const o=s.orders[dayKey()];assert.ok(o);assert.equal(o.approvedAt,undefined);assert.ok(o.slots.find(x=>x.frontId===a.frontId)!.doneAt);assert.deepEqual(o.slots.find(x=>x.frontId===b.frontId),b);s=undo(s,s.changes.at(-1)!.id);assert.equal(s.orders[dayKey()],undefined);});
test('A dictated completion freezes the slot too',()=>{let s=applyParsed(fresh(),parsed([{...item('Fizik'),moves:['Fizik ders sayfasını aç ve konuları listele.','Fizik ilk konunun sorularını çöz.']}]),'one');const slot=ensureOrder(s).slots[0];s=applyParsed(s,parsed([{...item('Fizik'),complete:true,moves:[]}]),'Fizik sayfasını açtım.');const after=ensureOrder(s).slots[0];assert.equal(after.moveId,slot.moveId);assert.equal(after.text,slot.text);assert.ok(after.doneAt);assert.equal(s.orders[dayKey()].approvedAt,undefined);});
test('Select, reorder and edit keep a passed camp in place',()=>{let s=applyParsed(fresh(),parsed([{...item('Fizik'),moves:['Fizik ders sayfasını aç ve konuları listele.','Fizik ilk konunun sorularını çöz.']},item('Kimya'),item('Biyoloji')]),'one');s=act(s,{id:'a',kind:'approve'});const [a,b,c]=ensureOrder(s).slots.map(x=>x.frontId);s=act(s,{id:'b',kind:'complete',frontId:a});const passed=structuredClone(ensureOrder(s).slots[0]);const cur=ensureOrder(s);assert.throws(()=>act(s,{id:'r1',kind:'reorder',ids:[b,a,c],orderDate:cur.date,orderSnapshot:JSON.stringify(cur)}),/Geçilen/);s=act(s,{id:'r2',kind:'reorder',ids:[a,c,b],orderDate:cur.date,orderSnapshot:JSON.stringify(cur)});assert.deepEqual(ensureOrder(s).slots.map(x=>x.frontId),[a,c,b]);assert.deepEqual(keepPassed(ensureOrder(s),[b,c,a]),[a,b,c]);s=act(s,{id:'e',kind:'edit',frontId:a,text:'Fizik ikinci konunun sorularını çöz.'});assert.deepEqual(ensureOrder(s).slots[0],passed);s=act(s,{id:'s',kind:'select',ids:[b]});assert.deepEqual(ensureOrder(s).slots.map(x=>x.frontId),[a,b]);assert.deepEqual(ensureOrder(s).slots[0],passed);s=act(s,{id:'s2',kind:'select',ids:[]});assert.deepEqual(ensureOrder(s).slots,[passed]);});
test('Generic title suffixes do not create duplicate fronts',()=>{let s=applyParsed(fresh(),parsed([item('Robotik','lane')]),'one');s=applyParsed(s,parsed([item('Robotik Projesi','lane')]),'two');assert.equal(Object.keys(s.fronts).length,1);});
test('Undo cannot orphan a slot that still references a newly created front',()=>{let s=applyParsed(fresh(),parsed([item('Fizik')]),'one');const created=s.changes[0].id;s=act(s,{id:'a',kind:'approve'});assert.throws(()=>undo(s,created),/emir/);});
test('Unfinished prior order gets priority',()=>{const s=applyParsed(fresh(),parsed([item('Fizik'),item('Erasmus','application')]),'test');const f=Object.values(s.fronts).find(f=>f.title==='Fizik')!;s.orders['2020-01-01']={date:'2020-01-01',approvedAt:'2020-01-01',slots:[{frontId:f.id,moveId:nextMove(f)!.id,text:nextMove(f)!.text,reason:''}]};assert.equal(propose(s).slots[0].frontId,f.id);});

test('Reorder preserves approved snapshots including closed fronts and supports undo',()=>{let s=applyParsed(fresh(),parsed([item('Fizik'),item('Erasmus','application')]),'test');s=act(s,{id:'approve',kind:'approve'});const old=structuredClone(ensureOrder(s));s=act(s,{id:'close',kind:'status',frontId:old.slots[0].frontId,status:'closed'});const next=act(s,{id:'sort',kind:'reorder',ids:old.slots.map(x=>x.frontId).reverse(),orderDate:old.date,orderSnapshot:JSON.stringify(old)});assert.deepEqual(ensureOrder(next),{...old,slots:[...old.slots].reverse()});assert.deepEqual(undo(next,next.changes.at(-1)!.id).orders,s.orders);});
test('Reorder rejects incomplete, duplicate, foreign and stale orders',()=>{const s=applyParsed(fresh(),parsed([item('Fizik'),item('Erasmus','application')]),'test'),old=ensureOrder(s),ids=old.slots.map(x=>x.frontId),base={id:'sort',kind:'reorder',orderDate:old.date,orderSnapshot:JSON.stringify(old)};for(const invalid of [ids.slice(1),[ids[0],ids[0]],[ids[0],'foreign']])assert.throws(()=>act(s,{...base,ids:invalid}),/birer kez/);assert.throws(()=>act(s,{...base,ids,orderDate:'2000-01-01'}),/değişti/);const changed=act(s,{id:'a',kind:'approve'});assert.throws(()=>act(changed,{...base,ids}),/değişti/);});
test('Reorder supports more than fifteen fronts and does not approve a suggestion',()=>{const s=applyParsed(fresh(),parsed(Array.from({length:18},(_,i)=>item('Ders '+i))),'test'),old=ensureOrder(s);const next=act(s,{id:'sort',kind:'reorder',ids:old.slots.map(x=>x.frontId).reverse(),orderDate:old.date,orderSnapshot:JSON.stringify(old)});assert.equal(ensureOrder(next).slots.length,18);assert.equal(ensureOrder(next).approvedAt,undefined);assert.deepEqual(ensureOrder(next).slots,[...old.slots].reverse());});
// Anthropic structured output: one request takes at most 16 union-typed fields ("type": [x, "null"]) and 24 optional
// fields. The 4 Oct schema had 27 unions and was refused; newer fields use empty values instead of null (lib/llm.ts).
function limits(node:unknown){let unions=0,optional=0;const walk=(x:unknown)=>{if(!x||typeof x!=='object')return;const n=x as {type?:unknown;anyOf?:unknown[];properties?:Record<string,unknown>;required?:string[];items?:unknown};if(Array.isArray(n.type)&&n.type.length>1||n.anyOf)unions++;if(n.properties){const required=new Set(n.required??[]);optional+=Object.keys(n.properties).filter(k=>!required.has(k)).length;Object.values(n.properties).forEach(walk);}if(n.items)walk(n.items);};walk(node);return {unions,optional};}
test('Model schemas stay within Anthropic’s union and optional field limits',()=>{for(const s of [schema,summarySchema]){const {unions,optional}=limits(jsonSchema(s));assert.ok(unions<=16,`${unions} union-typed fields (limit 16)`);assert.ok(optional<=24,`${optional} optional fields (limit 24)`);}assert.deepEqual(limits(jsonSchema(schema)),{unions:14,optional:0});assert.deepEqual(limits({type:'object',properties:{a:{type:['string','null']},b:{type:'string'}},required:['b']}),{unions:1,optional:1});});
