import {test} from 'node:test';
import assert from 'node:assert/strict';
import {fresh,dayKey,validMove,nextMove,ensureOrder,propose,undo,normalize,similarity} from '../lib/domain';
import {act,applyParsed} from '../lib/reducer';
const item=(title:string,type:'course'|'lane'|'application'='course')=>({id:null,title,type,complete:false,completedMoveId:null,moves:[`${title} için ders sayfasını aç ve konuları listele.`],where:null,question:null});
const parsed=(items:ReturnType<typeof item>[])=>({items,question:null,summary:'İşlendi'});
test('Istanbul 04:00 boundary',()=>{assert.equal(dayKey(new Date('2026-10-12T00:59:00Z')),'2026-10-11');assert.equal(dayKey(new Date('2026-10-12T01:00:00Z')),'2026-10-12');});
test('Turkish normalization and concrete moves',()=>{assert.equal(normalize('İSTATİSTİK'),'istatistik');assert.equal(similarity('Tez','tez'),1);assert.ok(validMove('İstatistik ders sayfasını aç ve vizeye kadarki konuları listele.'));assert.ok(!validMove('İstatistik için biraz daha çalış.'));assert.ok(validMove('Makaleyi oku.'));});
test('No duplicate fronts, raw history and partial/full undo',()=>{const s=applyParsed(fresh(),parsed([item('İstatistik'),item('Fizik')]),'Ham dikte');const again=applyParsed(s,parsed([item('İstatistik')]),'Yeni not');assert.equal(Object.keys(again.fronts).length,2);assert.throws(()=>undo(again,s.changes[0].id),/daha yeni/);const back=undo(again,again.changes.at(-1)!.id);const partial=undo(back,s.changes[0].id,0);assert.equal(Object.keys(partial.fronts).length,1);const all=undo(partial,s.changes[0].id);assert.equal(Object.keys(all.fronts).length,0);});
test('Unlimited and zero orders; held lanes excluded',()=>{let s=applyParsed(fresh(),parsed([...Array.from({length:16},(_,i)=>item('Ders '+i)),item('Tez','lane')]),'test');assert.equal(ensureOrder(s).slots.length,16);s=act(s,{id:'a',kind:'setup',ids:[]});s=act(s,{id:'b',kind:'select',ids:[]});s=act(s,{id:'c',kind:'approve'});assert.equal(ensureOrder(s).slots.length,0);assert.ok(ensureOrder(s).approvedAt);});
test('Approved order is unchanged after new dictation and status changes',()=>{let s=applyParsed(fresh(),parsed([item('İstatistik')]),'one');s=act(s,{id:'1',kind:'approve'});const snapshot=structuredClone(ensureOrder(s));s=applyParsed(s,parsed([item('Fizik')]),'two');assert.deepEqual(ensureOrder(s),snapshot);s=act(s,{id:'2',kind:'status',frontId:Object.keys(s.fronts)[0],status:'closed'});assert.deepEqual(ensureOrder(s),snapshot);});
test('Complete moves one slot forward and undo restores it',()=>{let s=applyParsed(fresh(),parsed([{...item('İstatistik'),moves:['İstatistik ders sayfasını aç ve konuları listele.','İstatistik ilk konusundaki 3 örnek soruyu çöz.']}]),'one');s=act(s,{id:'1',kind:'approve'});const id=Object.keys(s.fronts)[0],old=nextMove(s.fronts[id])!.id;s=act(s,{id:'2',kind:'complete',frontId:id});assert.notEqual(nextMove(s.fronts[id])!.id,old);assert.equal(ensureOrder(s).slots[0].moveId,nextMove(s.fronts[id])!.id);s=undo(s,s.changes.at(-1)!.id);assert.equal(nextMove(s.fronts[id])!.id,old);});
test('Completing the last known move does not loop back to a finished task',()=>{let s=applyParsed(fresh(),parsed([item('Fizik')]),'one');const id=Object.keys(s.fronts)[0];s=act(s,{id:'a',kind:'approve'});s=act(s,{id:'b',kind:'complete',frontId:id});assert.equal(nextMove(s.fronts[id]),undefined);assert.equal(ensureOrder(s).slots.length,0);});
test('Generic title suffixes do not create duplicate fronts',()=>{let s=applyParsed(fresh(),parsed([item('Robotik','lane')]),'one');s=applyParsed(s,parsed([item('Robotik Projesi','lane')]),'two');assert.equal(Object.keys(s.fronts).length,1);});
test('Undo cannot orphan a slot that still references a newly created front',()=>{let s=applyParsed(fresh(),parsed([item('Fizik')]),'one');const created=s.changes[0].id;s=act(s,{id:'a',kind:'approve'});assert.throws(()=>undo(s,created),/emir/);});
test('Unfinished prior order gets priority',()=>{const s=applyParsed(fresh(),parsed([item('Fizik'),item('Erasmus','application')]),'test');const f=Object.values(s.fronts).find(f=>f.title==='Fizik')!;s.orders['2020-01-01']={date:'2020-01-01',approvedAt:'2020-01-01',slots:[{frontId:f.id,moveId:nextMove(f)!.id,text:nextMove(f)!.text,reason:''}]};assert.equal(propose(s).slots[0].frontId,f.id);});

test('Reorder preserves approved snapshots including closed fronts and supports undo',()=>{let s=applyParsed(fresh(),parsed([item('Fizik'),item('Erasmus','application')]),'test');s=act(s,{id:'approve',kind:'approve'});const old=structuredClone(ensureOrder(s));s=act(s,{id:'close',kind:'status',frontId:old.slots[0].frontId,status:'closed'});const next=act(s,{id:'sort',kind:'reorder',ids:old.slots.map(x=>x.frontId).reverse(),orderDate:old.date,orderSnapshot:JSON.stringify(old)});assert.deepEqual(ensureOrder(next),{...old,slots:[...old.slots].reverse()});assert.deepEqual(undo(next,next.changes.at(-1)!.id).orders,s.orders);});
test('Reorder rejects incomplete, duplicate, foreign and stale orders',()=>{const s=applyParsed(fresh(),parsed([item('Fizik'),item('Erasmus','application')]),'test'),old=ensureOrder(s),ids=old.slots.map(x=>x.frontId),base={id:'sort',kind:'reorder',orderDate:old.date,orderSnapshot:JSON.stringify(old)};for(const invalid of [ids.slice(1),[ids[0],ids[0]],[ids[0],'foreign']])assert.throws(()=>act(s,{...base,ids:invalid}),/birer kez/);assert.throws(()=>act(s,{...base,ids,orderDate:'2000-01-01'}),/değişti/);const changed=act(s,{id:'a',kind:'approve'});assert.throws(()=>act(changed,{...base,ids}),/değişti/);});
test('Reorder supports more than fifteen fronts and does not approve a suggestion',()=>{const s=applyParsed(fresh(),parsed(Array.from({length:18},(_,i)=>item('Ders '+i))),'test'),old=ensureOrder(s);const next=act(s,{id:'sort',kind:'reorder',ids:old.slots.map(x=>x.frontId).reverse(),orderDate:old.date,orderSnapshot:JSON.stringify(old)});assert.equal(ensureOrder(next).slots.length,18);assert.equal(ensureOrder(next).approvedAt,undefined);assert.deepEqual(ensureOrder(next).slots,[...old.slots].reverse());});

