'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowDownUp,ArrowUpRight,Check,ChevronRight,GripVertical} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {type State,type Front,type Order,directGoal,nextMove} from '@/lib/domain';

type Props={state:State;order:Order;busy:boolean;online:boolean;open:(id:string)=>void;complete:(front:Front)=>void;edit:(front:Front,text:string)=>void;select:()=>void;action:(body:{kind:string;[key:string]:unknown})=>Promise<boolean|undefined>};
export default function AtlasOrder({state,order,busy,online,open,complete,edit,select,action}:Props){
 const [focus,setFocus]=useState<string|null>(null),[expanded,setExpanded]=useState(false),[reordering,setReordering]=useState(false),[ids,setIds]=useState<string[]>([]),[snapshot,setSnapshot]=useState('');const cancelDrag=useRef<(()=>boolean)|null>(null);
 const slots=order.slots,slot=slots.find(s=>s.frontId===focus)??slots[0],front=slot?state.fronts[slot.frontId]:undefined,current=front?.moves.find(m=>m.id===slot?.moveId),rank=slot?slots.indexOf(slot):0;
 const visible=expanded?slots:slots.slice(0,4),ordered=[...visible].sort((a,b)=>(state.fronts[a.frontId]?.title??'').localeCompare(state.fronts[b.frontId]?.title??'','tr'));
 const height=visible.length<=3?230:Math.ceil(visible.length/2)*115+50;
 const points=new Map(ordered.map((s,i)=>[s.frontId,visible.length===3?[[24,92],[74,57],[58,172]][i]:[i%2?72:25,55+Math.floor(i/2)*115+(i%2?35:0)]]));
 const path=visible.map((s,i)=>{const p=points.get(s.frontId)!;return `${i?'L':'M'} ${p[0]} ${p[1]}`;}).join(' ');
 function begin(){setIds(slots.map(s=>s.frontId));setSnapshot(JSON.stringify(order));setReordering(true);}
 const stale=snapshot!==JSON.stringify(order);
 return <section className="atlas-order">
  <div className="atlas-terrain"><div className="terrain-heading"><h2>Bugünün arazisi.</h2><span>{order.approvedAt?'ROTA ONAYLANDI':'ÖNERİLEN ROTA'}</span></div>
   {slots.length>0?<><div className="terrain-map" style={{height}}><div className="terrain-contours" aria-hidden="true"/><svg className="terrain-path" viewBox={`0 0 100 ${height}`} preserveAspectRatio="none" aria-hidden="true"><path d={path}/></svg>{visible.map(s=>{const p=points.get(s.frontId)!;return <button key={s.frontId} className={`terrain-node ${s.frontId===slot?.frontId?'is-focused':''}`} style={{left:p[0]+'%',top:p[1]}} aria-pressed={s.frontId===slot?.frontId} onClick={()=>setFocus(s.frontId)}><span className="terrain-pin">{String(slots.indexOf(s)+1).padStart(2,'0')}</span><span className="terrain-name">{state.fronts[s.frontId]?.title??'Cephe'}</span>{slots.indexOf(s)===0&&<small>İLK HAMLE</small>}</button>;})}</div><div className="terrain-caption"><span>{slots.length} CEPHE / {slots.length} HAMLE</span>{slots.length>4&&<button onClick={()=>setExpanded(!expanded)}>{expanded?'Haritayı daralt':`Tüm rotayı göster (${slots.length})`}</button>}</div></>:<p className="terrain-empty">Bugün açık emir yok.<br/>Yeni rotanı birlikte hazırlayalım.</p>}
  </div>
  <div className="atlas-order-sheet"><div className="sheet-grip" aria-hidden="true"/><div className="atlas-order-top"><span>{slot?`${String(rank+1).padStart(2,'0')} / ${rank===0?'İLK HAMLE':'ROTADAKİ HAMLE'}`:'GÜNÜN EMRİ'}</span>{slots.length>1&&<button className="text-button" onClick={begin} disabled={busy}><ArrowDownUp size={16}/>Sırayı düzenle</button>}</div>
  {slot&&front?<><button className="atlas-front-label" onClick={()=>open(front.id)}>{front.title}<ChevronRight size={14}/></button>{front.type==='lane'&&front.where&&<p className="atlas-where">Kaldığın yer: {front.where}</p>}<h3 className="atlas-move" key={slot.moveId}>{slot.text}</h3><p className="atlas-reason">↳ {current?.prerequisiteReason??slot.reason}</p><div className="atlas-move-actions"><button className={order.approvedAt?'primary':'secondary-action'} disabled={busy||!online||current?.doneAt!==undefined||nextMove(front)?.id!==slot.moveId} onClick={()=>complete(front)}><Check size={17}/>Hamleyi bitir</button><button className="text-button" onClick={()=>edit(front,slot.text)} disabled={busy}>Düzenle</button></div>{directGoal(front)&&<button className="text-button prerequisite" disabled={busy||!online} onClick={()=>action({kind:'skipPrerequisite',frontId:front.id})}>Ön adıma gerek yok</button>}{nextMove(front)?.id!==slot.moveId&&<p className="quiet">Cephe güncellendi. Yeni hamleyi görmek için cephe seçimini güncelle.</p>}</>:<div className="empty-order"><h3 className="serif">Günün emri sende.</h3><p>Haritandan cephe seçebilir ya da bugünü boş bırakabilirsin.</p></div>}
  {!order.approvedAt&&<button className="primary approve-route" disabled={busy||!online||!state.setup} onClick={()=>action({kind:'approve'})}><span>Bu rotayla ilerle</span><ArrowUpRight size={20}/></button>}
  <div className="atlas-order-bottom"><span className="quiet">{order.approvedAt?'Günün emri onaylandı.':'Günün emri onayını bekliyor.'}</span><button className="text-button" disabled={busy} onClick={select}>Cephe ekle / çıkar</button></div>
  {slots.length>1&&<div className="route-itinerary">{slots.map((s,i)=><button key={s.frontId} className={slot?.frontId===s.frontId?'is-current':''} onClick={()=>setFocus(s.frontId)}><span>{String(i+1).padStart(2,'0')}</span><span><small>{state.fronts[s.frontId]?.title}</small>{s.text}</span><ChevronRight size={16}/></button>)}</div>}
  </div>
  <Dialog open={reordering} onOpenChange={value=>!busy&&setReordering(value)}><DialogContent className="berthier-dialog reorder-dialog" onEscapeKeyDown={e=>{if(cancelDrag.current?.())e.preventDefault();}}><DialogTitle>Rotayı düzenle</DialogTitle><DialogDescription>Sağdaki tutamacı basılı tut, hamleyi istediğin yere sürükle. Bıraktığında yeni sırayı görebilirsin.</DialogDescription>
   {stale?<div className="notice">Emir bu sırada güncellendi. Yeni haliyle devam et.<button onClick={begin}>Güncel sırayı aç</button></div>:<SortableRoute ids={ids} setIds={setIds} order={order} fronts={state.fronts} disabled={busy} cancelDrag={cancelDrag}/>}
   <div className="row-actions"><button className="primary" disabled={busy||!online||stale} onClick={async()=>{if(await action({kind:'reorder',ids,orderDate:order.date,orderSnapshot:snapshot})){setReordering(false);setFocus(ids[0]??null);}}}>Sırayı kaydet</button><button disabled={busy} onClick={()=>setReordering(false)}>Vazgeç</button></div><p className="quiet">Kaydetmeden günün emri değişmez. Sonradan kayıt defterinden geri alabilirsin.</p>
  </DialogContent></Dialog>
 </section>;
}

function SortableRoute({ids,setIds,order,fronts,disabled,cancelDrag}:{ids:string[];setIds:(ids:string[])=>void;order:Order;fronts:State['fronts'];disabled:boolean;cancelDrag:React.RefObject<(()=>boolean)|null>}){
 const list=useRef<HTMLOListElement>(null),latest=useRef(ids),gesture=useRef<{id:string;pointer:number;x:number;y:number;lastY:number;before:string[];active:boolean;timer:ReturnType<typeof setTimeout>|null;raf:number|null}|null>(null);
 const [lifted,setLifted]=useState<string|null>(null),[announcement,setAnnouncement]=useState('');const keyboard=useRef<{id:string;before:string[]}|null>(null);latest.current=ids;
 function move(id:string,to:number){const from=latest.current.indexOf(id);if(from===to||from<0||to<0||to>=latest.current.length)return;const next=[...latest.current];next.splice(from,1);next.splice(to,0,id);latest.current=next;setIds(next);setAnnouncement(`${fronts[id]?.title}, ${to+1}. sırada.`);}
 function target(y:number){const g=gesture.current;if(!g?.active||!list.current)return;const rows=[...list.current.querySelectorAll<HTMLElement>('[data-front]')].filter(row=>row.dataset.front!==g.id);let index=rows.length;for(let i=0;i<rows.length;i++){const b=rows[i].getBoundingClientRect();if(y<b.top+b.height/2){index=i;break;}}move(g.id,index);}
 function finish(cancel=false){const g=gesture.current;if(!g)return;if(g.timer)clearTimeout(g.timer);if(g.raf)cancelAnimationFrame(g.raf);gesture.current=null;if(cancel&&g.active){latest.current=g.before;setIds(g.before);}if(list.current?.hasPointerCapture(g.pointer))list.current.releasePointerCapture(g.pointer);setLifted(null);if(g.active)setAnnouncement(cancel?'Taşıma iptal edildi.':'Hamle yeni yerine bırakıldı. Kaydettiğinde uygulanacak.');}
 useEffect(()=>{const cancel=()=>{if(keyboard.current){setIds(keyboard.current.before);keyboard.current=null;setLifted(null);setAnnouncement('Taşıma iptal edildi.');return true;}if(gesture.current){finish(true);return true;}return false;};cancelDrag.current=cancel;window.addEventListener('blur',cancel);return()=>{cancelDrag.current=null;window.removeEventListener('blur',cancel);const g=gesture.current;if(g?.timer)clearTimeout(g.timer);if(g?.raf)cancelAnimationFrame(g.raf);};},[]);
 function start(event:React.PointerEvent<HTMLButtonElement>,id:string){if(disabled||event.button!==0||!event.isPrimary||gesture.current)return;keyboard.current=null;const g={id,pointer:event.pointerId,x:event.clientX,y:event.clientY,lastY:event.clientY,before:[...latest.current],active:false,timer:null as ReturnType<typeof setTimeout>|null,raf:null as number|null};gesture.current=g;list.current?.setPointerCapture(event.pointerId);g.timer=setTimeout(()=>{if(gesture.current!==g)return;g.active=true;setLifted(id);setAnnouncement(`${fronts[id]?.title} tutuldu. Yeni yerine sürükle.`);function scroll(){if(gesture.current!==g||!list.current)return;const bounds=list.current.getBoundingClientRect(),delta=g.lastY<bounds.top+42?-8:g.lastY>bounds.bottom-42?8:0;if(delta){list.current.scrollTop+=delta;target(g.lastY);}g.raf=requestAnimationFrame(scroll);}g.raf=requestAnimationFrame(scroll);},event.pointerType==='mouse'?0:350);}
 function key(event:React.KeyboardEvent<HTMLButtonElement>,id:string){if(disabled)return;if(event.key===' '||event.key==='Enter'){event.preventDefault();if(keyboard.current){keyboard.current=null;setLifted(null);setAnnouncement('Hamle bırakıldı.');}else{keyboard.current={id,before:[...latest.current]};setLifted(id);setAnnouncement('Hamle tutuldu. Yukarı ve aşağı tuşlarıyla taşı; Enter ile bırak.');}}else if(keyboard.current?.id===id){if(event.key==='Escape'){event.preventDefault();setIds(keyboard.current.before);keyboard.current=null;setLifted(null);}else if(event.key==='ArrowUp'||event.key==='ArrowDown'){event.preventDefault();move(id,latest.current.indexOf(id)+(event.key==='ArrowUp'?-1:1));}}}
 return <><p className="sr-only" id="route-keyboard-help">Klavye ile: boşlukla tut, yukarı/aşağı tuşlarıyla taşı, Enter ile bırak, Escape ile iptal et.</p><ol ref={list} className="sortable-route" onPointerMove={e=>{const g=gesture.current;if(!g||g.pointer!==e.pointerId)return;g.lastY=e.clientY;if(!g.active){if(Math.hypot(e.clientX-g.x,e.clientY-g.y)>10)finish(true);return;}e.preventDefault();target(e.clientY);}} onPointerUp={e=>{if(gesture.current?.pointer===e.pointerId)finish();}} onPointerCancel={e=>{if(gesture.current?.pointer===e.pointerId)finish(true);}} onLostPointerCapture={e=>{if(gesture.current?.pointer===e.pointerId)finish(true);}}>{ids.map((id,i)=><li key={id} data-front={id} className={lifted===id?'is-lifted':''}><span className="sort-number">{String(i+1).padStart(2,'0')}</span><span className="sort-content"><strong>{fronts[id]?.title??'Cephe'}</strong><span>{order.slots.find(s=>s.frontId===id)?.text}</span></span><button className="drag-handle" disabled={disabled} aria-label={`${fronts[id]?.title} hamlesini taşı`} aria-describedby="route-keyboard-help" aria-pressed={lifted===id} onPointerDown={e=>start(e,id)} onKeyDown={e=>key(e,id)} onContextMenu={e=>e.preventDefault()}><GripVertical size={22}/></button></li>)}</ol><div className="sr-only" role="status" aria-live="polite">{announcement}</div></>;
}
