'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowDownUp,ArrowUpRight,Check,ChevronRight,GripVertical} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {type State,type Front,type Order,directGoal,nextMove,keepPassed} from '@/lib/domain';
import {clockText} from '@/lib/expedition/camps';
import {atTime} from '@/lib/turkish';
import ExpeditionMap from './expedition-map';

type Action=(body:{kind:string;[key:string]:unknown},options?:{quiet?:boolean})=>Promise<boolean|undefined>;
type Props={state:State;order:Order;busy:boolean;online:boolean;open:(id:string)=>void;complete:(front:Front)=>void;edit:(front:Front,text:string)=>void;select:()=>void;action:Action};
const pad=(n:number)=>String(n).padStart(2,'0');
// The change that marked this camp as passed today; “Geri al” undoes exactly that change.
export function passedBy(state:State,order:Order,frontId:string){return [...state.changes].reverse().find(c=>c.ops.some(o=>!o.undone&&o.key==='order:'+order.date&&!!(o.after as Order|null)?.slots.some(x=>x.frontId===frontId&&x.doneAt)&&!(o.before as Order|null)?.slots.some(x=>x.frontId===frontId&&x.doneAt)));}
export default function AtlasOrder({state,order,busy,online,open,complete,edit,select,action}:Props){
 const [picked,setPicked]=useState<{id:string;done:boolean}|null>(null);
 // A camp chosen while open gives way to the next open camp once it is passed; a passed camp chosen on purpose stays.
 const slots=order.slots,firstOpen=slots.find(s=>!s.doneAt),chosen=picked?slots.find(s=>s.frontId===picked.id):undefined,slot=chosen&&(picked!.done||!chosen.doneAt)?chosen:firstOpen??chosen??slots[0];
 const front=slot?state.fronts[slot.frontId]:undefined,current=front?.moves.find(m=>m.id===slot?.moveId),rank=slot?slots.indexOf(slot):0,passed=slot?.doneAt?clockText(slot.doneAt):'',passedChange=slot&&passed?passedBy(state,order,slot.frontId):undefined;
 const nDone=slots.filter(s=>s.doneAt).length,allDone=slots.length>0&&nDone===slots.length;
 function pick(id:string){setPicked({id,done:!!slots.find(s=>s.frontId===id)?.doneAt});}
 const reorder=useReorder({state,order,busy,online,action,saved:ids=>{const first=ids.find(id=>!order.slots.find(s=>s.frontId===id)?.doneAt);if(first)pick(first);}});
 return <section className="atlas-order">
  <div className="atlas-terrain"><div className="terrain-heading"><h2>Bugünün arazisi.</h2><span>{order.approvedAt?'ROTA ONAYLANDI':'ÖNERİLEN ROTA'}</span></div>
   {slots.length>0?<><ExpeditionMap variant="home" state={state} order={order} focus={slot?.frontId} onFocus={pick} editable={!busy&&online} reorder={next=>action({kind:'reorder',ids:next,orderDate:order.date,orderSnapshot:JSON.stringify(order)},{quiet:true})}/><div className="terrain-caption"><span>{allDone?`SEFER TAMAMLANDI · ${nDone}/${slots.length}`:`${slots.length} CEPHE / ${slots.length} HAMLE${nDone?` · ${nDone} GEÇİLDİ`:''}`}</span><span>MERCAN = ACİL</span></div></>:<p className="terrain-empty">Bugün açık emir yok.<br/>Yeni rotanı birlikte hazırlayalım.</p>}
  </div>
  <div className="atlas-order-sheet"><div className="sheet-grip" aria-hidden="true"/><div className="atlas-order-top"><span>{slot?`${pad(rank+1)} / ${passed?'GEÇİLDİ · '+passed:slot===firstOpen?'SIRADAKİ HAMLE':'ROTADAKİ HAMLE'}`:'GÜNÜN EMRİ'}</span>{slots.length>1&&<button className="text-button" onClick={reorder.begin} disabled={busy}><ArrowDownUp size={16}/>Sırayı düzenle</button>}</div>
  {slot&&front?<><button className="atlas-front-label" onClick={()=>open(front.id)}>{front.title}<ChevronRight size={14}/></button>{front.type==='lane'&&front.where&&<p className="atlas-where">Kaldığın yer: {front.where}</p>}<h3 className={passed?'atlas-move is-passed':'atlas-move'} key={slot.moveId}>{slot.text}</h3><p className="atlas-reason">↳ {passed?`Bugün ${atTime(passed)} tamamlandı.`:current?.prerequisiteReason??slot.reason}</p><div className="atlas-move-actions"><button className={order.approvedAt?'primary':'secondary-action'} disabled={busy||!online||!!passed||current?.doneAt!==undefined||nextMove(front)?.id!==slot.moveId} onClick={()=>complete(front)}><Check size={17}/>Hamleyi bitir</button>{passed?<button className="text-button" onClick={()=>passedChange&&action({kind:'undo',changeId:passedChange.id},{quiet:true})} disabled={busy||!online||!passedChange}>Geri al</button>:<button className="text-button" onClick={()=>edit(front,slot.text)} disabled={busy}>Düzenle</button>}</div>{!passed&&directGoal(front)&&<button className="text-button prerequisite" disabled={busy||!online} onClick={()=>action({kind:'skipPrerequisite',frontId:front.id})}>Ön adıma gerek yok</button>}{!passed&&nextMove(front)?.id!==slot.moveId&&<p className="quiet">Cephe güncellendi. Yeni hamleyi görmek için cephe seçimini güncelle.</p>}</>:<div className="empty-order"><h3 className="serif">Günün emri sende.</h3><p>Haritandan cephe seçebilir ya da bugünü boş bırakabilirsin.</p></div>}
  {!order.approvedAt&&<button className="primary approve-route" disabled={busy||!online||!state.setup} onClick={()=>action({kind:'approve'})}><span>Bu rotayla ilerle</span><ArrowUpRight size={20}/></button>}
  <div className="atlas-order-bottom"><span className="quiet">{order.approvedAt?'Günün emri onaylandı.':'Günün emri onayını bekliyor.'}</span><button className="text-button" disabled={busy} onClick={select}>Cephe ekle / çıkar</button></div>
  {slots.length>1&&<div className="route-itinerary">{slots.map((s,i)=><button key={s.frontId} className={[slot?.frontId===s.frontId?'is-current':'',s.doneAt?'is-passed':''].join(' ').trim()||undefined} onClick={()=>pick(s.frontId)}><span>{s.doneAt?'✓':pad(i+1)}</span><span><small>{state.fronts[s.frontId]?.title}{s.doneAt?` · geçildi ${clockText(s.doneAt)}`:''}</small><span className="itinerary-move">{s.text}</span></span><ChevronRight size={16}/></button>)}</div>}
  </div>
  {reorder.dialog}
 </section>;
}

// The “Rotayı düzenle” dialog. Karargâh and the morning report open the same one.
export function useReorder({state,order,busy,online,action,saved}:{state:State;order:Order;busy:boolean;online:boolean;action:Action;saved?:(ids:string[])=>void}){
 const [reordering,setReordering]=useState(false),[ids,setIds]=useState<string[]>([]),[snapshot,setSnapshot]=useState('');const cancelDrag=useRef<(()=>boolean)|null>(null);
 function begin(){setIds(order.slots.map(s=>s.frontId));setSnapshot(JSON.stringify(order));setReordering(true);}
 const stale=snapshot!==JSON.stringify(order);
 return {begin,dialog:<Dialog open={reordering} onOpenChange={value=>!busy&&setReordering(value)}><DialogContent className="berthier-dialog reorder-dialog" onEscapeKeyDown={e=>{if(cancelDrag.current?.())e.preventDefault();}}><DialogTitle>Rotayı düzenle</DialogTitle><DialogDescription>Sağdaki tutamacı basılı tut, hamleyi istediğin yere sürükle. Bıraktığında yeni sırayı görebilirsin. Haritada bir kampı basılı tut, sonra başka bir kampın üstüne bırak. Masaüstünde doğrudan sürükle.</DialogDescription>
   {stale?<div className="notice">Emir bu sırada güncellendi. Yeni haliyle devam et.<button onClick={begin}>Güncel sırayı aç</button></div>:<SortableRoute ids={ids} setIds={setIds} order={order} fronts={state.fronts} disabled={busy} cancelDrag={cancelDrag}/>}
   <div className="row-actions"><button className="primary" disabled={busy||!online||stale} onClick={async()=>{if(await action({kind:'reorder',ids,orderDate:order.date,orderSnapshot:snapshot})){setReordering(false);saved?.(ids);}}}>Sırayı kaydet</button><button disabled={busy} onClick={()=>setReordering(false)}>Vazgeç</button></div><p className="quiet">Kaydetmeden günün emri değişmez. Sonradan kayıt defterinden geri alabilirsin.</p>
  </DialogContent></Dialog>};
}

function SortableRoute({ids,setIds,order,fronts,disabled,cancelDrag}:{ids:string[];setIds:(ids:string[])=>void;order:Order;fronts:State['fronts'];disabled:boolean;cancelDrag:React.RefObject<(()=>boolean)|null>}){
 const passed=(id:string)=>!!order.slots.find(s=>s.frontId===id)?.doneAt;
 const list=useRef<HTMLOListElement>(null),latest=useRef(ids),gesture=useRef<{id:string;pointer:number;x:number;y:number;lastY:number;before:string[];active:boolean;timer:ReturnType<typeof setTimeout>|null;raf:number|null}|null>(null);
 const [lifted,setLifted]=useState<string|null>(null),[announcement,setAnnouncement]=useState('');const keyboard=useRef<{id:string;before:string[]}|null>(null);latest.current=ids;
 // Passed camps keep their place: only the open ones take the new relative order.
 function move(id:string,to:number){const from=latest.current.indexOf(id);if(from===to||from<0||to<0||to>=latest.current.length)return;const next=[...latest.current];next.splice(from,1);next.splice(to,0,id);place(id,keepPassed(order,next));}
 function place(id:string,next:string[]){if(next.join()===latest.current.join())return;latest.current=next;setIds(next);setAnnouncement(`${fronts[id]?.title}, ${next.indexOf(id)+1}. sırada.`);}
 function step(id:string,dir:number){const open=latest.current.filter(x=>!passed(x)),i=open.indexOf(id),j=i+dir;if(i<0||j<0||j>=open.length)return;[open[i],open[j]]=[open[j],open[i]];place(id,keepPassed(order,open));}
 function target(y:number){const g=gesture.current;if(!g?.active||!list.current)return;const rows=[...list.current.querySelectorAll<HTMLElement>('[data-front]')].filter(row=>row.dataset.front!==g.id);let index=rows.length;for(let i=0;i<rows.length;i++){const b=rows[i].getBoundingClientRect();if(y<b.top+b.height/2){index=i;break;}}move(g.id,index);}
 function finish(cancel=false){const g=gesture.current;if(!g)return;if(g.timer)clearTimeout(g.timer);if(g.raf)cancelAnimationFrame(g.raf);gesture.current=null;if(cancel&&g.active){latest.current=g.before;setIds(g.before);}if(list.current?.hasPointerCapture(g.pointer))list.current.releasePointerCapture(g.pointer);setLifted(null);if(g.active)setAnnouncement(cancel?'Taşıma iptal edildi.':'Hamle yeni yerine bırakıldı. Kaydettiğinde uygulanacak.');}
 useEffect(()=>{const cancel=()=>{if(keyboard.current){setIds(keyboard.current.before);keyboard.current=null;setLifted(null);setAnnouncement('Taşıma iptal edildi.');return true;}if(gesture.current){finish(true);return true;}return false;};cancelDrag.current=cancel;window.addEventListener('blur',cancel);return()=>{cancelDrag.current=null;window.removeEventListener('blur',cancel);const g=gesture.current;if(g?.timer)clearTimeout(g.timer);if(g?.raf)cancelAnimationFrame(g.raf);};},[]);
 function start(event:React.PointerEvent<HTMLButtonElement>,id:string){if(disabled||event.button!==0||!event.isPrimary||gesture.current)return;keyboard.current=null;const g={id,pointer:event.pointerId,x:event.clientX,y:event.clientY,lastY:event.clientY,before:[...latest.current],active:false,timer:null as ReturnType<typeof setTimeout>|null,raf:null as number|null};gesture.current=g;list.current?.setPointerCapture(event.pointerId);g.timer=setTimeout(()=>{if(gesture.current!==g)return;g.active=true;setLifted(id);setAnnouncement(`${fronts[id]?.title} tutuldu. Yeni yerine sürükle.`);function scroll(){if(gesture.current!==g||!list.current)return;const bounds=list.current.getBoundingClientRect(),delta=g.lastY<bounds.top+42?-8:g.lastY>bounds.bottom-42?8:0;if(delta){list.current.scrollTop+=delta;target(g.lastY);}g.raf=requestAnimationFrame(scroll);}g.raf=requestAnimationFrame(scroll);},event.pointerType==='mouse'?0:350);}
 function key(event:React.KeyboardEvent<HTMLButtonElement>,id:string){if(disabled)return;if(event.key===' '||event.key==='Enter'){event.preventDefault();if(keyboard.current){keyboard.current=null;setLifted(null);setAnnouncement('Hamle bırakıldı.');}else{keyboard.current={id,before:[...latest.current]};setLifted(id);setAnnouncement('Hamle tutuldu. Yukarı ve aşağı tuşlarıyla taşı; Enter ile bırak.');}}else if(keyboard.current?.id===id){if(event.key==='Escape'){event.preventDefault();setIds(keyboard.current.before);keyboard.current=null;setLifted(null);}else if(event.key==='ArrowUp'||event.key==='ArrowDown'){event.preventDefault();step(id,event.key==='ArrowUp'?-1:1);}}}
 return <><p className="sr-only" id="route-keyboard-help">Klavye ile: boşlukla tut, yukarı/aşağı tuşlarıyla taşı, Enter ile bırak, Escape ile iptal et.</p><ol ref={list} className="sortable-route" onPointerMove={e=>{const g=gesture.current;if(!g||g.pointer!==e.pointerId)return;g.lastY=e.clientY;if(!g.active){if(Math.hypot(e.clientX-g.x,e.clientY-g.y)>10)finish(true);return;}e.preventDefault();target(e.clientY);}} onPointerUp={e=>{if(gesture.current?.pointer===e.pointerId)finish();}} onPointerCancel={e=>{if(gesture.current?.pointer===e.pointerId)finish(true);}} onLostPointerCapture={e=>{if(gesture.current?.pointer===e.pointerId)finish(true);}}>{ids.map((id,i)=><li key={id} data-front={id} className={[lifted===id?'is-lifted':'',passed(id)?'is-passed':''].join(' ').trim()||undefined}><span className="sort-number">{passed(id)?'✓':String(i+1).padStart(2,'0')}</span><span className="sort-content"><strong>{fronts[id]?.title??'Cephe'}</strong><span>{order.slots.find(s=>s.frontId===id)?.text}</span></span>{passed(id)?<span className="drag-handle is-fixed"><span className="sr-only">Geçildi; yeri değişmez.</span></span>:<button className="drag-handle" disabled={disabled} aria-label={`${fronts[id]?.title} hamlesini taşı`} aria-describedby="route-keyboard-help" aria-pressed={lifted===id} onPointerDown={e=>start(e,id)} onKeyDown={e=>key(e,id)} onContextMenu={e=>e.preventDefault()}><GripVertical size={22}/></button>}</li>)}</ol><div className="sr-only" role="status" aria-live="polite">{announcement}</div></>;
}
