'use client';
import MediaInput from './media-input';
import Research,{ResearchLinks} from './research';
import AtlasOrder from './atlas-order';
import ExpeditionMap from './expedition-map';
import MorningReport from './morning-report';
import Logbook from './logbook';
import {clockText} from '@/lib/expedition/camps';
import {buildReport,pendingQuestions as openQuestions} from '@/lib/report';
import {logbook} from '@/lib/logbook';
import {laneSuggestion} from '@/lib/research';
import Horizon,{HorizonSummary} from './horizon';
import {CalendarDays,AudioLines,ClipboardCheck} from 'lucide-react';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Compass,Map,Plus,BookOpen,History,ArrowLeft,Check,ChevronRight,Download,WifiOff,RotateCcw,Settings,PenLine,X,Sunrise,Flag} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogClose} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {type State,type Front,type Dictation,fresh,ensureOrder,nextMove,labels,similarity,dayKey,directGoal} from '@/lib/domain';
import {questionInput} from '@/lib/questions';
import {localRead,localWrite,localWriteMany} from '@/lib/offline';
type Payload={id:string;kind:string;frontId?:string;text?:string;[key:string]:unknown};
type Snapshot={revision?:number;state:State;dictations:Dictation[];summary?:string;savedAt?:string};
type Modal='dictate'|'select'|'lanes'|'complete'|'edit'|'answer'|null;
export default function Berthier({userId}:{userId:string}) {
 const [state,setState]=useState<State>(fresh),[dictations,setDictations]=useState<Dictation[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[online,setOnline]=useState(true),[error,setError]=useState(''),[summary,setSummary]=useState('');
 const [mediaBusy,setMediaBusy]=useState(false),[external,setExternal]=useState(false),[savedAt,setSavedAt]=useState<string|null>(null);
 const [draft,setDraft]=useState(''),[processing,setProcessing]=useState(false),[saving,setSaving]=useState(false),[reply,setReply]=useState<Dictation|null>(null),[answerAsText,setAnswerAsText]=useState(false);
 const [view,setView]=useState('home'),[modal,setModal]=useState<Modal>(null),[context,setContext]=useState<string|undefined>(),[text,setText]=useState(''),[selected,setSelected]=useState<string[]>([]),[outbox,setOutbox]=useState<Payload[]>([]),[clock,setClock]=useState(Date.now());
 const revisionRef=useRef(-2),queueWrites=useRef(Promise.resolve()),processingRef=useRef(false),submitting=useRef(false),stateRef=useRef(state),locked=useRef(false),queueRef=useRef<Payload[]>([]),key=`${userId}:`,mounted=useRef(false),recording=useRef<Set<string>>(new Set());
 stateRef.current=state;
 useEffect(()=>{window.scrollTo({top:0,behavior:'instant'});},[view]);
 const adopt=useCallback(async(data:Snapshot)=>{if(data.revision!==undefined&&data.revision<revisionRef.current)return;if(data.revision!==undefined)revisionRef.current=data.revision;setState(data.state);stateRef.current=data.state;setDictations(data.dictations);const at=new Date().toISOString();setSavedAt(at);try{await localWrite(key+'snapshot',{...data,savedAt:at});}catch{setError('Cihaz önbelleği kullanılamıyor. Sunucudaki kayıtların güvende; çevrimdışı giriş kullanılamaz.');}},[key]);
 const refresh=useCallback(async()=>{try{const r=await fetch('/api/state');const data=await r.json() as Snapshot & {error?:string};if(!r.ok)throw Error(data.error);await adopt(data);setError('');}catch(e){setError(e instanceof Error?e.message:'Bağlantı kurulamadı. Son kayıt gösteriliyor.');}finally{setLoading(false);}},[adopt]);
 const call=useCallback(async(payload:Payload)=>{const r=await fetch('/api/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await r.json() as Snapshot & {error?:string};if(!r.ok)throw Error(data.error??'İşlem kaydedilemedi.');await adopt(data);return data as Snapshot;},[adopt]);
 const updateQueue=useCallback(async(q:Payload[])=>{queueRef.current=q;setOutbox(q);const saved=queueWrites.current.catch(()=>{}).then(()=>localWrite(key+'outbox',q));queueWrites.current=saved;await saved;},[key]);
 const flush=useCallback(async()=>{
 if(processingRef.current||!navigator.onLine)return;processingRef.current=true;setProcessing(true);
 try{while(queueRef.current.length){const payload=queueRef.current[0];
 // A quick durable save precedes the slower model request. Safe to retry with the same ID.
 if(payload.kind==='dictate'){const r=await fetch('/api/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,kind:'enqueue'})});if(!r.ok){const d=await r.json() as {error?:string};throw Error(d.error??'Metnin cihazda saklı; sunucuya kaydedilemedi.');}setSummary('Dikten kaydedildi. İşleniyor…');}
 const data=await call(payload);await updateQueue(queueRef.current.filter(x=>x.id!==payload.id));setSummary(data.summary??'Kaydedildi.');setError('');
 }}catch(e){setError(e instanceof Error?e.message:'Girdin kuyrukta; tekrar dene.');}finally{processingRef.current=false;setProcessing(false);}
 },[call,updateQueue]);
 // Recover accepted work on this or another device without relying on a local outbox.
 useEffect(()=>{const pending=dictations.filter(d=>d.status==='queued'&&!queueRef.current.some(p=>p.id===d.id));if(!pending.length)return;const additions=pending.map(d=>{const meta=JSON.parse(d.result??'{}');return {id:d.id,kind:meta.kind??'dictate',source:meta.source??'dictation',text:d.raw,...(d.context?{frontId:d.context}:{}),...(meta.replyTo?{replyTo:meta.replyTo}:{})};});void updateQueue([...queueRef.current,...additions]).then(flush).catch(()=>setError('Girdin sunucuda saklı. İşlemek için tekrar dene.'));},[dictations,updateQueue,flush]);
 useEffect(()=>{let live=true;async function init(){try{const cached=await localRead<Snapshot>(key+'snapshot');if(cached&&live){setState(cached.state);setDictations(cached.dictations);setSavedAt(cached.savedAt??null);}const q=await localRead<Payload[]>(key+'outbox')??[];queueRef.current=q;setOutbox(q);const saved=await localRead<{text:string;external:boolean}>(key+'media-text-draft');setDraft(saved?.text??await localRead<string>(key+'draft')??'');setExternal(saved?.external??false);}catch{setError('Cihaz önbelleği açılamadı. Bağlantı varken çalışabilirsin.');}if(live){mounted.current=true;setOnline(navigator.onLine);await refresh();void flush();}}
 void init();const connected=()=>{setOnline(true);void refresh().then(flush);};const disconnected=()=>setOnline(false);window.addEventListener('online',connected);window.addEventListener('offline',disconnected);const timer=setInterval(()=>{setClock(Date.now());},60000);if('serviceWorker'in navigator)void navigator.serviceWorker.register('/sw.js').then(()=>navigator.serviceWorker.ready).then(reg=>{reg.active?.postMessage({type:'CACHE_SHELL',assets:performance.getEntriesByType('resource').map(r=>r.name)});}).catch(()=>{});return()=>{live=false;window.removeEventListener('online',connected);window.removeEventListener('offline',disconnected);clearInterval(timer);};},[key,refresh,flush]);
 useEffect(()=>{if(mounted.current)void localWrite(key+'media-text-draft',{text:draft,external}).catch(()=>{});},[key,draft,external]);
 useEffect(()=>{const ctx=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>void}}).modelContext;if(!ctx)return;const ctrl=new AbortController();try{ctx.registerTool({name:'read_berthier_map',description:'Read saved fronts and today’s order. Does not modify records.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input:unknown){if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('No parameters accepted');return {fronts:Object.values(stateRef.current.fronts),order:ensureOrder(stateRef.current)};}},{signal:ctrl.signal});}catch{}return()=>ctrl.abort();},[]);
 // quiet: no toast (the map shows its own notice); silent: no toast and no summary line (the morning report shows the result in place).
 async function action(body:Omit<Payload,'id'>,options?:{quiet?:boolean;silent?:boolean}){if(locked.current)return;locked.current=true;setBusy(true);setError('');try{const data=await call({...body,id:crypto.randomUUID()} as Payload);if(!options?.silent)setSummary(data.summary??'Kaydedildi.');if(!options?.quiet&&!options?.silent)toast.success(data.summary??'Kaydedildi.');setModal(null);return true;}catch(e){await refresh();setError(e instanceof Error?e.message:'İşlem kaydedilemedi.');return false;}finally{locked.current=false;setBusy(false);}}
 async function submitDictation(){const inputText=modal==='dictate'||modal==='answer'?text:draft;if(!inputText.trim()||submitting.current||mediaBusy)return;submitting.current=true;setSaving(true);const payload:Payload={id:crypto.randomUUID(),kind:'dictate',source:modal==='answer'?JSON.parse(reply?.result??'{}').source??'dictation':external?'document':'dictation',text:inputText.trim(),...(context?{frontId:context}:{}),...(modal==='answer'&&reply?{replyTo:reply.id}:{})};
 try{await updateQueue([...queueRef.current,payload]);setText('');if(modal!=='answer'){setDraft('');setExternal(false);await localWrite(key+'media-text-draft',{text:'',external:false});await localWrite(key+'draft','');}setModal(null);setSummary(navigator.onLine?'Dikten cihazda saklandı; sunucuya aktarılıyor.':'Cihazda saklandı. Bağlantı gelince işlenecek.');void (async()=>{if(navigator.onLine){try{await fetch('/api/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,kind:'enqueue'})});}catch{}}void flush();})();}catch{setError('Girdi cihazda saklanamadı. Metnin bu alanda duruyor; silmeden tekrar dene.');}finally{submitting.current=false;setSaving(false);}}
 function answer(d:Dictation){setAnswerAsText(false);setReply(d);setContext(d.context??undefined);setText('');setModal('answer');}
 // A one-tap answer from the morning report goes through the same durable queue as a written one.
 async function sendAnswer(d:Dictation,value:string){if(submitting.current)return;submitting.current=true;const payload:Payload={id:crypto.randomUUID(),kind:'dictate',source:JSON.parse(d.result??'{}').source??'dictation',text:value,...(d.context?{frontId:d.context}:{}),replyTo:d.id};try{await updateQueue([...queueRef.current,payload]);void (async()=>{if(navigator.onLine){try{await fetch('/api/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,kind:'enqueue'})});}catch{}}void flush();})();}catch{setError('Yanıt cihazda saklanamadı; tekrar dene.');}finally{submitting.current=false;}}
 // Berthier's own records (report opening, logbook summaries) are not user actions: no summary line, no toast.
 async function record(kind:'reportOpen'|'logbookSummaries'){if(recording.current.has(kind))return;recording.current.add(kind);try{await call({id:crypto.randomUUID(),kind});}catch{}finally{recording.current.delete(kind);}}
 function openDictation(id?:string,prefill?:string){setContext(id);setText(prefill??draft);setModal('dictate');}
 function complete(f:Front){setContext(f.id);if(f.type==='lane'){setText('');setModal('complete');}else void action({kind:'complete',frontId:f.id,skip:!!f.moves.filter(m=>!m.doneAt)[1]},{quiet:view==='home'});}
 const order=ensureOrder(state),fronts=Object.values(state.fronts),front=state.fronts[view],active=fronts.filter(f=>f.status==='active'&&nextMove(f));
 const pendingQuestions=openQuestions(dictations,outbox,state.changes);
 // Karargâh cards: the morning report's sections and the expedition's day.
 const homeReport=view==='home'?buildReport(state,dictations,outbox,new Date(clock)):null,homeBook=view==='home'?logbook(state,dayKey(new Date(clock))):null;
 const answerQuestion=reply?JSON.parse(reply.result??'{}').question??'Yanıtın':'';const answerInput=answerAsText?{type:'text' as const,choices:[]}:questionInput(answerQuestion);
 const title=view==='home'?'Karargâh':view==='map'?'Harita':view==='horizon'?'Ufuk':view==='depot'?'Fikir deposu':view==='review'?'Haftalık teftiş':view==='report'?'Sabah raporu':view==='logbook'?'Sefer defteri':view==='history'?'Kayıt defteri':view==='settings'?'Tercihler':front?.title??'Karargâh';
 const date=new Date(clock).toLocaleDateString('tr-TR',{timeZone:'Europe/Istanbul',day:'numeric',month:'long',weekday:'long'});
 function selection(mode:'select'|'lanes'){setSelected(mode==='select'?order.slots.filter(x=>!x.doneAt).map(x=>x.frontId):fronts.filter(f=>f.type==='lane'&&f.status==='active').map(f=>f.id));setModal(mode);}
 function exportData(){const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),state,dictations,outbox},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`berthier-${dayKey()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <div className={`shell ${view==='home'?'is-home':''} ${view==='map'&&fronts.length?'is-map':''} ${view==='report'?'is-report':''} ${view==='logbook'?'is-logbook':''}`}><Toaster position="top-center" theme="dark"/><header className="masthead"><a href="/" className="brand"><span>berthier</span><span className="brand-asterisk" aria-hidden="true">✳</span></a><div className="header-actions"><button className="icon-button" aria-label="Kayıt defteri" onClick={()=>setView('history')}><History size={20}/></button><button className="icon-button" aria-label="Tercihler" onClick={()=>setView('settings')}><Settings size={20}/></button></div></header><main aria-busy={busy}>
 <div className="heading"><div>{view!=='home'?<button className="back" onClick={()=>setView(front?'map':'home')}><ArrowLeft size={16}/>{front?'Harita':'Karargâh'}</button>:<p className="date">{date}</p>}<h1>{title}</h1></div><span className="seal"><Compass size={32}/></span></div>
 {!online&&view!=='report'&&<div className="notice"><WifiOff size={18}/>Çevrimdışısın. Son kayıtlar gösteriliyor; diktelerin kuyrukta saklanır.</div>}
 {error&&<div role="alert" className="notice error">{error}<button disabled={busy} onClick={()=>{void refresh();void flush();}}>Tekrar dene</button></div>}
 {busy&&<p className="notice" role="status">Berthier işliyor. Girdin korunuyor…</p>}
 {summary&&view!=='report'&&<div className="summary" role="status"><span>{summary}</span><button onClick={()=>setView('history')}>Ayrıntı</button>{state.changes.at(-1)?.ops.some(o=>!o.undone)&&<button disabled={busy||!online} onClick={()=>action({kind:'undo',changeId:state.changes.at(-1)!.id})}>Geri al</button>}</div>}
 {outbox.length>0&&<div className="quiet queue-status" role="status">{processing?'Dikten arka planda işleniyor.':`${outbox.length} girdi işlenmeyi bekliyor.`}<button disabled={processing||!online} onClick={()=>void flush()}>Şimdi işle</button></div>}
 {loading&&!fronts.length?<p className="loading">Kayıtların açılıyor…</p>:<>
 {view==='home'&&<>
 {!fronts.length?<section className="orders"><div className="section-head"><h2>Günün emri</h2><span>İlk gün</span></div><h3 className="serif">Önce, zihninde yer aç.</h3><p>Kafandaki her şeyi söyle; dağınık olabilir. Cephelerini ve sıradaki somut hamlelerini çıkarayım; emri sen onayla.</p><label htmlFor="first">Berthier’e söyle</label><textarea id="first" value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Dersler, araştırmalar, başvurular, yarım kalanlar…"/><button className="light" disabled={!draft.trim()||saving} onClick={()=>{setContext(undefined);void submitDictation();}}>İlk haritamı oluştur</button><p className="caption">Sesle yazmak için iPhone klavyendeki mikrofonu kullanabilirsin.</p></section>:<>
 {!state.setup&&<section className="notice">Haritan hazır. Bu hafta hangi kulvarlar aktif olsun?<button disabled={busy} onClick={()=>selection('lanes')}>Kulvarları seç</button></section>}
 <AtlasOrder state={state} order={order} busy={busy} online={online} open={setView} complete={complete} edit={(f,value)=>{setContext(f.id);setText(value);setModal('edit');}} select={()=>selection('select')} action={action}/>
 </>}
 {pendingQuestions.map(d=>{const result=JSON.parse(d.result??'{}');return <section className="question-block" key={d.id}><h2>Bir şeyi netleştirelim</h2><p>{result.question}</p><button onClick={()=>answer(d)}>Yanıtla</button></section>;})}
 <div className="home-links"><button className="map-link" onClick={()=>setView('report')}><Sunrise/><div><h2>Sabah raporu</h2><p>{homeReport?.order.approvedAt?`Onaylandı · ${clockText(homeReport.order.approvedAt)}`:`Emir ${homeReport?.counts[0]||'yok'} · uyarı ${homeReport?.counts[1]||'yok'} · yer ${homeReport?.counts[2]||'yok'}`}</p></div><ChevronRight/></button><button className="map-link" onClick={()=>setView('logbook')}><Flag/><div><h2>Sefer defteri</h2><p>{homeBook?.window?`${homeBook.window.index}. gün / 14 · ${homeBook.camps} kamp alındı`:'İlk raporla başlar'}</p></div><ChevronRight/></button><ResearchLinks state={state} open={setView}/></div>{fronts.filter(f=>f.type==='lane'&&f.status==='held'&&laneSuggestion(state,f).startsWith('Önümüzdeki')).map(f=><div className="notice" key={f.id}>{f.title} bekletiliyor; tarihli kalemi ve hazırlık planı Ufuk’ta.<button disabled={busy||!online} onClick={()=>action({kind:'status',frontId:f.id,status:'active'})}>Aktif et</button></div>)}<HorizonSummary state={state} open={()=>setView('horizon')}/><button className="map-link" onClick={()=>setView('map')}><Map/><div><h2>Harita</h2><p>{fronts.length?`${fronts.filter(f=>f.status!=='closed').length} açık cephe, ${fronts.filter(f=>f.type==='lane'&&f.status==='active').length} aktif kulvar`:'Cephelerin burada bir araya gelecek.'}</p></div><ChevronRight/></button>
 <aside className="paper-note"><BookOpen/><div><h3>Hiçbir şey aklında kalmak zorunda değil.</h3><p>Ham diktelerin kayıt defterinde saklanır. Berthier’in değişikliklerini oradan geri alabilirsin.</p></div></aside></>}
 {(view==='depot'||view==='review')&&<Research state={state} busy={busy||!online} action={action} dictate={prefill=>openDictation(undefined,prefill)} review={view==='review'}/>}
 {view==='review'&&<button className="map-link logbook-link" onClick={()=>setView('logbook')}><Flag/><div><h2>Sefer defteri</h2><p>Berthier’in günlük kaydı ve seferin ölçümleri</p></div><ChevronRight/></button>}
 {view==='report'&&<MorningReport state={state} dictations={dictations} outbox={outbox} now={clock} online={online} busy={busy} savedAt={savedAt} action={action} select={()=>selection('select')} answer={answer} reply={(d,value)=>void sendAnswer(d,value)} back={()=>setView('home')} opened={()=>void record('reportOpen')}/>}
 {view==='logbook'&&<Logbook state={state} now={clock} online={online} back={()=>setView('home')} summarize={()=>void record('logbookSummaries')}/>}
 {view==='horizon'&&<Horizon state={state} busy={busy||!online} action={action} dictate={prefill=>openDictation(undefined,prefill)}/>}
 {view==='map'&&<>{!fronts.length?<div className="blank"><Map size={36}/><h2>Harita henüz boş.</h2><p>Kafandaki ilk işi söyle; buradan başlayalım.</p><button className="primary" onClick={()=>openDictation()}>Berthier’e söyle</button></div>:<><ExpeditionMap variant="atlas" state={state} order={order} editable={!busy&&online} onBack={()=>setView('home')} onOpen={setView} onList={()=>document.getElementById('harita-listesi')?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'})} reorder={ids=>action({kind:'reorder',ids,orderDate:order.date,orderSnapshot:JSON.stringify(order)},{quiet:true})}/><div id="harita-listesi" className="map-list">{Object.entries(labels).map(([type,label])=>{const group=fronts.filter(f=>f.type===type&&f.status!=='closed').sort((a,b)=>Number(b.status==='active')-Number(a.status==='active')||a.title.localeCompare(b.title,'tr'));return group.length>0&&<section className="front-group" key={type}><h2>{label}<span>{group.length}</span></h2>{group.map(f=><FrontRow key={f.id} f={f} open={()=>setView(f.id)}/>)}</section>;})}<details className="archive"><summary>Kapanan cepheler ({fronts.filter(f=>f.status==='closed').length})</summary>{fronts.filter(f=>f.status==='closed').map(f=><FrontRow key={f.id} f={f} open={()=>setView(f.id)}/>)}</details><button onClick={()=>selection('lanes')}>Aktif kulvarları seç</button></div></>}</>}
 {front&&<section className="front-detail">
 {front.type==='lane'&&<div className="bookmark"><BookOpen size={22}/><div><h2>Kaldığın yer</h2><p>{front.where||'Henüz not yok.'}</p>{front.question&&<><h3>Sıradaki soru</h3><p>{front.question}</p></>}</div></div>}
 <div className="status-controls" aria-label="Cephe durumu">{(front.type==='lane'?(['active','held','closed'] as const):(['active','closed'] as const)).map(status=><button aria-pressed={front.status===status} className={front.status===status?'chosen':''} disabled={busy||!online} key={status} onClick={()=>action({kind:'status',frontId:front.id,status})}>{{active:'Aktif',held:'Bekletilen',closed:'Kapalı'}[status]}</button>)}</div>
 <section className="next-panel"><p className="quiet">Sıradaki hamle</p><h2 className="move-text">{nextMove(front)?.text??'Henüz bir hamle yok.'}</h2>{nextMove(front)?.prerequisiteReason&&<p className="quiet">{nextMove(front)?.prerequisiteReason}</p>}<div className="row-actions"><button className="primary" disabled={busy||!online||!nextMove(front)} onClick={()=>complete(front)}><Check size={18}/>Bitti</button>{directGoal(front)&&<button disabled={busy||!online} onClick={()=>action({kind:'skipPrerequisite',frontId:front.id})}>Ön adıma gerek yok</button>}<button onClick={()=>{setContext(front.id);setText(nextMove(front)?.text??'');setModal('edit');}}>Düzenle</button></div></section>
 <button className="context-button" onClick={()=>openDictation(front.id)}><Plus size={18}/>Bu cepheye söyle</button>
 {front.moves.filter(m=>!m.doneAt).length>1&&<details className="archive"><summary>Sonraki hamle önerileri</summary>{front.moves.filter(m=>!m.doneAt).slice(1).map(m=><p className="history-move" key={m.id}>{m.text}</p>)}</details>}
 {fronts.filter(f=>f.id!==front.id&&f.status!=='closed'&&similarity(f.title,front.title)>=.4).map(f=><div className="notice" key={f.id}>{front.title} ve {f.title} aynı cephe olabilir.<button disabled={busy||!online} onClick={()=>action({kind:'merge',frontId:front.id,targetId:f.id})}>Birleştir</button></div>)}
 <details className="archive"><summary>Tarihler ve hazırlıklar</summary><Horizon state={state} busy={busy||!online} action={action} frontId={front.id} dictate={prefill=>openDictation(front.id,prefill)}/></details>{front.type==='lane'&&<details className="archive"><summary>Fikir deposu</summary><Research state={state} busy={busy||!online} action={action} laneId={front.id} dictate={prefill=>openDictation(front.id,prefill)}/></details>}<h2 className="subheading">Hamle geçmişi</h2>{front.moves.filter(m=>m.doneAt).reverse().map(m=><div className="history-move" key={m.id}><Check size={16}/><div>{m.text}<p className="quiet">{formatTime(m.doneAt!)}</p></div></div>)}{!front.moves.some(m=>m.doneAt)&&<p className="quiet">Tamamladığın hamleler burada saklanacak.</p>}
 <details className="archive"><summary>Bu cepheye söylenenler ({front.notes.length})</summary>{front.notes.slice().reverse().map((note,i)=><p className="raw-text" key={i}>{note}</p>)}</details></section>}
 {view==='history'&&<><p className="intro">Ham sözlerin ve haritada bıraktıkları iz. Eski bir değişikliği geri almak için aynı kaydın daha yeni değişikliklerini önce geri al.</p><h2 className="subheading">Değişiklikler</h2>{!state.changes.length&&<p className="quiet">Henüz değişiklik yok.</p>}{state.changes.slice().reverse().map(c=><details className="change-entry" key={c.id}><summary><span>{c.label}<small>{formatTime(c.at)}</small></span><span>{c.ops.every(o=>o.undone)?'Geri alındı':'Ayrıntı'}</span></summary><button disabled={busy||!online||c.ops.every(o=>o.undone)} onClick={()=>action({kind:'undo',changeId:c.id})}><RotateCcw size={16}/>Tümünü geri al</button>{c.ops.map((op,i)=><div className="op-row" key={i}><span>{op.key==='setup'?'İlk kurulum':op.key==='calendar'?'Tarihler ve hazırlık ayarları':op.key==='research'?'Depo ve teftiş':op.key.startsWith('order:')?'Günün emri':((op.after??op.before) as Front)?.title}{op.undone?' — geri alındı':''}</span><button disabled={busy||!online||op.undone} onClick={()=>action({kind:'undo',changeId:c.id,index:i})}>Geri al</button></div>)}</details>)}<h2 className="subheading">Ham dikteler</h2>{[...outbox.map(x=>({id:x.id,raw:x.text??'',context:x.frontId??null,created_at:'',status:'local',result:null})),...dictations.filter(d=>!outbox.some(x=>x.id===d.id))].map(d=><details className="change-entry" key={d.id}><summary><span>{d.raw.slice(0,80)}{d.raw.length>80?'…':''}<small>{d.created_at?formatTime(d.created_at):'Cihazda saklandı'}</small></span><span>{{done:'İşlendi',failed:'Bekliyor',question:'Soru var',queued:'Kuyrukta',local:'Kuyrukta'}[d.status]??d.status}</span></summary><p className="raw-text">{d.raw}</p>{d.created_at&&<button disabled={busy||!online||state.ideaImports?.includes(d.id)} onClick={()=>action({kind:'importIdeas',sourceId:d.id})}>{state.ideaImports?.includes(d.id)?'Fikirler tarandı':'Fikirleri depoya aktar'}</button>}{d.status==='failed'&&!outbox.some(x=>x.id===d.id)&&<button disabled={busy} onClick={async()=>{await updateQueue([...queueRef.current,{id:d.id,kind:JSON.parse(d.result??'{}').kind??'dictate',source:JSON.parse(d.result??'{}').source??'dictation',text:d.raw,...(d.context?{frontId:d.context}:{}),...(JSON.parse(d.result??'{}').replyTo?{replyTo:JSON.parse(d.result??'{}').replyTo}:{})}]);void flush();}}>Tekrar işle</button>}</details>)}</>}
 {view==='settings'&&<><div className="settings-list"><div><span>Telefon</span><strong>iPhone</strong></div><div><span>Saat dilimi</span><strong>İstanbul</strong></div><div><span>Günün başlangıcı</span><strong>04:00</strong></div><div><span>Sabah raporu</span><strong>08:30</strong></div><div><span>Haftalık teftiş</span><strong>Pazar 20:00</strong></div><div><span>Sessiz saatler</span><strong>23:00–07:30</strong></div><div><span>Üniversite maili</span><strong>Gmail’e düşüyor</strong></div></div><p className="intro">Rapor ve teftiş saatlerin kaydedildi. Bildirimler sonraki paketlerde etkinleşecek; Gmail ve Google Takvim bağlantıları şimdilik ertelendi; gelen evrak bölümü olmayacak.</p><section className="paper-note"><Compass/><div><h2>iPhone ana ekranına ekle</h2><p>Safari’de Paylaş menüsünü aç, “Ana Ekrana Ekle”yi seç. Berthier kendi penceresinde açılır.</p></div></section><button className="export" onClick={exportData}><Download size={18}/>Verilerimi dışa aktar</button><p className="quiet">JSON dosyası ham diktelerini, cephelerini ve değişiklik geçmişini içerir.</p></>}
 </>}
 </main>{view!=='report'&&<div className="atlas-bottom"><button className="dictation-bar" onClick={()=>openDictation(front?.id)}><span className="dictation-icon"><AudioLines size={22}/></span><span>Aklındakini bırak.<small>Berthier yerine yerleştirir.</small></span><Plus size={22}/></button><nav className="dock" aria-label="Ana gezinme"><button className={view==='home'||view==='logbook'?'nav-active':''} onClick={()=>setView('home')}><Compass size={20}/>Karargâh</button><button className={view==='map'||front?'nav-active':''} onClick={()=>setView('map')}><Map size={20}/>Harita</button><button className={view==='horizon'?'nav-active':''} onClick={()=>setView('horizon')}><CalendarDays size={20}/>Ufuk</button><button className={view==='review'?'nav-active':''} onClick={()=>setView('review')}><ClipboardCheck size={20}/>Teftiş</button></nav></div>}

 <Dialog open={modal!==null} onOpenChange={open=>{if(!open&&!busy&&!saving&&!mediaBusy)setModal(null);}}><DialogContent className="berthier-dialog" showCloseButton={false}><DialogClose asChild><button className="modal-close icon-button" disabled={busy||mediaBusy} aria-label="Kapat"><X size={20}/></button></DialogClose><DialogTitle>{modal==='answer'?'Yanıtın':modal==='dictate'?(context?`${state.fronts[context]?.title} için söyle`:'Berthier’e söyle'):modal==='select'?'Bugünün cepheleri':modal==='lanes'?'Bu haftanın aktif kulvarları':modal==='complete'?'Nerede kaldın?':'Hamleyi düzenle'}</DialogTitle><DialogDescription>{modal==='answer'?answerQuestion:modal==='complete'?'Tek cümle yeter. Sıradaki sorunu da söyleyebilirsin.':modal==='lanes'?'Odaklanmak istediklerini seç. Diğerleri haritada bekler; sayı sınırı yok.':modal==='select'?'İstediğin kadar cephe seçebilirsin. Hiçbirini seçmemek de mümkün.':modal==='edit'?'Yapmak istediğin eylemi yaz. Düzeltmeni benzer hamlelerde hatırlayacağım.':'Dağınık olabilir. Ham metnin saklanır ve değişiklikleri geri alabilirsin.'}</DialogDescription>
 {modal==='answer'&&<><label htmlFor="answer-text">{answerInput.type==='date'?'Tarih':answerInput.type==='time'?'Saat':'Cevabın'}</label>{answerInput.type==='text'?<textarea id="answer-text" autoFocus value={text} maxLength={20000} onChange={e=>setText(e.target.value)} placeholder="Cevabını yaz…"/>:<input id="answer-text" autoFocus type={answerInput.type} value={text} onInput={e=>setText(e.currentTarget.value)} onChange={e=>setText(e.target.value)}/>}<div className="row-actions">{answerInput.choices.map(choice=><button key={choice} aria-pressed={text===choice} onClick={()=>setText(choice)}>{choice}</button>)}</div>{questionInput(answerQuestion).type!=='text'&&<button onClick={()=>{setAnswerAsText(!answerAsText);setText('');}}>{answerAsText?'Seçerek yanıtla':'Yazarak yanıtla'}</button>}<button className="primary" disabled={saving||!text.trim()} onClick={()=>void submitDictation()}>Yanıtı gönder</button></>}
 {(modal==='dictate'||modal==='complete'||modal==='edit')&&<><label className="sr-only" htmlFor="dictation-text">{modal==='complete'?'Kaldığın yer':'Dikte metni'}</label><textarea id="dictation-text" autoFocus disabled={mediaBusy} maxLength={modal==='edit'?120:20000} value={text} onChange={e=>{setText(e.target.value);if(modal==='dictate')setDraft(e.target.value);}} placeholder={modal==='complete'?'Ne yaptın, sırada hangi soru var?':'Aklındaki her şeyi yaz…'}/><div className="row-actions"><button className="primary" disabled={saving||mediaBusy||!text.trim()||(modal!=='dictate'&&(busy||!online))} onClick={()=>modal==='dictate'?void submitDictation():modal==='complete'?void action({kind:'complete',frontId:context,text},{quiet:view==='home'}):void action({kind:'edit',frontId:context,text})}>{modal==='dictate'?'Berthier’e ver':'Kaydet'}</button>{modal==='complete'&&<button disabled={busy||!online} onClick={()=>action({kind:'complete',frontId:context,skip:true},{quiet:view==='home'})}>Atla</button>}</div>{modal==='dictate'&&<MediaInput userId={userId} onBusy={setMediaBusy} onText={async(value,fromDocument)=>{const combined=[text,value].filter(Boolean).join('\n\n');if(combined.length>20000)throw Error('Bu dikteye sığmıyor. Mevcut metni gönder, sonra dosyanı yeniden yazıya dök. Dosyan cihazında saklı.');await localWriteMany([[key+'media-text-draft',{text:combined,external:external||fromDocument}],[key+'media-draft',null]]);setExternal(external||fromDocument);setText(combined);setDraft(combined);}}/>}</>}
 {(modal==='select'||modal==='lanes')&&<><div className="choices">{modal==='select'&&order.slots.filter(x=>x.doneAt).map(x=><label className="choice is-passed" key={x.frontId}><Checkbox checked disabled/><span><strong>{state.fronts[x.frontId]?.title}</strong><small>Geçildi {clockText(x.doneAt!)} · bugünün rotasında kalır</small></span></label>)}{(modal==='select'?active.filter(f=>!order.slots.some(x=>x.frontId===f.id&&x.doneAt)):fronts.filter(f=>f.type==='lane'&&f.status!=='closed')).map(f=><label className="choice" key={f.id}><Checkbox checked={selected.includes(f.id)} onCheckedChange={checked=>setSelected(a=>checked?[...a,f.id]:a.filter(id=>id!==f.id))}/><span><strong>{f.title}</strong><small>{nextMove(f)?.text}</small></span></label>)}</div><p className="quiet">{selected.length+(modal==='select'?order.slots.filter(x=>x.doneAt).length:0)} cephe seçili</p><div className="row-actions"><button className="primary" disabled={busy||!online} onClick={()=>action({kind:modal==='select'?'select':'setup',ids:selected})}>{modal==='lanes'?'Seçimi kaydet':'Emri güncelle'}</button><button onClick={()=>setSelected([])}>Seçimi temizle</button></div></>}
 </DialogContent></Dialog></div>;
}
function formatTime(value:string){return new Date(value).toLocaleString('tr-TR',{timeZone:'Europe/Istanbul',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'});}
function FrontRow({f,open}:{f:Front;open:()=>void}){return <button className="front-row" onClick={open}><span className={`type-dot ${f.type}`}/><span className="front-row-body"><strong>{f.title}</strong><span>{f.type==='lane'&&f.where?f.where:nextMove(f)?.text??'Sıradaki hamle yok.'}</span><small>{f.status==='held'?'Bekletiliyor · ':''}{formatTime(f.touched)}</small></span><ChevronRight size={18}/></button>;}



