'use client';
import MediaInput from './media-input';
import Research,{depotSummary} from './research';
import Book,{ReviewCard} from './book';
import Review from './review';
import Today from './today';
import Ledger from './ledger';
import Settings from './settings';
import PageHead from './page-head';
import AtlasOrder from './atlas-order';
import SaySheet from './say-sheet';
import ExpeditionMap from './expedition-map';
import MorningReport from './morning-report';
import Logbook from './logbook';
import {StatusCard,OfflineStrip,type Notice,type NoticeBody,type ReceiptLine} from './status';
import Routines,{PatternPage,RoutineDetail,RecordSheet,FixSheet,type Fix} from './routines';
import {reminderFor,routineNotice,runningInfo} from '@/lib/routines';
import {effective,placedOf,receiptTitle,type Placement} from '@/lib/kinds';
import {clockText} from '@/lib/expedition/camps';
import {buildReport,pendingQuestions as openQuestions} from '@/lib/report';
import {laneSuggestion} from '@/lib/research';
import Horizon from './horizon';
import {reviewDue} from '@/lib/book';
import {CalendarDays,AudioLines,ArrowUp} from 'lucide-react';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Compass,Map,Plus,BookOpen,Check,ChevronDown,ChevronRight,Repeat,X} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogClose} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {changeNotice} from '@/lib/ledger';
import {atTime,dayMonth,longDay} from '@/lib/turkish';
import {calendarDay} from '@/lib/calendar';
import {type State,type Front,type Change,type Dictation,fresh,ensureOrder,nextMove,labels,similarity,dayKey,directGoal,typeNames} from '@/lib/domain';
import {questionInput} from '@/lib/questions';
import {localRead,localWrite,localWriteMany} from '@/lib/offline';
type Payload={id:string;kind:string;frontId?:string;text?:string;[key:string]:unknown};
type Snapshot={revision?:number;state:State;dictations:Dictation[];summary?:string;savedAt?:string;replayed?:boolean};
type Failed={body:Omit<Payload,'id'>;options?:{quiet?:boolean;silent?:boolean};id:string;error:string};
type Modal='dictate'|'select'|'lanes'|'complete'|'edit'|'answer'|'type'|null;
const TYPE={course:'DERS',lane:'PROJE',application:'BAŞVURU',general:'İŞ'};
// “Bu cephe ne?” (C3): what each type changes, in the order of the design.
const TYPES:[Front['type'],string,string][]=[['general','İş','Kısa, bitince kapanır · İş Düzlüğü'],['course','Ders','Ritmi dışarıdan: sınav, ödev · Ders Ovası'],['lane','Proje','Kaldığın yer ve fikirler; bekletilebilir · Proje Dağları'],['application','Başvuru','Son tarih ve belgeler · Başvuru Geçidi']];
const COUNTS:[number,string][]=[[1,'1'],[2,'2'],[3,'3'],[4,'4'],[7,'Her gün']];
// K8: what a dictation placed, as it stands after any later move.
function receipt(placed:Placement[],sourceId:string,change:Change|undefined,s:State):NoticeBody{const lines=effective(s,sourceId,placed);return {kind:'done',...receiptTitle(lines),lines,sourceId,changeId:change&&!change.ops.every(o=>o.undone)?change.id:undefined};}
export default function Berthier({userId}:{userId:string}) {
 const [state,setState]=useState<State>(fresh),[dictations,setDictations]=useState<Dictation[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[online,setOnline]=useState(true),[error,setError]=useState(''),[failed,setFailed]=useState<Failed|null>(null),[notice,setNotice]=useState<Notice|null>(null);
 const [mediaBusy,setMediaBusy]=useState(false),[external,setExternal]=useState(false),[savedAt,setSavedAt]=useState<string|null>(null);
 const [draft,setDraft]=useState(''),[processing,setProcessing]=useState(false),[saving,setSaving]=useState(false),[reply,setReply]=useState<Dictation|null>(null),[answerAsText,setAnswerAsText]=useState(false),[recordingAudio,setRecordingAudio]=useState(false);
 const [sheet,setSheet]=useState<string|null>(null),[fix,setFix]=useState<Fix>(null),[hidden,setHidden]=useState<string[]>([]),[typeCount,setTypeCount]=useState(false);
 const [view,setView]=useState('home'),[modal,setModal]=useState<Modal>(null),[context,setContext]=useState<string|undefined>(),[text,setText]=useState(''),[selected,setSelected]=useState<string[]>([]),[outbox,setOutbox]=useState<Payload[]>([]),[clock,setClock]=useState(Date.now());
 const revisionRef=useRef(-2),queueWrites=useRef(Promise.resolve()),processingRef=useRef(false),submitting=useRef(false),stateRef=useRef(state),locked=useRef(false),queueRef=useRef<Payload[]>([]),key=`${userId}:`,mounted=useRef(false),recording=useRef<Set<string>>(new Set()),noticeTimer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);
 stateRef.current=state;
 useEffect(()=>{window.scrollTo({top:0,behavior:'instant'});},[view]);
 // The single status card (design 1g): a result stays 8 seconds, then lives on in the change log.
 // A receipt with a second guess stays 12 seconds (K8); “Rutin olsun” holds it while the number is chosen.
 const show=useCallback((n:NoticeBody|null)=>{clearTimeout(noticeTimer.current);setNotice(n?{...n,id:Date.now()}:null);if(n?.kind==='done')noticeTimer.current=setTimeout(()=>setNotice(x=>x?.kind==='done'?null:x),n.lines?.some(l=>l.alt)?12000:8000);},[]);
 const adopt=useCallback(async(data:Snapshot)=>{if(data.revision!==undefined&&data.revision<revisionRef.current)return;if(data.revision!==undefined)revisionRef.current=data.revision;setState(data.state);stateRef.current=data.state;setDictations(data.dictations);const at=new Date().toISOString();setSavedAt(at);try{await localWrite(key+'snapshot',{...data,savedAt:at});}catch{setError('Cihaz önbelleği kullanılamıyor. Sunucudaki kayıtların güvende; çevrimdışı giriş kullanılamaz.');}},[key]);
 const refresh=useCallback(async()=>{try{const r=await fetch('/api/state');const data=await r.json() as Snapshot & {error?:string};if(!r.ok)throw Error(data.error);await adopt(data);setError('');}catch(e){if(navigator.onLine)setError(e instanceof Error?e.message:'Bağlantı kurulamadı. Son kayıt gösteriliyor.');}finally{setLoading(false);}},[adopt]);
 const call=useCallback(async(payload:Payload)=>{const r=await fetch('/api/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await r.json() as Snapshot & {error?:string};if(!r.ok)throw Error(data.error??'İşlem kaydedilemedi.');await adopt(data);return data as Snapshot;},[adopt]);
 const updateQueue=useCallback(async(q:Payload[])=>{queueRef.current=q;setOutbox(q);const saved=queueWrites.current.catch(()=>{}).then(()=>localWrite(key+'outbox',q));queueWrites.current=saved;await saved;},[key]);
 const flush=useCallback(async()=>{
 if(processingRef.current||!navigator.onLine)return;processingRef.current=true;setProcessing(true);
 try{while(queueRef.current.length){const payload=queueRef.current[0];
 // A quick durable save precedes the slower model request. Safe to retry with the same ID.
 if(payload.kind==='dictate'){const r=await fetch('/api/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,kind:'enqueue'})});if(!r.ok){const d=await r.json() as {error?:string};throw Error(d.error??'Metnin cihazda saklı; sunucuya kaydedilemedi.');}}
 const data=await call(payload);await updateQueue(queueRef.current.filter(x=>x.id!==payload.id));setError('');
 // What the dictation did shows above Söyle: Berthier's question, or the changes it made.
 const asked=data.dictations.find(d=>d.id===payload.id&&d.status==='question'),change=data.state.changes.find(c=>c.sourceId===payload.id);if(asked){const question=JSON.parse(asked.result??'{}').question??'';show({kind:'question',dictation:asked,question,choices:questionInput(question).choices});}else{const placed=placedOf(data.dictations.find(d=>d.id===payload.id));show(placed.length?receipt(placed,payload.id,change,data.state):change?{kind:'done',...changeNotice(change,data.state.fronts,data.state.routines),changeId:change.id}:{kind:'done',title:'İşlendi.',text:data.summary??''});}
 }}catch(e){setError(e instanceof Error?e.message:'Girdin kuyrukta; tekrar dene.');}finally{processingRef.current=false;setProcessing(false);}
 },[call,updateQueue,show]);
 // Recover accepted work on this or another device without relying on a local outbox.
 useEffect(()=>{const pending=dictations.filter(d=>d.status==='queued'&&!queueRef.current.some(p=>p.id===d.id));if(!pending.length)return;const additions=pending.map(d=>{const meta=JSON.parse(d.result??'{}');return {id:d.id,kind:meta.kind??'dictate',source:meta.source??'dictation',text:d.raw,...(d.context?{frontId:d.context}:{}),...(meta.replyTo?{replyTo:meta.replyTo}:{})};});void updateQueue([...queueRef.current,...additions]).then(flush).catch(()=>setError('Girdin sunucuda saklı. İşlemek için tekrar dene.'));},[dictations,updateQueue,flush]);
 useEffect(()=>{let live=true;async function init(){try{const cached=await localRead<Snapshot>(key+'snapshot');if(cached&&live){setState(cached.state);setDictations(cached.dictations);setSavedAt(cached.savedAt??null);}const q=await localRead<Payload[]>(key+'outbox')??[];const h=await localRead<{day:string;keys:string[]}>(key+'reminder-hidden');if(h?.day===dayKey())setHidden(h.keys);queueRef.current=q;setOutbox(q);const saved=await localRead<{text:string;external:boolean}>(key+'media-text-draft');setDraft(saved?.text??await localRead<string>(key+'draft')??'');setExternal(saved?.external??false);}catch{setError('Cihaz önbelleği açılamadı. Bağlantı varken çalışabilirsin.');}if(live){mounted.current=true;setOnline(navigator.onLine);await refresh();void flush();}}
 void init();const connected=()=>{setOnline(true);void refresh().then(flush);};const disconnected=()=>setOnline(false);window.addEventListener('online',connected);window.addEventListener('offline',disconnected);const timer=setInterval(()=>{setClock(Date.now());},60000);if('serviceWorker'in navigator)void navigator.serviceWorker.register('/sw.js').then(()=>navigator.serviceWorker.ready).then(reg=>{reg.active?.postMessage({type:'CACHE_SHELL',assets:performance.getEntriesByType('resource').map(r=>r.name)});}).catch(()=>{});return()=>{live=false;window.removeEventListener('online',connected);window.removeEventListener('offline',disconnected);clearInterval(timer);};},[key,refresh,flush]);
 useEffect(()=>{if(mounted.current)void localWrite(key+'media-text-draft',{text:draft,external}).catch(()=>{});},[key,draft,external]);
 useEffect(()=>{const ctx=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>void}}).modelContext;if(!ctx)return;const ctrl=new AbortController();try{ctx.registerTool({name:'read_berthier_map',description:'Read saved fronts and today’s order. Does not modify records.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input:unknown){if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('No parameters accepted');return {fronts:Object.values(stateRef.current.fronts),order:ensureOrder(stateRef.current)};}},{signal:ctrl.signal});}catch{}return()=>ctrl.abort();},[]);
 // quiet: no status card (the map shows its own notice there); silent: the screen shows the result in place (morning report).
 // A failed command stays on the status card with its request id until it is retried, dismissed or another command is sent.
 // “Tekrar dene” sends it again; the server applies an id at most once, and a replayed id claims no change of its own.
 async function action(body:Omit<Payload,'id'>,options?:{quiet?:boolean;silent?:boolean},id=crypto.randomUUID()){if(locked.current)return;locked.current=true;setBusy(true);setError('');setFailed(null);const prior=stateRef.current,before=prior.changes,undone=before.find(c=>c.id===body.changeId)?.label;try{const data=await call({...body,id} as Payload);if(!options?.quiet&&!options?.silent){const c=!data.replayed&&data.state.changes.length>before.length?data.state.changes.at(-1):undefined,saved=c&&routineNotice(String(body.kind),prior,data.state);show(saved?{kind:'done',title:saved.title,text:saved.text,changeId:c.id,fix:saved.sessionId}:body.kind==='undo'?{kind:'done',title:'Geri alındı.',text:undone?undone.replace(/[.]?$/,'.'):''}:c?{kind:'done',...changeNotice(c,data.state.fronts,data.state.routines),changeId:c.id}:{kind:'done',title:(data.summary||'Kaydedildi').replace(/[.]?$/,'.'),text:''});}setModal(null);return true;}catch(e){await refresh();setFailed({body,options,id,error:e instanceof Error?e.message:'İşlem kaydedilemedi.'});return false;}finally{locked.current=false;setBusy(false);}}
 // The map's own notices (a camp taken, a new order saved) go to the same card, with “Geri al” for that change.
 // Rutinler: the reminder hidden for today (×), a receipt's second guess, and the routine context of Söyle.
 function hide(k:string){const keys=[...hidden,k];setHidden(keys);void localWrite(key+'reminder-hidden',{day:dayKey(),keys}).catch(()=>{});}
 function alt(line:ReceiptLine,sourceId:string,count?:number){if(line.alt?.to==='merge')void action({kind:'routineMerge',routineId:line.ref.split(':')[1],targetId:line.alt.targetId,sourceId,ref:line.ref});else if(line.alt)void action({kind:'rekind',sourceId,ref:line.ref,to:line.alt.to,...(count?{count}:{})});}
 function mapNotice(message:string){const [first,...rest]=message.split(/(?<=\.) /),c=stateRef.current.changes.at(-1);show({kind:'done',title:first,text:rest.join(' '),changeId:c&&!c.ops.every(o=>o.undone)?c.id:undefined});}
 async function submitDictation(){const inputText=modal==='dictate'||modal==='answer'?text:draft;if(!inputText.trim()||submitting.current||mediaBusy)return;submitting.current=true;setSaving(true);const payload:Payload={id:crypto.randomUUID(),kind:'dictate',source:modal==='answer'?JSON.parse(reply?.result??'{}').source??'dictation':external?'document':'dictation',text:inputText.trim(),...(context?{frontId:context}:{}),...(modal==='answer'&&reply?{replyTo:reply.id}:{})};
 try{await updateQueue([...queueRef.current,payload]);setText('');if(modal!=='answer'){setDraft('');setExternal(false);await localWrite(key+'media-text-draft',{text:'',external:false});await localWrite(key+'draft','');}setModal(null);void (async()=>{if(navigator.onLine){try{await fetch('/api/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,kind:'enqueue'})});}catch{}}void flush();})();}catch{setError('Girdi cihazda saklanamadı. Metnin bu alanda duruyor; silmeden tekrar dene.');}finally{submitting.current=false;setSaving(false);}}
 // A failed dictation goes back into the device queue with its original id, source and reply link.
 async function retry(d:Dictation){const meta=JSON.parse(d.result??'{}');await updateQueue([...queueRef.current,{id:d.id,kind:meta.kind??'dictate',source:meta.source??'dictation',text:d.raw,...(d.context?{frontId:d.context}:{}),...(meta.replyTo?{replyTo:meta.replyTo}:{})}]);void flush();}
 function answer(d:Dictation){setAnswerAsText(false);setReply(d);setContext(d.context??undefined);setText('');setModal('answer');}
 // A one-tap answer from the morning report goes through the same durable queue as a written one.
 async function sendAnswer(d:Dictation,value:string){if(submitting.current)return;submitting.current=true;const payload:Payload={id:crypto.randomUUID(),kind:'dictate',source:JSON.parse(d.result??'{}').source??'dictation',text:value,...(d.context?{frontId:d.context}:{}),replyTo:d.id};try{await updateQueue([...queueRef.current,payload]);void (async()=>{if(navigator.onLine){try{await fetch('/api/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,kind:'enqueue'})});}catch{}}void flush();})();}catch{setError('Yanıt cihazda saklanamadı; tekrar dene.');}finally{submitting.current=false;}}
 // Berthier's own records (report opening, logbook summaries) are not user actions: no summary line, no toast.
 async function record(kind:'reportOpen'|'logbookSummaries'){if(recording.current.has(kind))return;recording.current.add(kind);try{await call({id:crypto.randomUUID(),kind});}catch{}finally{recording.current.delete(kind);}}
 // Defter's and Karargâh's review card: an open review continues where it was left, otherwise a new one starts.
 async function startReview(){if(state.review&&!state.review.completedAt){setView('review');return;}if(await action({kind:'reviewStart'},{silent:true}))setView('review');}
 function openDictation(id?:string,prefill?:string){setContext(id);setText(prefill??draft);setModal('dictate');}
 function complete(f:Front){setContext(f.id);if(f.type==='lane'){setText('');setModal('complete');}else void action({kind:'complete',frontId:f.id,skip:!!f.moves.filter(m=>!m.doneAt)[1]});}
 const order=ensureOrder(state),fronts=Object.values(state.fronts),front=state.fronts[view],active=fronts.filter(f=>f.status==='active'&&nextMove(f));
 const pendingQuestions=openQuestions(dictations,outbox,state.changes);
 // Karargâh cards: the morning report's sections and the expedition's day.
 const homeReport=view==='home'?buildReport(state,dictations,outbox,new Date(clock)):null;
 const answerQuestion=reply?JSON.parse(reply.result??'{}').question??'Yanıtın':'';const answerInput=answerAsText?{type:'text' as const,choices:[]}:questionInput(answerQuestion);
 const title=view==='routines'?'Rutinler':view==='home'?'Karargâh':view==='map'?'Harita':view==='horizon'?'Ufuk':view==='depot'?'Fikir deposu':view==='review'?'Haftalık teftiş':view==='report'?'Sabah raporu':view==='logbook'?'Sefer defteri':view==='history'?'Kayıt defteri':view==='settings'?'Tercihler':front?.title??'Karargâh';
 // One tab per place (design 1d); Defter holds the review, the depot, the change log, preferences and the logbook.
 // K6: Rutinler took Harita's slot; the map, the fronts and the morning report sit under Karargâh.
 const tab=view==='home'||view==='map'||view==='report'||front?'home':view.startsWith('routine')?'routines':view==='horizon'?'horizon':['book','review','depot','history','settings','logbook'].includes(view)?'book':'';
 // Views that draw their own head (no brand bar, no generic heading); and where each page's back link goes.
 const ownHead=['home','report','logbook','book','review','horizon'].includes(view)||view.startsWith('routine')||(view==='map'&&fronts.length>0),back:[string,string]=front?['map','Harita']:['depot','history','settings'].includes(view)?['book','Defter']:['',''];
 // Text sheets grow with their text; past the visible height the field scrolls inside the sheet.
 const fit=(el:HTMLTextAreaElement|null)=>{if(el){el.style.height='auto';el.style.height=el.scrollHeight+2+'px';}};
 // “10:12’deki kayıt” for the offline strip: when the shown data last came from the server.
 const saved=savedAt?(calendarDay(new Date(savedAt))===calendarDay(new Date(clock))?'':dayMonth(calendarDay(new Date(savedAt)))+' ')+atTime(clockText(savedAt))+'ki kayıt':'son kayıt';
 // A disabled button says why (B14).
 const why=!online?'Bağlantı gelince yapılabilir; diktelerin cihazda saklanır.':busy?'Berthier işliyor…':'';
 function selection(mode:'select'|'lanes'){setSelected(mode==='select'?order.slots.filter(x=>!x.doneAt).map(x=>x.frontId):fronts.filter(f=>f.type==='lane'&&f.status==='active').map(f=>f.id));setModal(mode);}
 function exportData(){const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),state,dictations,outbox},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`berthier-${dayKey()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <div className={`shell ${view==='home'?'is-home':''} ${view==='map'&&fronts.length?'is-map':''} ${view==='report'?'is-report':''} ${view==='logbook'?'is-logbook':''} ${view==='review'?'is-review':''} ${view==='routines'?'is-routines':''} ${view==='routine-pattern'?'is-pattern':''}`}>{!online&&<OfflineStrip saved={saved} queued={outbox.length}/>}<main aria-busy={busy}>
 {!ownHead&&<PageHead title={title} back={back[1]} onBack={back[0]?()=>setView(back[0]):undefined} meta={view==='depot'?depotSummary(state):front?<><button className="page-type" aria-label={`Tür: ${typeNames[front.type]}. Değiştir`} onClick={()=>{setTypeCount(false);setModal('type');}}>{TYPE[front.type]}<ChevronDown size={14}/></button> · {{active:'AKTİF',held:'BEKLETİLİYOR',closed:'KAPANDI'}[front.status]}</>:undefined}/>}
 {loading&&!fronts.length?<p className="loading">Kayıtların açılıyor…</p>:<>
 {view==='home'&&<><div className="hq-top"><span>{longDay(dayKey(new Date(clock))).replace(' ',' · ')}</span>{savedAt&&<span><Check size={14}/>KAYITLI · {clockText(savedAt)}</span>}</div><h1 className="hq-title">Karargâh</h1>
 {!fronts.length?<section className="orders"><div className="section-head"><h2>Günün emri</h2><span>İlk gün</span></div><h3 className="serif">Önce, zihninde yer aç.</h3><p>Kafandaki her şeyi söyle; dağınık olabilir. Cephelerini ve sıradaki somut hamlelerini çıkarayım; emri sen onayla.</p><label htmlFor="first">Berthier’e söyle</label><textarea id="first" value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Dersler, araştırmalar, başvurular, yarım kalanlar…"/><button className="light" disabled={!draft.trim()||saving} onClick={()=>{setContext(undefined);void submitDictation();}}>İlk haritamı oluştur</button><p className="caption">Sesle yazmak için iPhone klavyendeki mikrofonu kullanabilirsin.</p></section>:<>
 {!state.setup&&<section className="notice">Haritan hazır. Bu hafta hangi projeler aktif olsun?<button disabled={busy} onClick={()=>selection('lanes')}>Projeleri seç</button></section>}
 {reviewDue(state,new Date(clock))&&<ReviewCard state={state} now={clock} busy={busy} online={online} why={why} review={()=>void startReview()}/>}<AtlasOrder state={state} order={order} busy={busy} online={online} why={why} say={id=>openDictation(id)} open={setView} complete={complete} edit={(f,value)=>{setContext(f.id);setText(value);setModal('edit');}} select={()=>selection('select')} action={action}/>
 {fronts.filter(f=>f.type==='lane'&&f.status==='held'&&laneSuggestion(state,f).startsWith('Önümüzdeki')).map(f=><div className="notice" key={f.id}>{f.title} bekletiliyor; tarihli kalemi ve hazırlık planı Ufuk’ta.<button disabled={busy||!online} onClick={()=>action({kind:'status',frontId:f.id,status:'active'})}>Aktif et</button></div>)}
 <Today state={state} now={clock} routines={()=>setView('routines')} report={homeReport!} busy={busy} online={online} action={action} reply={(d,value)=>void sendAnswer(d,value)} write={answer} open={()=>setView('report')}/>
 </>}</>}
 {view==='routines'&&<Routines state={state} now={clock} busy={busy} online={online} why={why} action={action} open={setView} record={setSheet} say={()=>openDictation('routines')}/>}
 {view==='routine-pattern'&&<PatternPage state={state} now={clock} busy={busy} online={online} why={why} action={action} back={()=>setView('routines')}/>}
 {view.startsWith('routine:')&&<RoutineDetail state={state} id={view.slice(8)} now={clock} busy={busy} online={online} why={why} action={action} back={()=>setView('routines')} record={setSheet}/>}
 {view==='depot'&&<Research state={state} busy={busy||!online} action={action}/>}
 {view==='book'&&<Book state={state} dictations={dictations} outbox={outbox} now={clock} busy={busy} online={online} why={why} open={setView} review={()=>void startReview()}/>}
 {view==='review'&&<Review state={state} now={clock} busy={busy} online={online} why={why} action={action} close={()=>setView('book')} horizon={()=>setView('horizon')} pattern={()=>setView('routine-pattern')}/>}
  {view==='report'&&<MorningReport state={state} dictations={dictations} outbox={outbox} now={clock} online={online} busy={busy} action={action} select={()=>selection('select')} answer={answer} reply={(d,value)=>void sendAnswer(d,value)} back={()=>setView('home')} opened={()=>void record('reportOpen')}/>}
 {view==='logbook'&&<Logbook state={state} now={clock} online={online} back={()=>setView('book')} summarize={()=>void record('logbookSummaries')}/>}
 {view==='horizon'&&<Horizon state={state} busy={busy||!online} action={action}/>}
 {view==='map'&&<>{!fronts.length?<div className="blank"><Map size={36}/><h2>Harita henüz boş.</h2><p>Kafandaki ilk işi söyle; buradan başlayalım.</p><button className="primary" onClick={()=>openDictation()}>Berthier’e söyle</button></div>:<><ExpeditionMap variant="atlas" state={state} order={order} editable={!busy&&online} notify={mapNotice} onBack={()=>setView('home')} onOpen={setView} onList={()=>document.getElementById('harita-listesi')?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'})} reorder={ids=>action({kind:'reorder',ids,orderDate:order.date,orderSnapshot:JSON.stringify(order)},{quiet:true})}/><div id="harita-listesi" className="map-list">{Object.entries(labels).map(([type,label])=>{const group=fronts.filter(f=>f.type===type&&f.status!=='closed').sort((a,b)=>Number(b.status==='active')-Number(a.status==='active')||a.title.localeCompare(b.title,'tr'));return group.length>0&&<section className="front-group" key={type}><h2>{label}<span>{group.length}</span></h2>{group.map(f=><FrontRow key={f.id} f={f} open={()=>setView(f.id)}/>)}</section>;})}<details className="archive"><summary>Kapanan cepheler ({fronts.filter(f=>f.status==='closed').length})</summary>{fronts.filter(f=>f.status==='closed').map(f=><FrontRow key={f.id} f={f} open={()=>setView(f.id)}/>)}</details><button onClick={()=>selection('lanes')}>Aktif projeleri seç</button></div></>}</>}
 {front&&<section className="front-detail">
 {front.type==='lane'&&<div className="bookmark"><BookOpen size={22}/><div><h2>Kaldığın yer</h2><p>{front.where||'Henüz not yok.'}</p>{front.question&&<><h3>Sıradaki soru</h3><p>{front.question}</p></>}</div></div>}
 <div className="status-controls" aria-label="Cephe durumu">{(front.type==='lane'?(['active','held','closed'] as const):(['active','closed'] as const)).map(status=><button aria-pressed={front.status===status} className={front.status===status?'chosen':''} disabled={busy||!online} key={status} onClick={()=>action({kind:'status',frontId:front.id,status})}>{{active:'Aktif',held:'Bekletilen',closed:'Kapalı'}[status]}</button>)}</div>
 <section className="next-panel"><p className="quiet">Sıradaki hamle</p><h2 className="move-text">{nextMove(front)?.text??'Henüz bir hamle yok.'}</h2>{nextMove(front)?.prerequisiteReason&&<p className="quiet">{nextMove(front)?.prerequisiteReason}</p>}<div className="row-actions"><button className="btn-main" disabled={busy||!online||!nextMove(front)} onClick={()=>complete(front)}><Check size={18}/>Bitti</button>{directGoal(front)&&<button disabled={busy||!online} onClick={()=>action({kind:'skipPrerequisite',frontId:front.id})}>Ön adıma gerek yok</button>}<button onClick={()=>{setContext(front.id);setText(nextMove(front)?.text??'');setModal('edit');}}>Düzenle</button></div>{why&&nextMove(front)&&<p className="why">{why}</p>}</section>
 <button className="context-button" onClick={()=>openDictation(front.id)}><Plus size={18}/>Bu cepheye söyle</button>
 {front.moves.filter(m=>!m.doneAt).length>1&&<details className="archive"><summary>Sonraki hamle önerileri</summary>{front.moves.filter(m=>!m.doneAt).slice(1).map(m=><p className="history-move" key={m.id}>{m.text}</p>)}</details>}
 {fronts.filter(f=>f.id!==front.id&&f.status!=='closed'&&similarity(f.title,front.title)>=.4).map(f=><div className="notice" key={f.id}>{front.title} ve {f.title} aynı cephe olabilir.<button disabled={busy||!online} onClick={()=>action({kind:'merge',frontId:front.id,targetId:f.id})}>Birleştir</button></div>)}
 <details className="archive"><summary>Tarihler ve hazırlıklar</summary><Horizon state={state} busy={busy||!online} action={action} frontId={front.id}/></details>{front.type==='lane'&&<details className="archive"><summary>Fikir deposu</summary><Research state={state} busy={busy||!online} action={action} laneId={front.id}/></details>}<h2 className="subheading">Hamle geçmişi</h2>{front.moves.filter(m=>m.doneAt).reverse().map(m=><div className="history-move" key={m.id}><Check size={16}/><div>{m.text}<p className="quiet">{formatTime(m.doneAt!)}</p></div></div>)}{!front.moves.some(m=>m.doneAt)&&<p className="quiet">Tamamladığın hamleler burada saklanacak.</p>}
 <details className="archive"><summary>Bu cepheye söylenenler ({front.notes.length})</summary>{front.notes.slice().reverse().map((note,i)=><p className="raw-text" key={i}>{note}</p>)}</details></section>}
 {view==='history'&&<Ledger state={state} dictations={dictations} outbox={outbox} now={clock} busy={busy} online={online} processing={processing} action={action} retry={d=>void retry(d)}/>}
 {view==='settings'&&<Settings state={state} queued={outbox.length} savedAt={savedAt} busy={busy} online={online} why={why} action={action} exportData={exportData}/>}
 </>}
 </main><StatusCard notice={notice?.kind==='question'&&!pendingQuestions.some(d=>d.id===notice.dictation.id)?null:notice} error={failed?.error||error} online={online} processing={processing} queued={outbox.length} busy={busy} see={()=>{show(null);setView('history');}} undo={changeId=>void action({kind:'undo',changeId})} retry={()=>{setError('');if(failed)void action(failed.body,failed.options,failed.id).then(flush);else void refresh().then(flush);}} dismiss={()=>show(null)} clearError={()=>{setFailed(null);setError('');}} reply={(d,value)=>{show(null);void sendAnswer(d,value);}} write={d=>{show(null);answer(d);}} running={runningInfo(state,new Date(clock))} reminder={reminderFor(state,new Date(clock),hidden)} finish={()=>void action({kind:'routineFinish'})} fixEnd={()=>setFix({running:true})} fix={id=>{show(null);setFix({sessionId:id});}} start={r=>void action(r.timer?{kind:'routineStart',routineId:r.routineId}:{kind:'routineLog',routineId:r.routineId},r.timer?{quiet:true}:undefined)} skip={r=>void action({kind:'routineSkip',routineId:r.routineId,day:dayKey()})} hide={hide} alt={alt} keep={()=>clearTimeout(noticeTimer.current)}/>
 {view!=='report'&&view!=='review'&&view!=='routine-pattern'&&<nav className="tabbar" aria-label="Ana gezinme"><button aria-current={tab==='home'?'page':undefined} onClick={()=>setView('home')}><Compass size={22}/>Karargâh</button><button aria-current={tab==='routines'?'page':undefined} onClick={()=>setView('routines')}><Repeat size={22}/>Rutinler</button><button className="say-button" aria-label={outbox.length?`Söyle · ${outbox.length} girdi cihazda`:undefined} onClick={()=>openDictation(front?.id)}><span className={processing&&online?'say-disc is-working':'say-disc'}><AudioLines size={24}/>{outbox.length>0&&!(processing&&online)&&<span className="say-badge">{outbox.length}</span>}</span>Söyle</button><button aria-current={tab==='horizon'?'page':undefined} onClick={()=>setView('horizon')}><CalendarDays size={22}/>Ufuk</button><button aria-current={tab==='book'?'page':undefined} onClick={()=>setView('book')}><BookOpen size={22}/>Defter</button></nav>}

 <SaySheet open={modal==='dictate'||modal==='answer'||modal==='complete'||modal==='edit'} locked={busy||saving||mediaBusy} onClose={()=>setModal(null)} bare={modal==='dictate'&&recordingAudio} quietDescription={modal==='dictate'} title={modal==='answer'?'Yanıtın':modal==='complete'?'Nerede kaldın?':modal==='edit'?'Hamleyi düzenle':'Berthier’e söyle'} description={modal==='answer'?answerQuestion:modal==='complete'?'Tek cümle yeter. Sıradaki sorunu da söyleyebilirsin.':modal==='edit'?'Yapmak istediğin eylemi yaz. Düzeltmeni benzer hamlelerde hatırlayacağım.':'Dağınık olabilir. Ham metnin saklanır ve değişiklikleri geri alabilirsin.'}>
 {modal==='answer'&&<>{answerInput.type==='text'?<textarea id="answer-text" className="say-text" aria-label="Cevabın" autoFocus ref={fit} value={text} maxLength={20000} onChange={e=>setText(e.target.value)} placeholder="Cevabını yaz…"/>:<input id="answer-text" className="say-field" aria-label={answerInput.type==='date'?'Tarih':'Saat'} autoFocus type={answerInput.type} value={text} onInput={e=>setText(e.currentTarget.value)} onChange={e=>setText(e.target.value)}/>}{answerInput.choices.length>0&&<div className="say-choices">{answerInput.choices.map(choice=><button key={choice} aria-pressed={text===choice} onClick={()=>setText(choice)}>{choice}</button>)}</div>}<div className="say-row">{questionInput(answerQuestion).type!=='text'&&<button className="text-button" onClick={()=>{setAnswerAsText(!answerAsText);setText('');}}>{answerAsText?'Seçerek yanıtla':'Yazarak yanıtla'}</button>}<span className="say-spacer"/><button className="btn-main" disabled={saving||!text.trim()} onClick={()=>void submitDictation()}>Yanıtı gönder</button></div></>}
 {(modal==='dictate'||modal==='complete'||modal==='edit')&&<>{modal==='dictate'&&!recordingAudio&&context==='routines'&&<button className="say-context" aria-label="Yeni rutin bağlamını kaldır" onClick={()=>setContext(undefined)}><Repeat size={13}/>Yeni rutin<X size={14}/></button>}{modal==='dictate'&&!recordingAudio&&context&&state.fronts[context]&&<button className="say-context" aria-label={`${state.fronts[context].title} bağlamını kaldır`} onClick={()=>setContext(undefined)}><span className={`say-context-bar ${state.fronts[context].type}`}/>{state.fronts[context].title} için<X size={14}/></button>}{!(modal==='dictate'&&recordingAudio)&&<><label className="sr-only" htmlFor="dictation-text">{modal==='complete'?'Kaldığın yer':modal==='edit'?'Hamle':'Dikte metni'}</label><textarea id="dictation-text" className="say-text" ref={fit} autoFocus disabled={mediaBusy} maxLength={modal==='edit'?120:20000} value={text} onChange={e=>{setText(e.target.value);if(modal==='dictate')setDraft(e.target.value);}} placeholder={modal==='complete'?'Ne yaptın, sırada hangi soru var?':context==='routines'?'Haftada 4 yüz yogası, hafta içi her sabah sprint…':'Aklındaki her şeyi yaz…'}/></>}{modal==='dictate'?<MediaInput userId={userId} onBusy={setMediaBusy} onRecording={setRecordingAudio} send={<button className="say-send" aria-label="Berthier’e ver" title="Berthier’e ver" disabled={saving||mediaBusy||!text.trim()} onClick={()=>void submitDictation()}><ArrowUp size={20}/></button>} onText={async(value,fromDocument)=>{const combined=[text,value].filter(Boolean).join('\n\n');if(combined.length>20000)throw Error('Bu dikteye sığmıyor. Mevcut metni gönder, sonra dosyanı yeniden yazıya dök. Dosyan cihazında saklı.');await localWriteMany([[key+'media-text-draft',{text:combined,external:external||fromDocument}],[key+'media-draft',null]]);setExternal(external||fromDocument);setText(combined);setDraft(combined);}}/>:<div className="say-row">{modal==='complete'&&<button className="btn-quiet" disabled={busy||!online} onClick={()=>action({kind:'complete',frontId:context,skip:true})}>Atla</button>}<span className="say-spacer"/><button className="btn-main" disabled={saving||busy||!online||!text.trim()} onClick={()=>modal==='complete'?void action({kind:'complete',frontId:context,text}):void action({kind:'edit',frontId:context,text})}>Kaydet</button></div>}{modal!=='dictate'&&why&&<p className="why">{why}</p>}</>}
 </SaySheet>
 <SaySheet open={modal==='type'&&!!front} onClose={()=>setModal(null)} locked={busy} title="Bu cephe ne?" description={front?`${front.was?.length?'Türünü':'Berthier'} “${typeNames[front.type]}” ${front.was?.length?'yaptın':'dedi'}. Değiştirirsen benzer cephelerde hatırlarım.`:''}>
 {front&&<div className="type-list">{TYPES.map(([t,name,note])=><button key={t} className={front.type===t?'type-row is-current':'type-row'} aria-pressed={front.type===t} disabled={busy||!online} onClick={()=>{if(front.type!==t)void action({kind:'retype',frontId:front.id,type:t}).then(ok=>{if(ok)setModal(null);});}}><span className={`type-bar ${t}`}/><span><strong>{name}</strong><small>{note}</small></span>{front.type===t?<Check size={18}/>:<span/>}</button>)}
 <button className="type-row" aria-expanded={typeCount} disabled={busy||!online||front.status==='closed'} onClick={()=>setTypeCount(!typeCount)}><Repeat size={16}/><span><strong>Rutin</strong><small>Tekrar ediyor; Rutinler’e taşınır, cephe kapanır</small></span><span/></button>
 {typeCount&&<div className="say-choices" role="group" aria-label="Haftada kaç?">{COUNTS.map(([n,label])=><button key={n} disabled={busy||!online} onClick={()=>void action({kind:'retype',frontId:front.id,type:'routine',count:n}).then(ok=>{if(ok){setModal(null);setView('routines');}})}>{label}</button>)}</div>}
 <p className="say-foot">Kayıt defterinden geri alınır.</p>{why&&<p className="why">{why}</p>}</div>}
 </SaySheet>
 <RecordSheet state={state} id={sheet} now={clock} busy={busy} online={online} why={why} action={action} close={()=>setSheet(null)} open={setView}/>
 <FixSheet key={JSON.stringify(fix)} state={state} fix={fix} busy={busy} online={online} why={why} action={action} close={()=>setFix(null)}/>
 <Dialog open={modal==='select'||modal==='lanes'} onOpenChange={open=>{if(!open&&!busy)setModal(null);}}><DialogContent className="berthier-dialog" showCloseButton={false}><DialogClose asChild><button className="modal-close icon-button" disabled={busy} aria-label="Kapat"><X size={20}/></button></DialogClose><DialogTitle>{modal==='lanes'?'Bu haftanın aktif projeleri':'Cephe ekle / çıkar'}</DialogTitle><DialogDescription>{modal==='lanes'?'Odaklanmak istediklerini seç. Diğerleri haritada bekler; sayı sınırı yok.':'İstediğin kadar cephe seçebilirsin. Hiçbirini seçmemek de mümkün.'}</DialogDescription>
 {(modal==='select'||modal==='lanes')&&<><div className="choices">{modal==='select'&&order.slots.filter(x=>x.doneAt).map(x=><label className="choice is-passed" key={x.frontId}><Checkbox checked disabled/><span><strong>{state.fronts[x.frontId]?.title}</strong><small>Geçildi {clockText(x.doneAt!)} · bugünün rotasında kalır</small></span></label>)}{(modal==='select'?active.filter(f=>!order.slots.some(x=>x.frontId===f.id&&x.doneAt)):fronts.filter(f=>f.type==='lane'&&f.status!=='closed')).map(f=><label className="choice" key={f.id}><Checkbox checked={selected.includes(f.id)} onCheckedChange={checked=>setSelected(a=>checked?[...a,f.id]:a.filter(id=>id!==f.id))}/><span><strong>{f.title}</strong><small>{nextMove(f)?.text}</small></span></label>)}</div><p className="quiet">{selected.length+(modal==='select'?order.slots.filter(x=>x.doneAt).length:0)} cephe seçili</p><div className="row-actions"><button className="primary" disabled={busy||!online} onClick={()=>action({kind:modal==='select'?'select':'setup',ids:selected})}>{modal==='lanes'?'Seçimi kaydet':'Emri güncelle'}</button><button onClick={()=>setSelected([])}>Seçimi temizle</button></div></>}
 </DialogContent></Dialog></div>;
}
function formatTime(value:string){return new Date(value).toLocaleString('tr-TR',{timeZone:'Europe/Istanbul',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'});}
function FrontRow({f,open}:{f:Front;open:()=>void}){return <button className="front-row" onClick={open}><span className={`type-dot ${f.type}`}/><span className="front-row-body"><strong>{f.title}</strong><span>{f.type==='lane'&&f.where?f.where:nextMove(f)?.text??'Sıradaki hamle yok.'}</span><small>{f.status==='held'?'Bekletiliyor · ':''}{formatTime(f.touched)}</small></span><ChevronRight size={18}/></button>;}



