'use client';
import {useCallback,useEffect,useMemo,useRef,useState,type CSSProperties,type PointerEvent as ReactPointerEvent} from 'react';
import {ArrowUpRight,Check,Flag,Maximize,Minus,Plus,X} from 'lucide-react';
import {nextMove,type State,type Order} from '@/lib/domain';
import {addDays,calendarDay,daysBetween,type CalendarEvent} from '@/lib/calendar';
import {allocateCamps,curve,dayLabel,fitView,loadTerrain,overlaps,placeLabels,rippleContourPaths,REGION_NAMES,terrainRoute,urgency,WORLD,type Box,type Point,type Positions,type Terrain,type View} from '@/lib/terrain';
import './expedition-map.css';

export type ExpeditionMapProps={state:State;order:Order;mode?:'hq'|'atlas';selectedId?:string|null;onSelect?:(id:string|null)=>void;onOpen?:(id:string)=>void;onReorder?:(ids:string[],snapshot:string)=>Promise<boolean|undefined>;disabled?:boolean;criticalDays?:number;approachingDays?:number};
type Drag={id:string;x:number;y:number;target:string|null};
const pad=(n:number)=>String(n).padStart(2,'0');
const clockTime=(value:string)=>new Date(value).toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit',timeZone:'Europe/Istanbul'});
const allocationKey='berthier-terrain-positions-v2';
let memoryPositions:Positions={};
function readPositions(){try{const raw=JSON.parse(localStorage.getItem(allocationKey)??'{}');if(raw&&typeof raw==='object'&&!Array.isArray(raw))memoryPositions={...raw,...memoryPositions};}catch{}return memoryPositions;}
function frontEvent(events:CalendarEvent[],frontId:string,today:string){return events.filter(e=>e.frontId===frontId&&e.date&&!e.cancelled).map(e=>{if(!e.weekly||e.date!>=today)return e;const diff=daysBetween(e.date!,today);return {...e,date:addDays(e.date!,Math.ceil(diff/7)*7)};}).sort((a,b)=>{const da=daysBetween(today,a.date!),db=daysBetween(today,b.date!);return Number(da<0)-Number(db<0)||(da<0?db-da:da-db);})[0];}

export default function ExpeditionMap({state,order,mode='hq',selectedId,onSelect,onOpen,onReorder,disabled=false,criticalDays=2,approachingDays=7}:ExpeditionMapProps){
 const contourRoot=useRef<SVGGElement>(null);
 const root=useRef<HTMLDivElement>(null),[size,setSize]=useState({w:390,h:mode==='hq'?360:640}),[positions,setPositions]=useState<Positions>({}),[terrain,setTerrain]=useState<Terrain|null>(null),[terrainError,setTerrainError]=useState(false),[view,setView]=useState<View>({x:0,y:0,k:.35}),[paths,setPaths]=useState<Record<string,Point[]>>({}),[ownSelected,setOwnSelected]=useState<string|null>(null),[pending,setPending]=useState<{ids:string[];snapshot:string}|null>(null),[saving,setSaving]=useState(false),[legend,setLegend]=useState(false),[drag,setDrag]=useState<Drag|null>(null),[fx,setFx]=useState<{id:string;all:boolean;key:number}|null>(null),[notice,setNotice]=useState(''),[animate,setAnimate]=useState(false);
 const selection=selectedId===undefined?ownSelected:selectedId;
 const select=useCallback((id:string|null)=>{setOwnSelected(id);onSelect?.(id);},[onSelect]);
 const today=calendarDay(),snapshot=JSON.stringify(order),frontSignature=Object.values(state.fronts).map(f=>f.id+':'+f.type).sort().join('|');
 useEffect(()=>{const next=allocateCamps(Object.values(state.fronts),readPositions());memoryPositions=next;setPositions(next);try{localStorage.setItem(allocationKey,JSON.stringify(next));}catch{}},[frontSignature]); // Stored ids/coordinates contain no front text.
 useEffect(()=>{let live=true;loadTerrain().then(value=>{if(live)setTerrain(value);}).catch(()=>{if(live)setTerrainError(true);});return ()=>{live=false;};},[]);
 useEffect(()=>{if(!root.current)return;const obs=new ResizeObserver(entries=>{const r=entries[0].contentRect;setSize({w:r.width,h:r.height});});obs.observe(root.current);return ()=>obs.disconnect();},[]);
 const slots=useMemo(()=>{const all=order.slots.map(s=>({...s,doneAt:(s as typeof s&{doneAt?:string}).doneAt??state.fronts[s.frontId]?.moves.find(m=>m.id===s.moveId)?.doneAt}));return pending?pending.ids.flatMap(id=>all.filter(s=>s.frontId===id)):all;},[order,state.fronts,pending]);
 const ids=slots.map(s=>s.frontId),routeSignature=ids.join('|'),slotMap=new Map(slots.map((s,i)=>[s.frontId,{...s,rank:i+1}])),nextId=slots.find(s=>!s.doneAt)?.frontId,selected=selection?state.fronts[selection]:undefined;
 const fronts=Object.values(state.fronts).filter(f=>mode==='atlas'?f.status!=='closed'||slotMap.has(f.id):slotMap.has(f.id));
 const fit=useCallback(()=>{const route=order.slots.map(s=>positions[s.frontId]?.point).filter((p):p is Point=>!!p),all=Object.values(state.fronts).filter(f=>f.status!=='closed').map(f=>positions[f.id]?.point).filter((p):p is Point=>!!p);setAnimate(true);setView(fitView(mode==='atlas'?all:route,size.w,size.h,mode==='atlas'?110:36,mode==='atlas'?80:48));},[order.date,order.slots.map(s=>s.frontId).join('|'),positions,size.w,size.h,mode]);
 const fitted=useRef('');
 useEffect(()=>{if(!Object.keys(positions).length&&fronts.length)return;const key=mode+':'+order.date+':'+size.w+':'+size.h;if(fitted.current===key)return;fitted.current=key;fit();},[positions,size,mode,order.date,fit,fronts.length]);
 useEffect(()=>{if(!animate)return;const timer=setTimeout(()=>setAnimate(false),320);return ()=>clearTimeout(timer);},[animate]);
 useEffect(()=>{if(!terrain)return;let live=true;const legs=ids.map((id,i)=>({id,from:i?positions[ids[i-1]]?.point:WORLD.HQ,to:positions[id]?.point}));(async()=>{const result:Record<string,Point[]>={};for(const leg of legs){if(!live)return;if(leg.from&&leg.to)result[leg.id]=terrainRoute(terrain,leg.from,leg.to);await new Promise<void>(resolve=>setTimeout(resolve,0));}if(live)setPaths(result);})();return ()=>{live=false;};},[terrain,routeSignature,positions]);
 const previousDone=useRef<Set<string>|null>(null);
 useEffect(()=>{const done=new Set(slots.filter(s=>s.doneAt).map(s=>s.frontId));if(previousDone.current){const id=[...done].find(x=>!previousDone.current!.has(x));if(id){const all=slots.length>0&&done.size===slots.length;setNotice(all?'Sefer tamamlandı.':'Hamle tamamlandı. Kampa bayrak dikildi.');if(!window.matchMedia('(prefers-reduced-motion: reduce)').matches)setFx({id,all,key:Date.now()});}}previousDone.current=done;},[slots]);
 useEffect(()=>{if(!fx)return;const timer=setTimeout(()=>setFx(null),fx.all?2550:1200);return ()=>clearTimeout(timer);},[fx]);
 useEffect(()=>{if(!fx||!terrain||!positions[fx.id]||!contourRoot.current)return;const started=performance.now(),nodes=[...contourRoot.current.querySelectorAll('path')];let frame=0,last=0;const draw=(now:number)=>{if(now-last>=32){const paths=rippleContourPaths(terrain,positions[fx.id].point,now-started,fx.all);nodes.forEach((node,i)=>node.setAttribute('d',paths[i]));last=now;}frame=requestAnimationFrame(draw);};frame=requestAnimationFrame(draw);return()=>{cancelAnimationFrame(frame);nodes.forEach((node,i)=>node.setAttribute('d',terrain.contours[i].d));};},[fx,terrain,positions]);
 const viewRef=useRef(view);viewRef.current=view;
 const zoom=useCallback((factor:number,center?:Point)=>{const current=viewRef.current,p=center??[size.w/2,size.h/2],min=Math.min(.12,fitView(Object.values(positions).map(x=>x.point),size.w,size.h).k),k=Math.min(2.8,Math.max(min,current.k*factor));setAnimate(true);setView({k,x:p[0]-(p[0]-current.x)*k/current.k,y:p[1]-(p[1]-current.y)*k/current.k});},[positions,size]);
 const camps=fronts.flatMap(f=>{const p=positions[f.id]?.point;if(!p)return [];const slot=slotMap.get(f.id),event=frontEvent(Object.values(state.events??{}),f.id,today),days=event?.date?daysBetween(today,event.date):null,done=!!slot?.doneAt;return [{front:f,point:p,x:p[0]*view.k+view.x,y:p[1]*view.k+view.y,slot,event,days,done,urgency:urgency(days,f.status==='held',done,criticalDays,approachingDays),label:done?'GEÇİLDİ · '+clockTime(slot!.doneAt!):dayLabel(days,f.status==='held')}];});
 const hq:Point=[WORLD.HQ[0]*view.k+view.x,WORLD.HQ[1]*view.k+view.y],extra:Box[]=[[size.w-57,8,size.w-7,146],...(mode==='atlas'?[[0,0,size.w,100] as Box]:[])];
 const labelPlacement=placeLabels([{id:'__hq',x:hq[0],y:hq[1],r:23,width:0,height:0,priority:100},...camps.map(c=>({id:c.front.id,x:c.x,y:c.y,r:c.slot?22:12,width:Math.min(176,Math.max(c.done?115:80,c.front.title.length*6.8+16)),height:c.slot?42:25,priority:c.done?90:c.front.id===selection?80:c.front.id===nextId?70:c.slot?50:10,force:c.done}))],size.w,size.h,extra);
 const regions=useMemo(()=>{const config:[string,Point[],number][]=[['Kulvar Dağları',[[330,150],[560,330],[300,20],[470,400],[110,420],[620,240]],-4],['Ders Ovası',[[300,830],[420,1040],[470,880],[430,1190],[650,1010],[150,990]],0],['Başvuru Geçidi',[[683,510],[765,318],[585,455],[812,560],[640,250]],-62],['Genel Düzlük',[[400,560],[400,720],[270,680],[380,810]],0]];const boxes=[...labelPlacement.occupied];return config.flatMap(([text,candidates,angle])=>{for(const p of candidates){const x=p[0]*view.k+view.x,y=p[1]*view.k+view.y,w=text.length*5.5,rad=Math.abs(angle*Math.PI/180),bw=Math.abs(w*Math.cos(rad))+20,bh=Math.abs(w*Math.sin(rad))+20,b:Box=[x-bw/2,y-bh/2,x+bw/2,y+bh/2];if(b[0]<8||b[2]>size.w-8||b[1]<(mode==='atlas'?110:8)||b[3]>size.h-14||boxes.some(q=>overlaps(b,q)))continue;const touchesPath=Object.values(paths).some(points=>points.some(q=>{const px=q[0]*view.k+view.x,py=q[1]*view.k+view.y;return px>b[0]&&px<b[2]&&py>b[1]&&py<b[3];}));if(touchesPath)continue;boxes.push(b);return [{text,x,y,angle}];}return [];});},[view,size,paths,mode,JSON.stringify(labelPlacement.occupied)]);
 const interaction=useRef<{start:Point;last:Point;id:string|null;timer:ReturnType<typeof setTimeout>|null;dragging:boolean;pan:boolean;initial:View;pinch?:{distance:number;mid:Point;view:View};moved:boolean}|null>(null),suppressClick=useRef(false),dragRef=useRef<Drag|null>(null),latest=useRef({camps,slots,snapshot,pending,disabled,onReorder});latest.current={camps,slots,snapshot,pending,disabled,onReorder};
 const updateDrag=useCallback((id:string,p:Point)=>{const target=latest.current.camps.filter(c=>c.slot&&!c.done&&c.front.id!==id).find(c=>Math.hypot(c.x-p[0],c.y-p[1])<36)?.front.id??null;const value={id,x:p[0],y:p[1],target};dragRef.current=value;setDrag(value);},[]);
 const finishDrag=useCallback(()=>{const d=dragRef.current;if(d?.target){const {slots:current,snapshot:currentSnapshot,pending:currentPending}=latest.current,movable=current.filter(s=>!s.doneAt).map(s=>s.frontId),from=movable.indexOf(d.id),to=movable.indexOf(d.target);if(from>=0&&to>=0){movable.splice(to,0,...movable.splice(from,1));let cursor=0;const reordered=current.map(s=>s.doneAt?s.frontId:movable[cursor++]);setPending({ids:reordered,snapshot:currentPending?.snapshot??currentSnapshot});setNotice('Yeni sıra hazır. Kaydettiğinde günün emrine uygulanır.');}}dragRef.current=null;setDrag(null);},[]);
 const point=useCallback((clientX:number,clientY:number):Point=>{const rect=root.current!.getBoundingClientRect();return [clientX-rect.left,clientY-rect.top];},[]);
 const cancelInteraction=useCallback(()=>{if(interaction.current?.timer)clearTimeout(interaction.current.timer);interaction.current=null;dragRef.current=null;setDrag(null);},[]);
 const pointerDown=(e:ReactPointerEvent<HTMLDivElement>)=>{if(e.pointerType!=='mouse'||e.button!==0)return;const el=e.target as HTMLElement,camp=el.closest<HTMLElement>('[data-camp]'),id=camp?.dataset.camp??null;if(el.closest('[data-map-control]'))return;const p=point(e.clientX,e.clientY),canDrag=!!id&&!!onReorder&&!disabled&&!!slotMap.get(id)&&!slotMap.get(id)?.doneAt;interaction.current={start:p,last:p,id,timer:null,dragging:canDrag,pan:!id,initial:viewRef.current,moved:false};root.current?.setPointerCapture(e.pointerId);};
 const pointerMove=(e:ReactPointerEvent<HTMLDivElement>)=>{if(e.pointerType!=='mouse')return;const i=interaction.current;if(!i)return;const p=point(e.clientX,e.clientY);i.last=p;if(Math.hypot(p[0]-i.start[0],p[1]-i.start[1])>5)i.moved=true;if(!i.moved)return;suppressClick.current=true;setAnimate(false);if(i.dragging&&i.id)updateDrag(i.id,p);else if(i.pan)setView({...i.initial,x:i.initial.x+p[0]-i.start[0],y:i.initial.y+p[1]-i.start[1]});};
 const pointerUp=(e:ReactPointerEvent<HTMLDivElement>)=>{if(e.pointerType!=='mouse')return;const i=interaction.current;if(i?.dragging&&i.moved)finishDrag();if(i&&!i.moved){select(i.id);suppressClick.current=true;}interaction.current=null;setTimeout(()=>{suppressClick.current=false;},0);};
 useEffect(()=>{const el=root.current;if(!el)return;const wheel=(e:WheelEvent)=>{if(!e.ctrlKey)return;e.preventDefault();zoom(Math.exp(-e.deltaY*.007),point(e.clientX,e.clientY));};const start=(e:TouchEvent)=>{if((e.target as HTMLElement).closest('[data-map-control]'))return;if(e.touches.length>=2){if(interaction.current?.timer)clearTimeout(interaction.current.timer);const a=point(e.touches[0].clientX,e.touches[0].clientY),b=point(e.touches[1].clientX,e.touches[1].clientY),mid:Point=[(a[0]+b[0])/2,(a[1]+b[1])/2];interaction.current={start:mid,last:mid,id:null,timer:null,dragging:false,pan:false,initial:viewRef.current,moved:true,pinch:{distance:Math.hypot(a[0]-b[0],a[1]-b[1]),mid,view:viewRef.current}};e.preventDefault();suppressClick.current=true;return;}const touch=e.touches[0],p=point(touch.clientX,touch.clientY),id=(e.target as HTMLElement).closest<HTMLElement>('[data-camp]')?.dataset.camp??null;const i={start:p,last:p,id,timer:null as ReturnType<typeof setTimeout>|null,dragging:false,pan:false,initial:viewRef.current,moved:false};interaction.current=i;if(id&&latest.current.onReorder&&!latest.current.disabled&&latest.current.slots.some(s=>s.frontId===id&&!s.doneAt))i.timer=setTimeout(()=>{if(interaction.current!==i)return;i.dragging=true;suppressClick.current=true;updateDrag(id,i.last);navigator.vibrate?.(20);},350);};const move=(e:TouchEvent)=>{const i=interaction.current;if(!i)return;if(e.touches.length>=2&&i.pinch){e.preventDefault();const a=point(e.touches[0].clientX,e.touches[0].clientY),b=point(e.touches[1].clientX,e.touches[1].clientY),mid:Point=[(a[0]+b[0])/2,(a[1]+b[1])/2],k=Math.max(.04,Math.min(2.8,i.pinch.view.k*Math.hypot(a[0]-b[0],a[1]-b[1])/i.pinch.distance)),v=i.pinch.view;setAnimate(false);setView({k,x:mid[0]-(i.pinch.mid[0]-v.x)*k/v.k,y:mid[1]-(i.pinch.mid[1]-v.y)*k/v.k});return;}if(e.touches.length!==1)return;const p=point(e.touches[0].clientX,e.touches[0].clientY);i.last=p;if(i.dragging&&i.id){e.preventDefault();updateDrag(i.id,p);return;}if(Math.hypot(p[0]-i.start[0],p[1]-i.start[1])>8){i.moved=true;if(i.timer)clearTimeout(i.timer);suppressClick.current=true;}};const end=()=>{const i=interaction.current;if(i?.timer)clearTimeout(i.timer);if(i?.dragging)finishDrag();interaction.current=null;setTimeout(()=>{suppressClick.current=false;},350);};el.addEventListener('wheel',wheel,{passive:false});el.addEventListener('touchstart',start,{passive:false});el.addEventListener('touchmove',move,{passive:false});el.addEventListener('touchend',end);el.addEventListener('touchcancel',cancelInteraction);return ()=>{el.removeEventListener('wheel',wheel);el.removeEventListener('touchstart',start);el.removeEventListener('touchmove',move);el.removeEventListener('touchend',end);el.removeEventListener('touchcancel',cancelInteraction);cancelInteraction();};},[zoom,point,updateDrag,finishDrag,cancelInteraction]);
 const stale=!!pending&&pending.snapshot!==snapshot,selectedCamp=camps.find(c=>c.front.id===selection),allDone=slots.length>0&&slots.every(s=>s.doneAt);
 async function save(){if(!pending||stale||!onReorder)return;setSaving(true);try{if(await onReorder(pending.ids,pending.snapshot)){setPending(null);setNotice('Sıra kaydedildi. Kayıt defterinden geri alabilirsin.');}}finally{setSaving(false);}}
 return <div ref={root} className={`expedition-map expedition-map--${mode} ${animate?'is-animating':''} ${drag?'is-dragging':''}`} onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={cancelInteraction} onClick={e=>{if(e.target===e.currentTarget&&!suppressClick.current)select(null);}} aria-label={mode==='hq'?'Bugünün sefer rotası':'Bütün cephelerin sefer haritası'}>
  <svg className="expedition-land" width="100%" height="100%" aria-hidden="true" onClick={()=>{if(!suppressClick.current)select(null);}}>
   <g className="expedition-world" transform={`translate(${view.x} ${view.y}) scale(${view.k})`}>
    {terrain?.raster&&<image href={terrain.raster} x={WORLD.X0} y={WORLD.Y0} width={WORLD.X1-WORLD.X0} height={WORLD.Y1-WORLD.Y0} preserveAspectRatio="none"/>}
    <g ref={contourRoot} className="expedition-contours">{terrain?.contours.map((line,i)=><path key={i} d={line.d} className={line.major?'is-major':''}/>)}</g>
    {terrain&&<path className="expedition-river" d={terrain.river}/>}
    {slots.map((slot,i)=>{const p=paths[slot.frontId];if(!p)return null;const d=curve(p),sealed=!!slot.doneAt&&(i===0||!!slots[i-1].doneAt),isNext=slot.frontId===nextId;return <g key={slot.frontId} className={`expedition-leg ${sealed?'is-sealed':''} ${isNext?'is-next':''}`}><path d={d} className="route-casing" vectorEffect="non-scaling-stroke"/>{sealed?<><path d={d} className="seal-outer" vectorEffect="non-scaling-stroke"/><path d={d} className="seal-middle" vectorEffect="non-scaling-stroke"/><path d={d} className="seal-inner" vectorEffect="non-scaling-stroke"/><path d={d} className={`seal-core ${fx?.id===slot.frontId?'is-new':''}`} pathLength={1} vectorEffect="non-scaling-stroke"/></>:<path d={d} className="route-line" vectorEffect="non-scaling-stroke"/>}</g>;})}
   </g>
   {regions.map(r=><text key={r.text} className="expedition-region" transform={`translate(${r.x} ${r.y}) rotate(${r.angle})`} textAnchor="middle">{r.text}</text>)}
  </svg>
  <div className="expedition-vignette" aria-hidden="true"/>
  {fx&&positions[fx.id]&&<div key={fx.key} className="expedition-ripple" style={{left:positions[fx.id].point[0]*view.k+view.x,top:positions[fx.id].point[1]*view.k+view.y}} aria-hidden="true">{fx.all&&<i/>}</div>}
  <div className="expedition-hq" style={{left:hq[0],top:hq[1]}} aria-label="Karargâh"><span>✳</span><small>KARARGÂH</small></div>
  {camps.map(c=>{const label=labelPlacement.labels[c.front.id],isSelected=c.front.id===selection;return <div key={c.front.id} className={`expedition-camp ${c.slot?'is-route':'is-other'} is-${c.urgency} ${c.front.status==='held'?'is-held':''} ${isSelected?'is-selected':''} ${c.front.id===nextId?'is-next':''} ${drag?.target===c.front.id?'is-target':''} ${fx?.id===c.front.id?'is-completing':''}`}>
   <button type="button" data-camp={c.front.id} className="expedition-camp-hit" style={{left:c.x,top:c.y}} aria-label={`${c.front.title}${c.slot?', rotada '+pad(c.slot.rank):''}, ${c.label}`} aria-pressed={isSelected} title={c.front.title+' · '+c.label} onClick={()=>{if(!suppressClick.current)select(c.front.id);}}><span className="expedition-palisade"/><span className="expedition-pin">{c.done?<Flag size={18} fill="currentColor"/>:c.slot?pad(c.slot.rank):c.front.status!=='held'?<i/>:null}</span>{c.urgency==='critical'&&<><span className="expedition-sonar"/><span className="expedition-sonar second"/></>}</button>
   {label&&<button type="button" data-camp={c.front.id} tabIndex={-1} className="expedition-camp-label" style={{left:label[0],top:label[1],maxWidth:176}} onClick={()=>{if(!suppressClick.current)select(c.front.id);}}><span>{c.front.title}</span>{c.slot&&<small>{c.label}</small>}</button>}
  </div>;})}
  {!terrain&&<div className="expedition-loading" role="status">{terrainError?'Arazi çizimi açılamadı. Kampları seçebilirsin.':'Arazi hazırlanıyor…'}</div>}
  <div className="expedition-controls" data-map-control><button type="button" onClick={()=>zoom(1.3)} aria-label="Haritayı yakınlaştır"><Plus size={19}/></button><button type="button" onClick={()=>zoom(1/1.3)} aria-label="Haritayı uzaklaştır"><Minus size={19}/></button><button type="button" onClick={fit} aria-label={mode==='atlas'?'Bütün cepheleri sığdır':'Bütün rotayı ve karargâhı sığdır'}><Maximize size={18}/></button></div>
  {mode==='atlas'&&<div className="expedition-legend-control" data-map-control><button type="button" onClick={()=>setLegend(!legend)} aria-expanded={legend}>NASIL OKUNUR?</button>{legend&&<div className="expedition-legend"><strong>Bölgeler cephe tipini gösterir.</strong><span>Kulvar Dağları · Ders Ovası</span><span>Başvuru Geçidi · Genel Düzlük</span><span>Kontur: yükselti · Patika: günün sırası</span><span><Flag size={13}/> Bayrak: geçilen kamp</span><span className="legend-seal">━ Mühür: tamamlanan rota</span><span className="legend-coral">Mercan = acil</span><small>İki parmakla yakınlaştır. Sırayı değiştirmek için kampı basılı tut.</small></div>}</div>}
  {drag&&<div className="expedition-drag-ghost" style={{left:drag.x,top:drag.y}} aria-hidden="true">{pad(slotMap.get(drag.id)?.rank??1)}</div>}
  {drag&&<div className="expedition-drag-hint" role="status">{drag.target?`Bırakırsan ${pad(slotMap.get(drag.target)?.rank??1)}. sıraya geçer.`:'Sıradaki başka bir kampın üstüne bırak.'}</div>}
  {pending&&<div className="expedition-pending" data-map-control role="status"><span>{stale?'Günün emri değişti. Yeniden sırala.':'Yeni sıra hazır.'}</span><button type="button" disabled={saving} onClick={()=>{setPending(null);setNotice('Önerilen sıra iptal edildi.');}}>Vazgeç</button><button type="button" disabled={disabled||saving||stale} onClick={save}>{saving?'Kaydediliyor…':'Sırayı kaydet'}</button></div>}
  {mode==='atlas'&&selected&&selectedCamp&&!pending&&<article className={`expedition-front-card is-${selectedCamp.urgency}`} data-map-control><button type="button" className="expedition-card-close" onClick={()=>select(null)} aria-label="Cephe kartını kapat"><X size={18}/></button><div className={`expedition-type type-${selected.type}`}>{REGION_NAMES[selected.type]}</div><h2>{selected.title}</h2><p>{selectedCamp.event?`${selectedCamp.event.title} · ${new Date(selectedCamp.event.date!+'T12:00:00Z').toLocaleDateString('tr-TR',{day:'numeric',month:'short'})}${selectedCamp.event.time?' · '+selectedCamp.event.time:''}`:selected.where?'Kaldığın yer: '+selected.where:'Tarihsiz cephe'}</p><div className="expedition-card-meta"><span>{selectedCamp.label}</span><small>{selectedCamp.slot?'ROTADA '+pad(selectedCamp.slot.rank):'BUGÜNÜN ROTASINDA DEĞİL'}</small></div><small>{selectedCamp.done?'TAMAMLANAN HAMLE':'SIRADAKİ HAMLE'}</small><p className="expedition-card-move">{selectedCamp.slot?.text??nextMove(selected)?.text??'Açık hamle yok.'}</p><button type="button" className="expedition-open" onClick={()=>onOpen?.(selected.id)}>Cepheyi aç <ArrowUpRight size={17}/></button></article>}
  {allDone&&!selected&&!pending&&<div className="expedition-complete"><Check size={14}/> Sefer tamamlandı.</div>}
  <span className="expedition-sr" aria-live="polite">{notice}</span>
 </div>;
}
