'use client';
import {useState} from 'react';
import {CalendarDays,AlertTriangle,Check,ChevronRight} from 'lucide-react';
import {KRITIK,YAKLASAN} from '@/lib/expedition/camps';
import {WD,dayMonth,shortDay,untilTime,upper} from '@/lib/turkish';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {type State} from '@/lib/domain';
import {addDays,calendarDay,conflicts,denseDays,eventMail,kindNames,occurrences,daysBetween,type CalendarEvent,type Conflict,type Profile} from '@/lib/calendar';
type Props={state:State;busy:boolean;action:(body:{kind:string;[key:string]:unknown})=>Promise<boolean|undefined>;frontId?:string};
// Ufuk (design 1i): fourteen days at a glance, empty ones too. Coral dot = 2 days or less, coral ring = 7 days
// or less, grey = later or weekly (the map's thresholds); a conflicting day has a coral frame, today a gold one.
// Every row opens the item; the conflict card offers the mail draft. With frontId, only that front's items.
export default function Horizon({state,busy,action,frontId}:Props){
 const [editing,setEditing]=useState<CalendarEvent|null>(null),[mailId,setMailId]=useState<string|null>(null);
 const today=calendarDay(),last=addDays(today,13),all=Object.values(state.events??{}).filter(e=>!e.cancelled),events=frontId?all.filter(e=>e.frontId===frontId):all,rows=occurrences(events,today,last).filter(e=>e.kind!=='class'),clashes=conflicts(all,today).filter(c=>!frontId||c.a.frontId===frontId||c.b.frontId===frontId),dense=denseDays(all),selected=clashes.find(c=>c.id===mailId);
 const hard=clashes.filter(c=>c.severity==='hard'),clashAt=new Set(hard.flatMap(c=>[c.a.id+c.a.date,c.b.id+c.a.date])),clashDays=new Set(hard.map(c=>c.a.date));
 const tone=(e:CalendarEvent)=>{if(e.weekly)return 'calm';const d=daysBetween(today,e.date!);return d<=KRITIK?'crit':d<=YAKLASAN?'near':'calm';};
 const later=events.filter(e=>e.kind!=='class'&&!e.weekly&&e.date&&e.date>last),weekly=events.filter(e=>e.kind==='class'),past=events.filter(e=>e.date&&e.date<today&&!e.weekly),undated=events.filter(e=>!e.date);
 function row(e:CalendarEvent){const moves=Object.values(state.fronts).flatMap(f=>f.moves).filter(m=>m.eventId===e.id&&!m.removedAt),done=moves.filter(m=>m.doneAt).length,f=e.frontId?state.fronts[e.frontId]:undefined;const meta=[kindNames[e.kind],f?.title,e.location,e.weekly&&e.date?'Her '+WD[new Date(e.date+'T12:00:00Z').getUTCDay()]:'',e.endTime?untilTime(e.endTime)+' kadar':''].filter(Boolean).join(' · ');
  return <button className="hz-row" key={e.id+e.date} onClick={()=>setEditing({...e})}><span className={clashAt.has(e.id+e.date)?'hz-time is-clash':'hz-time'}>{e.time??'GÜN İÇİ'}</span><span className="hz-main"><span className="hz-title">{e.title}</span><span className="hz-meta">{meta}</span>{e.bring.length>0&&<span className="hz-bring">Yanına al: {e.bring.join(', ')}</span>}{moves.length>0&&<span className="hz-prep"><span className="hz-bar" aria-hidden="true">{moves.map((m,i)=><span key={m.id} className={i<done?'is-done':undefined}/>)}</span>HAZIRLIK {done}/{moves.length}</span>}</span><ChevronRight size={18}/></button>;}
 const more=(label:string,list:CalendarEvent[])=>list.length>0&&<details className="hz-more"><summary><span>{label}</span><span>{list.length}</span></summary>{list.map(row)}</details>;
 return <div className="horizon">{!frontId&&<><p className="page-top">14 GÜN · {upper(dayMonth(today))} – {upper(dayMonth(last))} · İSTANBUL SAATİ</p><h1 className="page-title">Ufuk</h1>
 <div className="hz-grid">{Array.from({length:14},(_,i)=>addDays(today,i)).map(d=>{const items=rows.filter(e=>e.date===d);return <button key={d} className={['hz-cell',d===today?'is-today':'',clashDays.has(d)?'is-clash':''].join(' ').trim()} aria-label={`${shortDay(d)}: ${items.length?items.length+' kalem':'boş'}`} onClick={()=>items.length>0&&document.getElementById('hz-'+d)?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'})}><span>{upper(WD[new Date(d+'T12:00:00Z').getUTCDay()])}</span><strong>{Number(d.slice(8))}</strong><span className="hz-dots">{items.slice(0,3).map(e=><span key={e.id} className={`hz-dot is-${tone(e)}`}/>)}</span></button>;})}</div>
 <p className="hz-legend"><span><span className="hz-dot is-crit"/>2 GÜN VE ALTI</span><span><span className="hz-dot is-near"/>7 GÜN VE ALTI</span><span><span className="hz-key"/>ÇAKIŞMA</span></p></>}
 {clashes.map(c=>{const seen=!!state.seenConflicts?.includes(c.id);return <section key={c.id} className={`hz-clash is-${c.severity}${seen?' is-seen':''}`}><p className="hz-clash-top"><AlertTriangle size={16}/><span>{c.severity==='hard'?'SAAT ÇAKIŞMASI':'ZAMAN NOTU'} · {upper(shortDay(c.a.date!))}{c.a.time?' '+c.a.time:''}</span>{seen&&<span className="hz-seen">GÖRÜLDÜ</span>}</p><p>{c.severity==='hard'?`${c.a.title} ve ${c.b.title} aynı saatte. Öneri: ${c.move.title} için başka saat iste.${c.move.kind==='presentation'?' Sunum saatinin taşınması sınava göre daha olası.':''}`:`${c.a.title} ve ${c.b.title}: ${c.reason}`}</p><div className="hz-clash-actions">{c.severity==='hard'&&<button onClick={()=>{setMailId(c.id);if(!seen)void action({kind:'seenConflict',conflictId:c.id});}}>Mail taslağı</button>}<button disabled={busy} onClick={()=>action(seen?{kind:'seenConflict',conflictId:c.id,seen:false}:{kind:'seenConflict',conflictId:c.id})}>{seen?'Geri al':'Gördüm'}</button></div></section>;})}
 {!rows.length&&!frontId&&<section className="blank"><CalendarDays size={32}/><h2>Önümüzdeki 14 günde kalem yok.</h2><p>“Yarın 14:00’te dekanlıkta imza var” diye başlayabilirsin.</p></section>}
 {!rows.length&&frontId&&<p className="quiet">Önümüzdeki 14 günde bu cepheye ait tarihli kalem yok.</p>}
 {[...new Set(rows.map(e=>e.date!))].map(date=>{const list=rows.filter(e=>e.date===date);return <section className="hz-day" id={'hz-'+date} key={date}><h2><span>{date===today?'BUGÜN · ':date===addDays(today,1)?'YARIN · ':''}{upper(shortDay(date))}</span><span className={dense.has(date)?'is-dense':undefined}>{dense.has(date)?'YOĞUN GÜN':list.length}</span></h2>{list.map(row)}</section>;})}
 {undated.length>0&&<section className="hz-day"><h2><span>TARİHİ NETLEŞECEK</span><span>{undated.length}</span></h2>{undated.map(row)}</section>}
 <div className="hz-mores">{more('Haftalık ders saatleri',weekly)}{more('14 günden sonra',later)}{more('Geçen tarihler',past)}</div>
 <EventDialog state={state} busy={busy} action={action} editing={editing} setEditing={setEditing}/>
 <ConflictMailDialog state={state} busy={busy} action={action} conflict={selected} close={()=>setMailId(null)}/>
 </div>;
}
// Shared with the morning report: the item details/date dialog and the conflict mail draft.
export function EventDialog({state,busy,action,editing,setEditing}:{state:State;busy:boolean;action:Props['action'];editing:CalendarEvent|null;setEditing:(e:CalendarEvent|null)=>void}){const today=calendarDay();return <Dialog open={!!editing} onOpenChange={open=>!open&&setEditing(null)}><DialogContent className="berthier-dialog"><DialogTitle>{editing?.title}</DialogTitle><DialogDescription>Tarihi değiştirince hazırlık yeniden hesaplanır; biten hamleler korunur.</DialogDescription>{editing&&<form className="event-form" onSubmit={async e=>{e.preventDefault();if(await action({kind:'event',event:editing}))setEditing(null);}}><div className="field-grid"><label>Tarih<input type="date" value={editing.date??''} onChange={e=>setEditing({...editing,date:e.target.value||null})}/></label><label>Saat<input type="time" value={editing.time??''} onChange={e=>setEditing({...editing,time:e.target.value||null})}/></label><label>Bitiş saati<input type="time" value={editing.endTime??''} onChange={e=>setEditing({...editing,endTime:e.target.value||null})}/></label><label>Hazırlığa kaç gün önce?<input type="number" min="0" max="365" placeholder="Varsayılan" value={editing.prepDays??''} onChange={e=>setEditing({...editing,prepDays:e.target.value===''?null:Number(e.target.value)})}/></label></div><label>Yer<input value={editing.location} maxLength={200} onChange={e=>setEditing({...editing,location:e.target.value})}/></label><label>Yanına alınacaklar (virgülle ayır)<input defaultValue={editing.bring.join(', ')} onBlur={e=>setEditing({...editing,bring:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)})}/></label>
 {editing.kind==='application'&&<><p>{[editing.institution,editing.program].filter(Boolean).join(' · ')||'Kurum ve program bilgilerini dikteyle ekleyebilirsin.'}</p>{/^https?:\/\//i.test(editing.portal)&&<a className="portal-link" href={editing.portal} target="_blank" rel="noopener noreferrer">Başvuru portalını aç ↗</a>}<h3>Gerekli belgeler</h3>{!editing.documents.length&&<p className="quiet">Henüz bilinmiyor. İlk hamle, başvuru sayfasındaki belgeleri listelemek.</p>}{editing.documents.map((d,i)=><div className="document-row" key={i}><div><strong>{d.name}</strong><p className="quiet">{d.holder||'Sende'}</p></div><Select value={d.status} onValueChange={value=>setEditing({...editing,documents:editing.documents.map((x,j)=>j===i?{...x,status:value as typeof d.status}:x)})}><SelectTrigger aria-label={`${d.name} durumu`}><SelectValue/></SelectTrigger><SelectContent>{Object.entries({todo:'Yapılacak',requested:'İstendi',ready:'Hazır',uploaded:'Yüklendi'}).map(([value,label])=><SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></div>)}</>}
 <h3>Hazırlık planı</h3>{Object.values(state.fronts).flatMap(f=>f.moves).filter(m=>m.eventId===editing.id&&!m.removedAt).map(m=><p className="plan-row" key={m.id}>{m.doneAt?<Check size={16}/>:<span className="plan-date">{m.prepareAt&&formatDate(m.prepareAt)}</span>}<span>{m.text}</span></p>)}{editing.date&&daysBetween(today,editing.date)<(editing.prepDays??(editing.kind==='application'?28:editing.kind==='exam'?10:7))&&<p className="notice">Süre dar: plan kalan günlere sıkıştırıldı; başkasına bağlı işler önce.</p>}<div className="row-actions"><button type="submit" className="primary" disabled={busy}>Değişiklikleri kaydet</button><button type="button" disabled={busy} onClick={async()=>{if(await action({kind:'cancelEvent',eventId:editing.id}))setEditing(null);}}>Kalemi kaldır</button></div><p className="quiet">Değişiklikleri kayıt defterinden geri alabilirsin.</p></form>}</DialogContent></Dialog>;}
export function ConflictMailDialog({state,busy,action,conflict,close}:{state:State;busy:boolean;action:Props['action'];conflict:Conflict|undefined;close:()=>void}){const [profile,setProfile]=useState<Profile>(state.profile??{name:'',number:'',department:'',university:''});return <Dialog open={!!conflict} onOpenChange={open=>!open&&close()}><DialogContent className="berthier-dialog"><DialogTitle>Çakışma için mail taslağı</DialogTitle><DialogDescription>Metni düzenleyip kendi mail uygulamandan gönderebilirsin.</DialogDescription>{!state.profile?<form className="event-form" onSubmit={e=>{e.preventDefault();void action({kind:'profile',profile});}}><p>İmzan için bu bilgileri bir kez kaydedelim. İstersen boş bırakabilirsin.</p>{Object.entries({name:'Ad soyad',number:'Öğrenci numarası',department:'Bölüm',university:'Üniversite'}).map(([key,label])=><label key={key}>{label}<input maxLength={key==='number'?50:100} value={profile[key as keyof Profile]} onChange={e=>setProfile({...profile,[key]:e.target.value})}/></label>)}<button className="primary" disabled={busy}>Kaydet ve taslağı göster</button></form>:conflict&&<><textarea aria-label="Mail taslağı" className="mail-draft" defaultValue={eventMail(conflict,state.profile)}/><p className="quiet">Taslağı seçip kopyala. Berthier mail göndermez.</p></>}</DialogContent></Dialog>;}
function formatDate(date:string){return new Date(date+'T12:00:00Z').toLocaleDateString('tr-TR',{day:'numeric',month:'short',weekday:'short'});}
