'use client';
import {useState} from 'react';
import {CalendarDays,MapPin,AlertTriangle,Check,ArrowRight} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {type State} from '@/lib/domain';
import {addDays,calendarDay,conflicts,denseDays,eventMail,kindNames,occurrences,daysBetween,type CalendarEvent,type Profile} from '@/lib/calendar';
type Props={state:State;busy:boolean;action:(body:{kind:string;[key:string]:unknown})=>Promise<boolean|undefined>;dictate:(prefill:string)=>void;frontId?:string};
export function HorizonSummary({state,open}:{state:State;open:()=>void}){const today=calendarDay(),events=Object.values(state.events??{}),upcoming=occurrences(events,today,addDays(today,13)).filter(e=>e.kind!=='class'),unseen=conflicts(events,today).filter(c=>!state.seenConflicts?.includes(c.id));return <button className="map-link horizon-link" onClick={open}><CalendarDays/><div><h2>Ufuk <span className="quiet">14 gün</span></h2><p>{unseen.length?`${unseen.length} yeni çakışma · `:''}{upcoming.length?`${upcoming.length} tarihli kalem · ${upcoming[0].title}`:'Tarihli işlerini ve hazırlıklarını burada takip et.'}</p></div><ArrowRight/></button>;}
export default function Horizon({state,busy,action,dictate,frontId}:Props){
 const [editing,setEditing]=useState<CalendarEvent|null>(null),[mailId,setMailId]=useState<string|null>(null),[profile,setProfile]=useState<Profile>(state.profile??{name:'',number:'',department:'',university:''});
 const today=calendarDay(),all=Object.values(state.events??{}).filter(e=>!e.cancelled),events=frontId?all.filter(e=>e.frontId===frontId):all,rows=occurrences(events,today,addDays(today,13)).filter(e=>e.kind!=='class'),clashes=conflicts(all,today).filter(c=>!frontId||c.a.frontId===frontId||c.b.frontId===frontId),dense=denseDays(all),selected=clashes.find(c=>c.id===mailId);
 function card(e:CalendarEvent){const moves=Object.values(state.fronts).flatMap(f=>f.moves).filter(m=>m.eventId===e.id),done=moves.filter(m=>m.doneAt).length;return <article className="event-card" key={e.id+e.date}><div className="event-time">{e.time??'Saat belli değil'}{e.endTime&&<small>– {e.endTime}</small>}</div><div className="event-main"><p className="quiet">{kindNames[e.kind]}{e.frontId&&state.fronts[e.frontId]?` · ${state.fronts[e.frontId].title}`:''}</p><h3>{e.title}</h3>{e.location&&<p><MapPin size={15}/>{e.location}</p>}{e.bring.length>0&&<p className="bring">Yanına al: {e.bring.join(', ')}</p>}{moves.length>0&&<p className="quiet">Hazırlık: {done}/{moves.length} hamle tamamlandı</p>}<button onClick={()=>setEditing({...e})}>Ayrıntı ve tarih</button></div></article>;}
 return <div className="horizon"><p className="intro">Önündeki 14 gün, hazırlıklar ve çakışmalar. Saatler İstanbul saatidir.</p>
 {clashes.map(c=><section key={c.id} className={`conflict ${c.severity}`}><div className="conflict-heading"><AlertTriangle size={19}/><h2>{c.severity==='hard'?'Saat çakışması':'Zaman notu'}</h2>{state.seenConflicts?.includes(c.id)&&<span className="quiet">Görüldü</span>}</div><p><strong>{formatDate(c.a.date!)}</strong> · {c.a.title} ({c.a.time}) ve {c.b.title} ({c.b.time}). {c.reason}</p>{c.severity==='hard'&&<><p>Öneri: {c.move.title} için başka bir saat iste.{c.move.kind==='presentation'?' Sunum saatinin taşınması sınava göre daha olası.':''}</p><button onClick={()=>{setMailId(c.id);if(!state.seenConflicts?.includes(c.id))void action({kind:'seenConflict',conflictId:c.id});}}>Mail taslağı</button></>}{!state.seenConflicts?.includes(c.id)&&c.severity==='soft'&&<button disabled={busy} onClick={()=>action({kind:'seenConflict',conflictId:c.id})}>Gördüm</button>}</section>)}
 {!rows.length&&<section className="blank"><CalendarDays size={32}/><h2>Önümüzdeki 14 günde kalem yok.</h2><p>“Yarın 14:00’te dekanlıkta imza var” diye başlayabilirsin.</p></section>}
 {[...new Set(rows.map(e=>e.date!))].map(date=><section className="horizon-day" key={date}><h2>{date===today?'Bugün':date===addDays(today,1)?'Yarın':formatDate(date)}{dense.has(date)&&<span className="dense-label">Yoğun gün</span>}</h2>{rows.filter(e=>e.date===date).map(card)}</section>)}
 {events.filter(e=>!e.date).length>0&&<section className="horizon-day"><h2>Tarihi netleşecek</h2>{events.filter(e=>!e.date).map(card)}</section>}
 {events.some(e=>e.kind==='class'||e.date&&e.date>addDays(today,13))&&<details className="archive"><summary>Ders saatleri ve daha ilerideki tarihler</summary>{events.filter(e=>e.kind==='class'||e.date&&e.date>addDays(today,13)).map(e=><div key={e.id}><p className="quiet">{e.date&&formatDate(e.date)}{e.weekly?' · Her hafta':''}</p>{card(e)}</div>)}</details>}
 {events.some(e=>e.date&&e.date<today&&!e.weekly)&&<details className="archive"><summary>Geçen tarihler</summary>{events.filter(e=>e.date&&e.date<today&&!e.weekly).map(card)}</details>}
 <button className="context-button" onClick={()=>dictate('')}>Tarih veya hazırlık değişikliği söyle</button>
 <Dialog open={!!editing} onOpenChange={open=>!open&&setEditing(null)}><DialogContent className="berthier-dialog"><DialogTitle>{editing?.title}</DialogTitle><DialogDescription>Tarihi değiştirince hazırlık yeniden hesaplanır; biten hamleler korunur.</DialogDescription>{editing&&<form className="event-form" onSubmit={async e=>{e.preventDefault();if(await action({kind:'event',event:editing}))setEditing(null);}}><div className="field-grid"><label>Tarih<input type="date" value={editing.date??''} onChange={e=>setEditing({...editing,date:e.target.value||null})}/></label><label>Saat<input type="time" value={editing.time??''} onChange={e=>setEditing({...editing,time:e.target.value||null})}/></label><label>Bitiş saati<input type="time" value={editing.endTime??''} onChange={e=>setEditing({...editing,endTime:e.target.value||null})}/></label><label>Hazırlığa kaç gün önce?<input type="number" min="0" max="365" placeholder="Varsayılan" value={editing.prepDays??''} onChange={e=>setEditing({...editing,prepDays:e.target.value===''?null:Number(e.target.value)})}/></label></div><label>Yer<input value={editing.location} maxLength={200} onChange={e=>setEditing({...editing,location:e.target.value})}/></label><label>Yanına alınacaklar (virgülle ayır)<input defaultValue={editing.bring.join(', ')} onBlur={e=>setEditing({...editing,bring:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)})}/></label>
 {editing.kind==='application'&&<><p>{[editing.institution,editing.program].filter(Boolean).join(' · ')||'Kurum ve program bilgilerini dikteyle ekleyebilirsin.'}</p>{/^https?:\/\//i.test(editing.portal)&&<a className="portal-link" href={editing.portal} target="_blank" rel="noopener noreferrer">Başvuru portalını aç ↗</a>}<h3>Gerekli belgeler</h3>{!editing.documents.length&&<p className="quiet">Henüz bilinmiyor. İlk hamle, başvuru sayfasındaki belgeleri listelemek.</p>}{editing.documents.map((d,i)=><div className="document-row" key={i}><div><strong>{d.name}</strong><p className="quiet">{d.holder||'Sende'}</p></div><Select value={d.status} onValueChange={value=>setEditing({...editing,documents:editing.documents.map((x,j)=>j===i?{...x,status:value as typeof d.status}:x)})}><SelectTrigger aria-label={`${d.name} durumu`}><SelectValue/></SelectTrigger><SelectContent>{Object.entries({todo:'Yapılacak',requested:'İstendi',ready:'Hazır',uploaded:'Yüklendi'}).map(([value,label])=><SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></div>)}</>}
 <h3>Hazırlık planı</h3>{Object.values(state.fronts).flatMap(f=>f.moves).filter(m=>m.eventId===editing.id).map(m=><p className="plan-row" key={m.id}>{m.doneAt?<Check size={16}/>:<span className="plan-date">{m.prepareAt&&formatDate(m.prepareAt)}</span>}<span>{m.text}</span></p>)}{editing.date&&daysBetween(today,editing.date)<(editing.prepDays??(editing.kind==='application'?28:editing.kind==='exam'?10:7))&&<p className="notice">Süre dar: plan kalan günlere sıkıştırıldı; başkasına bağlı işler önce.</p>}<div className="row-actions"><button type="submit" className="primary" disabled={busy}>Değişiklikleri kaydet</button><button type="button" disabled={busy} onClick={async()=>{if(await action({kind:'cancelEvent',eventId:editing.id}))setEditing(null);}}>Kalemi kaldır</button></div><p className="quiet">Değişiklikleri kayıt defterinden geri alabilirsin.</p></form>}</DialogContent></Dialog>
 <Dialog open={!!selected} onOpenChange={open=>!open&&setMailId(null)}><DialogContent className="berthier-dialog"><DialogTitle>Çakışma için mail taslağı</DialogTitle><DialogDescription>Metni düzenleyip kendi mail uygulamandan gönderebilirsin.</DialogDescription>{!state.profile?<form className="event-form" onSubmit={e=>{e.preventDefault();void action({kind:'profile',profile});}}><p>İmzan için bu bilgileri bir kez kaydedelim. İstersen boş bırakabilirsin.</p>{Object.entries({name:'Ad soyad',number:'Öğrenci numarası',department:'Bölüm',university:'Üniversite'}).map(([key,label])=><label key={key}>{label}<input maxLength={key==='number'?50:100} value={profile[key as keyof Profile]} onChange={e=>setProfile({...profile,[key]:e.target.value})}/></label>)}<button className="primary" disabled={busy}>Kaydet ve taslağı göster</button></form>:selected&&<><textarea aria-label="Mail taslağı" className="mail-draft" defaultValue={eventMail(selected,state.profile)}/><p className="quiet">Taslağı seçip kopyala. Berthier mail göndermez.</p></>}</DialogContent></Dialog>
 </div>;
}
function formatDate(date:string){return new Date(date+'T12:00:00Z').toLocaleDateString('tr-TR',{day:'numeric',month:'short',weekday:'short'});}
