'use client';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {Mic,Square,Paperclip} from 'lucide-react';
import {localRead,localWrite} from '@/lib/offline';
import {MEDIA_LIMIT,mediaKind} from '@/lib/media';
type Saved={blob:Blob;name:string};
// The limits and providers are shown only when a file is chosen or a recording nears its limit (design 1f).
const LIMITS='Ses ve PDF en fazla 10 MB; görsel 7 MB. Kayıt en fazla 10 dakika; ekranı açık tut. Dökümü görüp düzelttikten sonra gönder. Ses Gemini’ye, görsel ve PDF Claude’a iletilir; dosyanın kendisi dökümden sonra tutulmaz.';
const BARS=40,NEAR=540,clock=(s:number)=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;
export default function MediaInput({userId,onText,onBusy,onRecording,send}:{userId:string;onText:(text:string,external:boolean)=>void|Promise<void>;onBusy:(busy:boolean)=>void;onRecording?:(recording:boolean)=>void;send?:ReactNode}){
 const [file,setFile]=useState<Saved|null>(null),[working,setWorking]=useState(false),[recording,setRecording]=useState(false),[seconds,setSeconds]=useState(0),[error,setError]=useState(''),[warning,setWarning]=useState(''),[levels,setLevels]=useState<number[]>([]),[large,setLarge]=useState(false);
 const input=useRef<HTMLInputElement>(null),recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),chunks=useRef<Blob[]>([]),size=useRef(0),live=useRef(true),starting=useRef(false),started=useRef(0),writes=useRef(Promise.resolve()),converting=useRef(false),finish=useRef<'convert'|'discard'|null>(null),audio=useRef<AudioContext|null>(null),sampler=useRef<ReturnType<typeof setInterval>|null>(null);
 const key=userId+':media-draft';
 useEffect(()=>{live.current=true;void localRead<Saved>(key).then(value=>{if(live.current&&value)setFile(value);}).catch(()=>{});return()=>{live.current=false;if(recorder.current?.state==='recording')recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop());stopLevels();};},[key]);
 useEffect(()=>{onBusy(working||recording);return()=>onBusy(false);},[working,recording,onBusy]);
 useEffect(()=>{onRecording?.(recording);return()=>onRecording?.(false);},[recording,onRecording]);
 useEffect(()=>{if(!recording)return;const timer=setInterval(()=>setSeconds(s=>{if(Date.now()-started.current>=600000){recorder.current?.stop();return 600;}return Math.floor((Date.now()-started.current)/1000);}),1000);return()=>clearInterval(timer);},[recording]);
 useEffect(()=>{const stop=()=>{if(document.visibilityState==='hidden'&&recorder.current?.state==='recording')recorder.current.stop();};document.addEventListener('visibilitychange',stop);window.addEventListener('pagehide',stop);return()=>{document.removeEventListener('visibilitychange',stop);window.removeEventListener('pagehide',stop);};},[]);
 // Level bars: the microphone's loudness every 150 ms. Without Web Audio the bars stay flat; recording is unaffected.
 function listen(s:MediaStream){const ctx=audio.current;if(!ctx)return;try{const analyser=ctx.createAnalyser();analyser.fftSize=512;ctx.createMediaStreamSource(s).connect(analyser);void ctx.resume().catch(()=>{});const data=new Uint8Array(analyser.fftSize);sampler.current=setInterval(()=>{analyser.getByteTimeDomainData(data);let sum=0;for(const v of data)sum+=((v-128)/128)**2;setLevels(l=>[...l.slice(1-BARS),Math.min(1,Math.sqrt(sum/data.length)*4)]);},150);}catch{}}
 function stopLevels(){if(sampler.current)clearInterval(sampler.current);sampler.current=null;void audio.current?.close().catch(()=>{});audio.current=null;}
 async function keep(value:Saved){setFile(value);try{await localWrite(key,value);}catch{setError('Dosya bu açık pencerede duruyor; kalıcı cihaz kaydı açılamadı. Döküm alınana kadar pencereyi açık tut.');}}
 async function choose(f:File){setError('');setWarning('');try{if(f.size>MEDIA_LIMIT)throw Error('En fazla 10 MB dosya seç.');if(mediaKind(f.type)==='image'&&f.size>7*1024*1024)throw Error('Görsel en fazla 7 MB olabilir. Daha küçük bir kopya seç.');await keep({blob:f,name:f.name});}catch(e){setError((e as Error).message);}}
 async function start(){if(starting.current||recorder.current?.state==='recording')return;starting.current=true;setWorking(true);setError('');setLevels([]);setLarge(false);try{const Context=window.AudioContext??(window as Window&{webkitAudioContext?:typeof AudioContext}).webkitAudioContext;try{audio.current=Context?new Context():null;}catch{audio.current=null;}if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw Error('Bu tarayıcı ses kaydını desteklemiyor. Klavyenin mikrofonunu kullanabilirsin.');const s=await navigator.mediaDevices.getUserMedia({audio:true});stream.current=s;if(!live.current){s.getTracks().forEach(t=>t.stop());stopLevels();return;}const type=['audio/mp4','audio/webm;codecs=opus','audio/webm'].find(t=>MediaRecorder.isTypeSupported(t));const r=new MediaRecorder(s,type?{mimeType:type,audioBitsPerSecond:64000}:{audioBitsPerSecond:64000});recorder.current=r;chunks.current=[];size.current=0;finish.current=null;setSeconds(0);r.ondataavailable=e=>{if(e.data.size){chunks.current.push(e.data);size.current+=e.data.size;if(size.current>=MEDIA_LIMIT*.9)setLarge(true);const checkpoint={blob:new Blob(chunks.current,{type:r.mimeType}),name:'Ses kaydı'};writes.current=writes.current.catch(()=>{}).then(()=>localWrite(key,checkpoint)).catch(()=>{if(live.current)setError('Kayıt şu an bellekte; cihaz yedeği yazılamadı. Pencereyi açık tut.');});if(size.current>=MEDIA_LIMIT-100000&&r.state==='recording')r.stop();}};
 // “Bitir ve yazıya dök” keeps the recording and transcribes it; “Vazgeç” removes it from the device. Any other stop (limit, app in background) keeps it waiting.
 r.onstop=()=>{starting.current=true;s.getTracks().forEach(t=>t.stop());stopLevels();const blob=new Blob(chunks.current,{type:r.mimeType}),then=finish.current;chunks.current=[];finish.current=null;if(live.current){setWorking(true);setRecording(false);}let next:Saved|null=null;writes.current=writes.current.catch(()=>{}).then(async()=>{if(then==='discard'){await localWrite(key,null);if(live.current)setFile(null);return;}const saved={blob,name:'Ses kaydı'};if(live.current)await keep(saved);else await localWrite(key,saved);if(then==='convert')next=saved;}).catch(()=>{}).finally(()=>{starting.current=false;if(live.current){setWorking(false);if(next)void convert(next);}});};r.onerror=()=>{setError('Kayıt kesildi. Elde kalan sesi dökmeyi deneyebilirsin.');if(r.state==='recording')r.stop();s.getTracks().forEach(t=>t.stop());setRecording(false);};started.current=Date.now();r.start(5000);listen(s);setRecording(true);}catch(e){stream.current?.getTracks().forEach(t=>t.stop());stopLevels();setError(e instanceof Error?e.message:'Mikrofon açılamadı.');}finally{starting.current=false;setWorking(false);}}
 function stop(then:'convert'|'discard'){finish.current=then;if(recorder.current?.state==='recording')recorder.current.stop();}
 async function convert(value=file){if(!value||converting.current)return;converting.current=true;setWorking(true);setError('');try{const response=await fetch('/api/media',{method:'POST',headers:{'Content-Type':value.blob.type},body:value.blob});const result=await response.json() as {text:string;warning:string;error?:string};if(!response.ok)throw Error(result.error||'Döküm alınamadı.');await onText(result.text,mediaKind(value.blob.type)!=='audio');setWarning(result.warning);setFile(null);}catch(e){setError(e instanceof Error?e.message:'Bağlantı kesildi; dosya cihazında saklı.');}finally{converting.current=false;setWorking(false);}}
 if(recording)return <section className="media-input is-recording" aria-label="Ses kaydı"><p className="rec-live" role="status"><span aria-hidden="true"/>KAYIT SÜRÜYOR</p><p className="rec-time"><span>{clock(seconds)}</span><span>/ 10:00</span></p><div className="rec-bars" aria-hidden="true">{Array.from({length:BARS},(_,i)=>{const v=levels[i];return <span key={i} className={v===undefined?undefined:'is-heard'} style={{height:v===undefined?6:Math.round(6+v*46)}}/>;})}</div><p className="rec-note">Bitirince yazıya dökülür; göndermeden önce metni görüp düzeltirsin. Ekran açık kalsın.</p>{(seconds>=NEAR||large)&&<p className="quiet media-limits">{LIMITS}</p>}<div className="rec-actions"><button className="btn-main" onClick={()=>stop('convert')}><Square size={14} fill="currentColor"/>Bitir ve yazıya dök</button><button className="btn-quiet" onClick={()=>stop('discard')}>Vazgeç</button></div><p className="rec-foot">SES YAZIYA DÖKÜLÜNCE DOSYA TUTULMAZ</p></section>;
 return <section className="media-input">{file&&<div className="media-pending"><p>{file.name} · {(file.blob.size/1024/1024).toFixed(1)} MB</p><div className="row-actions"><button disabled={working} onClick={()=>void convert()}>{working?'Yazıya dökülüyor…':'Yazıya dök'}</button><button disabled={working} onClick={async()=>{try{await localWrite(key,null);setFile(null);}catch{setError('Dosya cihazdan kaldırılamadı. Tekrar dene.');}}}>Vazgeç</button></div></div>}{(file||error)&&<p className="quiet media-limits">{LIMITS}</p>}{error&&<p role="alert" className="notice error">{error}</p>}{warning&&<p className="notice">{warning}</p>}<div className="say-row"><button className="say-pill" disabled={working||!!file} onClick={()=>void start()}><Mic size={17}/>Ses kaydet</button><button className="say-round" aria-label="Dosya ekle" disabled={working||!!file} onClick={()=>input.current?.click()}><Paperclip size={18}/></button><input hidden ref={input} type="file" accept="image/jpeg,image/png,image/webp,image/gif,application/pdf,audio/*" onChange={e=>{const f=e.target.files?.[0];if(f)void choose(f);e.target.value='';}}/><span className="say-spacer"/>{send}</div></section>;
}
