'use client';
import {useEffect,useRef,useState} from 'react';
import {Mic,Square,Paperclip} from 'lucide-react';
import {localRead,localWrite} from '@/lib/offline';
import {MEDIA_LIMIT,mediaKind} from '@/lib/media';
type Saved={blob:Blob;name:string};
export default function MediaInput({userId,onText,onBusy}:{userId:string;onText:(text:string,external:boolean)=>void|Promise<void>;onBusy:(busy:boolean)=>void}){
 const [file,setFile]=useState<Saved|null>(null),[working,setWorking]=useState(false),[recording,setRecording]=useState(false),[seconds,setSeconds]=useState(0),[error,setError]=useState(''),[warning,setWarning]=useState('');
 const input=useRef<HTMLInputElement>(null),recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),chunks=useRef<Blob[]>([]),size=useRef(0),live=useRef(true),starting=useRef(false),started=useRef(0),writes=useRef(Promise.resolve());
 const key=userId+':media-draft';
 useEffect(()=>{live.current=true;void localRead<Saved>(key).then(value=>{if(live.current&&value)setFile(value);}).catch(()=>{});return()=>{live.current=false;if(recorder.current?.state==='recording')recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop());};},[key]);
 useEffect(()=>{onBusy(working||recording);return()=>onBusy(false);},[working,recording,onBusy]);
 useEffect(()=>{if(!recording)return;const timer=setInterval(()=>setSeconds(s=>{if(Date.now()-started.current>=600000){recorder.current?.stop();return 600;}return Math.floor((Date.now()-started.current)/1000);}),1000);return()=>clearInterval(timer);},[recording]);
 useEffect(()=>{const stop=()=>{if(document.visibilityState==='hidden'&&recorder.current?.state==='recording')recorder.current.stop();};document.addEventListener('visibilitychange',stop);window.addEventListener('pagehide',stop);return()=>{document.removeEventListener('visibilitychange',stop);window.removeEventListener('pagehide',stop);};},[]);
 async function keep(value:Saved){setFile(value);try{await localWrite(key,value);}catch{setError('Dosya bu açık pencerede duruyor; kalıcı cihaz kaydı açılamadı. Döküm alınana kadar pencereyi açık tut.');}}
 async function choose(f:File){setError('');setWarning('');try{if(f.size>MEDIA_LIMIT)throw Error('En fazla 10 MB dosya seç.');if(mediaKind(f.type)==='image'&&f.size>7*1024*1024)throw Error('Görsel en fazla 7 MB olabilir. Daha küçük bir kopya seç.');await keep({blob:f,name:f.name});}catch(e){setError((e as Error).message);}}
 async function start(){if(starting.current||recorder.current?.state==='recording')return;starting.current=true;setWorking(true);setError('');try{if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw Error('Bu tarayıcı ses kaydını desteklemiyor. Klavyenin mikrofonunu kullanabilirsin.');const s=await navigator.mediaDevices.getUserMedia({audio:true});stream.current=s;if(!live.current){s.getTracks().forEach(t=>t.stop());return;}const type=['audio/mp4','audio/webm;codecs=opus','audio/webm'].find(t=>MediaRecorder.isTypeSupported(t));const r=new MediaRecorder(s,type?{mimeType:type,audioBitsPerSecond:64000}:{audioBitsPerSecond:64000});recorder.current=r;chunks.current=[];size.current=0;setSeconds(0);r.ondataavailable=e=>{if(e.data.size){chunks.current.push(e.data);size.current+=e.data.size;const checkpoint={blob:new Blob(chunks.current,{type:r.mimeType}),name:'Ses kaydı'};writes.current=writes.current.catch(()=>{}).then(()=>localWrite(key,checkpoint)).catch(()=>{if(live.current)setError('Kayıt şu an bellekte; cihaz yedeği yazılamadı. Pencereyi açık tut.');});if(size.current>=MEDIA_LIMIT-100000&&r.state==='recording')r.stop();}};r.onstop=()=>{starting.current=true;s.getTracks().forEach(t=>t.stop());const blob=new Blob(chunks.current,{type:r.mimeType});chunks.current=[];if(live.current){setWorking(true);setRecording(false);}writes.current=writes.current.catch(()=>{}).then(async()=>{if(live.current)await keep({blob,name:'Ses kaydı'});else await localWrite(key,{blob,name:'Ses kaydı'});}).catch(()=>{}).finally(()=>{starting.current=false;if(live.current)setWorking(false);});};r.onerror=()=>{setError('Kayıt kesildi. Elde kalan sesi dökmeyi deneyebilirsin.');if(r.state==='recording')r.stop();s.getTracks().forEach(t=>t.stop());setRecording(false);};started.current=Date.now();r.start(5000);setRecording(true);}catch(e){stream.current?.getTracks().forEach(t=>t.stop());setError(e instanceof Error?e.message:'Mikrofon açılamadı.');}finally{starting.current=false;setWorking(false);}}
 async function convert(){if(!file||working)return;setWorking(true);setError('');try{const response=await fetch('/api/media',{method:'POST',headers:{'Content-Type':file.blob.type},body:file.blob});const result=await response.json() as {text:string;warning:string;error?:string};if(!response.ok)throw Error(result.error||'Döküm alınamadı.');await onText(result.text,mediaKind(file.blob.type)!=='audio');setWarning(result.warning);setFile(null);}catch(e){setError(e instanceof Error?e.message:'Bağlantı kesildi; dosya cihazında saklı.');}finally{setWorking(false);}}
 return <section className="media-input"><div className="row-actions"><button disabled={!recording&&(working||!!file)} onClick={()=>recording?recorder.current?.stop():void start()}>{recording?<Square size={17}/>:<Mic size={17}/>} {recording?`Kaydı bitir · ${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`:'Ses kaydet'}</button><button disabled={recording||working||!!file} onClick={()=>input.current?.click()}><Paperclip size={17}/> Dosya ekle</button><input hidden ref={input} type="file" accept="image/jpeg,image/png,image/webp,image/gif,application/pdf,audio/*" onChange={e=>{const f=e.target.files?.[0];if(f)void choose(f);e.target.value='';}}/></div>{file&&<div className="media-pending"><p>{file.name} · {(file.blob.size/1024/1024).toFixed(1)} MB</p><div className="row-actions"><button disabled={working} onClick={()=>void convert()}>{working?'Yazıya dökülüyor…':'Yazıya dök'}</button><button disabled={working} onClick={async()=>{try{await localWrite(key,null);setFile(null);}catch{setError('Dosya cihazdan kaldırılamadı. Tekrar dene.');}}}>Vazgeç</button></div></div>}<p className="quiet">Ses ve PDF en fazla 10 MB; görsel 7 MB. Kayıt en fazla 10 dakika; ekranı açık tut. Dökümü görüp düzelttikten sonra gönder. Ses Gemini’ye, görsel ve PDF Claude’a iletilir; dosyanın kendisi dökümden sonra tutulmaz.</p>{error&&<p role="alert" className="notice error">{error}</p>}{warning&&<p className="notice">{warning}</p>}</section>;
}
