'use client';
import {useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {type State,similarity} from '@/lib/domain';
import {type Idea,pendingIdeas,suggestedIdeaMove} from '@/lib/research';
import {upper} from '@/lib/turkish';
type Props={state:State;busy:boolean;action:(body:{kind:string;[key:string]:unknown},options?:{quiet?:boolean;silent?:boolean})=>Promise<boolean|undefined>;laneId?:string;pending?:boolean};
// Fikir deposu (design 1k): grouped by lane (unowned first), filtered by kind. A row opens its actions on tap:
// “Hamleye çevir” · “Yeni cephe aç” · “At”, or “Projeye ata” · “At” for an unowned item. Nothing becomes a move
// unless chosen. The weekly review's second step shows only the items it has not seen yet (pending).
const KIND:Record<Idea['kind'],string>={idea:'FİKİR',reading:'OKUMA',question:'AÇIK SORU'},FILTERS=[['all','Tümü'],['idea','Fikir'],['reading','Okuma'],['question','Soru']] as const;
export function depotSummary(state:State){const stored=Object.values(state.ideas??{}).filter(i=>i.status==='stored'),lanes=new Set(stored.map(i=>i.laneId&&state.fronts[i.laneId]?.status!=='closed'?i.laneId:null).filter(Boolean)),orphan=stored.filter(i=>!i.laneId||state.fronts[i.laneId]?.status==='closed').length;return `${stored.length} KALEM · ${lanes.size} PROJE${orphan?` · ${orphan} SAHİPSİZ`:''}`;}
export default function Research({state,busy,action,laneId,pending=false}:Props){
 const [edit,setEdit]=useState<{idea:Idea;decision:'move'|'front';text:string;title:string}|null>(null),[kind,setKind]=useState<'all'|Idea['kind']>('all'),[openId,setOpenId]=useState<string|null>(null),[assign,setAssign]=useState(false);
 const lanes=Object.values(state.fronts).filter(f=>f.type==='lane'&&f.status!=='closed').sort((a,b)=>Number(b.status==='active')-Number(a.status==='active')||a.title.localeCompare(b.title,'tr'));
 const pool=pending?pendingIdeas(state):Object.values(state.ideas??{}).filter(i=>i.status==='stored'&&(!laneId||i.laneId===laneId)).sort((a,b)=>a.createdAt.localeCompare(b.createdAt)),ideas=pool.filter(i=>kind==='all'||i.kind===kind);
 const owner=(i:Idea)=>{const l=i.laneId?state.fronts[i.laneId]:undefined;return l&&l.status!=='closed'?l:undefined;};
 const groups=laneId?[{id:laneId,lane:state.fronts[laneId],items:ideas}]:[{id:'none',lane:undefined,items:ideas.filter(i=>!owner(i))},...lanes.map(l=>({id:l.id,lane:l,items:ideas.filter(i=>owner(i)?.id===l.id)}))].filter(g=>g.items.length);
 function row(i:Idea){const lane=owner(i),related=lane?.status==='active'&&!!lane.question&&similarity(i.text,lane.question)>=.2,open=openId===i.id;return <div className={open?'idea-row is-open':'idea-row'} key={i.id}><button className="idea-main" aria-expanded={open} onClick={()=>{setOpenId(open?null:i.id);setAssign(false);}}><span className="idea-kind">{KIND[i.kind]}{related&&<span className="idea-related">SIRADAKİ SORUYLA İLGİLİ</span>}</span><span className="idea-line">{i.text}</span></button>
 {open&&<div className="idea-acts">{lane?<><button className="is-main" disabled={busy} onClick={()=>setEdit({idea:i,decision:'move',text:suggestedIdeaMove(i),title:''})}>Hamleye çevir</button><button disabled={busy} onClick={()=>setEdit({idea:i,decision:'front',text:suggestedIdeaMove(i),title:i.text.split(' ').slice(0,5).join(' ').slice(0,90)})}>Yeni cephe aç</button></>:<button className="is-main" aria-expanded={assign} disabled={busy||!lanes.length} onClick={()=>setAssign(!assign)}>Projeye ata</button>}<button className="is-quiet" disabled={busy} onClick={()=>action({kind:'ideaDecide',ideaId:i.id,decision:'discard'})}>At</button></div>}
 {open&&!lane&&assign&&<div className="idea-lanes">{lanes.map(l=><button key={l.id} disabled={busy} onClick={async()=>{if(await action({kind:'ideaAssign',ideaId:i.id,frontId:l.id}))setAssign(false);}}>{l.title}</button>)}</div>}
 {open&&!lane&&!lanes.length&&<p className="quiet">Henüz proje yok. Önce yapmak istediğin projeyi dikte et; bu fikir burada korunur.</p>}</div>;}
 return <div className="research">{!pending&&!laneId&&pool.length>0&&<div className="filter-chips" role="group" aria-label="Türe göre süz">{FILTERS.map(([k,label])=><button key={k} aria-pressed={kind===k} onClick={()=>setKind(k)}>{label} {k==='all'?pool.length:pool.filter(i=>i.kind===k).length}</button>)}</div>}
 {!pool.length&&<p className="intro">{pending?'Bu teftiş için yeni depo kalemi kalmadı.':'Fikirlerin burada bekler; sen seçene kadar hamleye dönüşmez.'}</p>}
 {groups.map(g=><section className="idea-group" key={g.id}>{!laneId&&<h2><span className={g.lane?'idea-bar':'idea-bar is-none'}/>{g.lane?upper(g.lane.title):'SAHİPSİZ'}<span>{g.lane?`${g.lane.status==='active'?'AKTİF':'BEKLETİLİYOR'} · ${g.items.length}`:g.items.length}</span></h2>}{g.items.map(row)}</section>)}
 {!pending&&pool.length>0&&<p className="quiet idea-note">Satıra dokununca seçenekler açılır. Atılan ve hamleye çevrilen kalemler kayıt defterinden geri alınır.</p>}
 <Dialog open={!!edit} onOpenChange={open=>!open&&setEdit(null)}><DialogContent className="berthier-dialog"><DialogTitle>{edit?.decision==='front'?'Depodan yeni cephe':'Fikri hamleye çevir'}</DialogTitle><DialogDescription>Somut öneriyi düzenleyebilirsin. Yeni proje bekletilen olarak açılır; aktif seçimi sende.</DialogDescription>{edit&&<form className="event-form" onSubmit={async e=>{e.preventDefault();if(await action({kind:'ideaDecide',ideaId:edit.idea.id,decision:edit.decision,text:edit.text,title:edit.title}))setEdit(null);}}>{edit.decision==='front'&&<label>Cephe adı<input required maxLength={90} value={edit.title} onChange={e=>setEdit({...edit,title:e.target.value})}/></label>}<label>Somut hamle<textarea required maxLength={120} value={edit.text} onChange={e=>setEdit({...edit,text:e.target.value})}/></label><button className="primary" disabled={busy}>Onayla ve ekle</button></form>}</DialogContent></Dialog>
 </div>;
}
