'use client';
import {useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {type State,similarity} from '@/lib/domain';
import {type Idea,pendingIdeas,suggestedIdeaMove} from '@/lib/research';
type Props={state:State;busy:boolean;action:(body:{kind:string;[key:string]:unknown},options?:{quiet?:boolean;silent?:boolean})=>Promise<boolean|undefined>;laneId?:string;pending?:boolean};
// Fikir deposu. The weekly review's second step shows only the items it has not seen yet (pending).
export default function Research({state,busy,action,laneId,pending=false}:Props){
 const [edit,setEdit]=useState<{idea:Idea;decision:'move'|'front';text:string;title:string}|null>(null);
 const lanes=Object.values(state.fronts).filter(f=>f.type==='lane'&&f.status!=='closed');
 const ideas=pending?pendingIdeas(state):Object.values(state.ideas??{}).filter(i=>i.status==='stored'&&(!laneId||i.laneId===laneId));
 return <div className="research">{!ideas.length&&<p className="intro">{pending?'Bu teftiş için yeni depo kalemi kalmadı.':'Fikirlerin burada bekler; sen seçene kadar hamleye dönüşmez.'}</p>}{ideas.map(i=>{const lane=i.laneId?state.fronts[i.laneId]:undefined;const related=lane?.status==='active'&&lane.question&&similarity(i.text,lane.question)>=.2;return <article className="idea-card" key={i.id}><p className="quiet">{{idea:'Fikir',reading:'Okuma',question:'Açık soru'}[i.kind]} · {lane?.title??'Sahipsiz'}</p><p className="idea-text">{i.text}</p>{related&&<p className="notice">Aktif kulvarının sıradaki sorusuyla ilgili görünüyor.</p>}{(!lane||lane.status==='closed')&&<Select onValueChange={frontId=>void action({kind:'ideaAssign',ideaId:i.id,frontId})} disabled={busy}><SelectTrigger aria-label="Fikrin kulvarı"><SelectValue placeholder="Önce bir kulvara ata"/></SelectTrigger><SelectContent>{lanes.map(f=><SelectItem key={f.id} value={f.id}>{f.title}</SelectItem>)}</SelectContent></Select>}{!lanes.length&&!lane&&<p className="quiet">Henüz kulvar yok. Önce yapmak istediğin projeyi dikte et; bu fikir burada korunur.</p>}<div className="idea-actions"><button disabled={busy||!lane||lane.status==='closed'} onClick={()=>setEdit({idea:i,decision:'move',text:suggestedIdeaMove(i),title:''})}>Hamleye çevir</button><button disabled={busy||!lane||lane.status==='closed'} onClick={()=>setEdit({idea:i,decision:'front',text:suggestedIdeaMove(i),title:i.text.split(' ').slice(0,5).join(' ').slice(0,90)})}>Yeni cephe aç</button><button disabled={busy} onClick={()=>action({kind:'ideaDecide',ideaId:i.id,decision:'discard'})}>At</button></div></article>;})}
 {!pending&&<p className="quiet">Atılan ve hamleye çevrilen kalemler kayıt defterinden geri alınabilir. Eski dikteler için kayıt defterindeki “Fikirleri depoya aktar” seçeneğini kullan.</p>}
 <Dialog open={!!edit} onOpenChange={open=>!open&&setEdit(null)}><DialogContent className="berthier-dialog"><DialogTitle>{edit?.decision==='front'?'Depodan yeni cephe':'Fikri hamleye çevir'}</DialogTitle><DialogDescription>Somut öneriyi düzenleyebilirsin. Yeni kulvar bekletilen olarak açılır; aktif seçimi sende.</DialogDescription>{edit&&<form className="event-form" onSubmit={async e=>{e.preventDefault();if(await action({kind:'ideaDecide',ideaId:edit.idea.id,decision:edit.decision,text:edit.text,title:edit.title}))setEdit(null);}}>{edit.decision==='front'&&<label>Cephe adı<input required maxLength={90} value={edit.title} onChange={e=>setEdit({...edit,title:e.target.value})}/></label>}<label>Somut hamle<textarea required maxLength={120} value={edit.text} onChange={e=>setEdit({...edit,text:e.target.value})}/></label><button className="primary" disabled={busy}>Onayla ve ekle</button></form>}</DialogContent></Dialog>
 </div>;
}
