'use client';
import {useEffect,useState} from 'react';
import {Archive,ClipboardCheck,ChevronRight} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {type State,similarity} from '@/lib/domain';
import {type Idea,pendingIdeas,staleFronts,laneSuggestion,suggestedIdeaMove} from '@/lib/research';
import Horizon from './horizon';
type Props={state:State;busy:boolean;action:(body:{kind:string;[key:string]:unknown})=>Promise<boolean|undefined>;dictate:(text:string)=>void;laneId?:string;review?:boolean};
const steps=['Bayat cepheler','Fikir deposu','Aktif kulvarlar','Ufuk','Özet'];
export function ResearchLinks({state,open}:{state:State;open:(view:string)=>void}){return <><button className="map-link" onClick={()=>open('depot')}><Archive/><div><h2>Fikir deposu</h2><p>{Object.values(state.ideas??{}).filter(i=>i.status==='stored').length} fikir, okuma ve soru</p></div><ChevronRight/></button><button className="map-link" onClick={()=>open('review')}><ClipboardCheck/><div><h2>Haftalık teftiş</h2><p>{state.review&&!state.review.completedAt?`${state.review.step+1}/5 · Kaldığın yerden devam et`:'Pazar 20:00 · İstersen şimdi başlayabilirsin'}</p></div><ChevronRight/></button></>;}
export default function Research({state,busy,action,dictate,laneId,review=false}:Props){
 const [edit,setEdit]=useState<{idea:Idea;decision:'move'|'front';text:string;title:string}|null>(null),[selected,setSelected]=useState<string[]>([]);
 const lanes=Object.values(state.fronts).filter(f=>f.type==='lane'&&f.status!=='closed');
 useEffect(()=>setSelected(lanes.filter(f=>f.status==='active').map(f=>f.id)),[state.fronts,state.review?.id]);
 const session=state.review,step=review?session?.step??0:1,openSession=!!session&&!session.completedAt;
 const ideas=review?pendingIdeas(state):Object.values(state.ideas??{}).filter(i=>i.status==='stored'&&(!laneId||i.laneId===laneId));
 async function advance(to:number){await action({kind:'reviewStep',step:to});}
 function depot(){return <>{!ideas.length&&<p className="intro">{review?'Bu teftiş için yeni depo kalemi kalmadı.':'Fikirlerin burada bekler; sen seçene kadar hamleye dönüşmez.'}</p>}{ideas.map(i=>{const lane=i.laneId?state.fronts[i.laneId]:undefined;const related=lane?.status==='active'&&lane.question&&similarity(i.text,lane.question)>=.2;return <article className="idea-card" key={i.id}><p className="quiet">{{idea:'Fikir',reading:'Okuma',question:'Açık soru'}[i.kind]} · {lane?.title??'Sahipsiz'}</p><p className="idea-text">{i.text}</p>{related&&<p className="notice">Aktif kulvarının sıradaki sorusuyla ilgili görünüyor.</p>}{(!lane||lane.status==='closed')&&<Select onValueChange={frontId=>void action({kind:'ideaAssign',ideaId:i.id,frontId})} disabled={busy}><SelectTrigger aria-label="Fikrin kulvarı"><SelectValue placeholder="Önce bir kulvara ata"/></SelectTrigger><SelectContent>{lanes.map(f=><SelectItem key={f.id} value={f.id}>{f.title}</SelectItem>)}</SelectContent></Select>}{!lanes.length&&!lane&&<p className="quiet">Henüz kulvar yok. Önce yapmak istediğin projeyi dikte et; bu fikir burada korunur.</p>}<div className="idea-actions"><button disabled={busy||!lane||lane.status==='closed'} onClick={()=>setEdit({idea:i,decision:'move',text:suggestedIdeaMove(i),title:''})}>Hamleye çevir</button><button disabled={busy||!lane||lane.status==='closed'} onClick={()=>setEdit({idea:i,decision:'front',text:suggestedIdeaMove(i),title:i.text.split(' ').slice(0,5).join(' ').slice(0,90)})}>Yeni cephe aç</button><button disabled={busy} onClick={()=>action({kind:'ideaDecide',ideaId:i.id,decision:'keep'})}>Depoda kalsın</button><button disabled={busy} onClick={()=>action({kind:'ideaDecide',ideaId:i.id,decision:'discard'})}>At</button></div></article>;})}</>;}
 if(review&&!openSession)return <section className="review-start"><ClipboardCheck size={30}/><h2>{session?.completedAt?'Son teftiş tamamlandı.':'Haritaya birlikte bakalım.'}</h2><p>Beş kısa adım: bayat cepheler, depo, aktif kulvarlar, ufuk ve özet. Yarıda kapatırsan kaldığın yer saklanır.</p>{session?.completedAt&&<details className="archive"><summary>Son teftiş özeti</summary>{session.decisions.map((d,i)=><p key={i}>{d}</p>)}</details>}<button className="primary" disabled={busy} onClick={()=>action({kind:'reviewStart'})}>Teftişi başlat</button></section>;
 return <div className="research">{review&&<><ol className="review-steps" aria-label="Teftiş adımları">{steps.map((label,i)=><li key={label} aria-current={i===step?'step':undefined}><button disabled={busy} className={i===step?'chosen':''} onClick={()=>advance(i)}>{i+1}<span>{label}</span></button></li>)}</ol><h2 className="subheading">{step+1}. {steps[step]}</h2><p className="quiet">Her karar kaydedilir. Buradan ayrıldığında kaldığın adım korunur.</p></>}
 {step===0&&<>{!staleFronts(state).length&&<p className="intro">Bir haftadır dokunulmamış açık cephe yok.</p>}{staleFronts(state).map(f=><article className="idea-card" key={f.id}><h3>{f.title}</h3><p className="quiet">Son dokunuş: {new Date(f.touched).toLocaleDateString('tr-TR')}</p>{f.status==='held'&&Date.now()-Date.parse(f.touched)>28*86400000&&<p>Uzun süredir bekliyor. Artık gündeminde değilse kapatabilirsin; yeniden açılabilir.</p>}<div className="idea-actions"><button disabled={busy} onClick={()=>action({kind:'reviewContinue',frontId:f.id})}>Sürdür</button>{f.type==='lane'&&<button disabled={busy} onClick={()=>action({kind:'status',frontId:f.id,status:'held'})}>Beklet</button>}<button disabled={busy} onClick={()=>action({kind:'status',frontId:f.id,status:'closed'})}>Kapat</button></div></article>)}</>}
 {step===1&&depot()}
 {step===2&&<><p className="intro">İstediğin kadar kulvar seç. Diğerleri bekler; tarihli kalemleri Ufuk’ta izlenir.</p>{lanes.map(f=><label className="choice" key={f.id}><Checkbox checked={selected.includes(f.id)} onCheckedChange={checked=>setSelected(ids=>checked?[...ids,f.id]:ids.filter(id=>id!==f.id))}/><span><strong>{f.title}</strong>{laneSuggestion(state,f)&&<small>Öneri · {laneSuggestion(state,f)}</small>}</span></label>)}<p className="quiet">{selected.length} kulvar seçili</p><button className="primary" disabled={busy} onClick={()=>action({kind:'setup',ids:selected})}>Seçimi kaydet</button></>}
 {step===3&&<><section className="notice">{Object.values(state.events??{}).filter(e=>!e.cancelled&&e.date&&e.frontId&&!state.fronts[e.frontId]?.moves.some(m=>m.eventId===e.id&&m.doneAt)).length} tarihli kalemin hazırlığında henüz tamamlanan hamle yok.</section><Horizon state={state} busy={busy} action={action} dictate={dictate}/></>}
 {step===4&&<><p className="intro">{lanes.filter(f=>f.status==='active').length} aktif kulvar · {Object.values(state.ideas??{}).filter(i=>i.status==='stored').length} kalem depoda.</p>{session?.decisions.length?<ul className="review-summary">{session.decisions.map((d,i)=><li key={i}>{d}</li>)}</ul>:<p>Bu teftişte henüz harita değişikliği yapmadın.</p>}<button className="primary" disabled={busy} onClick={()=>action({kind:'reviewFinish'})}>Teftişi tamamla</button></>}
 {review&&<div className="review-footer">{step>0&&<button disabled={busy} onClick={()=>advance(step-1)}>Önceki adım</button>}{step<4&&<button disabled={busy} onClick={async()=>{if(step===2&&!(await action({kind:'setup',ids:selected})))return;await advance(step+1);}}>Sonraki adım</button>}</div>}
 {!review&&<p className="quiet">Atılan ve hamleye çevrilen kalemler kayıt defterinden geri alınabilir. Eski dikteler için kayıt defterindeki “Fikirleri depoya aktar” seçeneğini kullan.</p>}
 <Dialog open={!!edit} onOpenChange={open=>!open&&setEdit(null)}><DialogContent className="berthier-dialog"><DialogTitle>{edit?.decision==='front'?'Depodan yeni cephe':'Fikri hamleye çevir'}</DialogTitle><DialogDescription>Somut öneriyi düzenleyebilirsin. Yeni kulvar bekletilen olarak açılır; aktif seçimi sende.</DialogDescription>{edit&&<form className="event-form" onSubmit={async e=>{e.preventDefault();if(await action({kind:'ideaDecide',ideaId:edit.idea.id,decision:edit.decision,text:edit.text,title:edit.title}))setEdit(null);}}>{edit.decision==='front'&&<label>Cephe adı<input required maxLength={90} value={edit.title} onChange={e=>setEdit({...edit,title:e.target.value})}/></label>}<label>Somut hamle<textarea required maxLength={120} value={edit.text} onChange={e=>setEdit({...edit,text:e.target.value})}/></label><button className="primary" disabled={busy}>Onayla ve ekle</button></form>}</DialogContent></Dialog>
 </div>;
}
