'use client';
import {useEffect,useRef,useState} from 'react';
import {BookOpen,Check,ChevronRight,Flag,WifiOff} from 'lucide-react';
import {type State,type Dictation,dayKey,ensureOrder} from '@/lib/domain';
import {addDays,daysBetween,occurrences,type CalendarEvent} from '@/lib/calendar';
import {buildMorningReport,expeditionDays,expeditionMetrics,type MorningReport} from '@/lib/rhythm';
import {RouteReorder} from './atlas-order';

type Action=(body:{kind:string;[key:string]:unknown})=>Promise<boolean|undefined>;
const regions={course:'Ders Ovası',lane:'Kulvar Dağları',application:'Başvuru Geçidi',general:'Genel Düzlük'};
const dateLabel=(date:string)=>new Date(date+'T12:00:00Z').toLocaleDateString('tr-TR',{weekday:'short',day:'numeric',month:'short'});
const timeLabel=(date:string)=>new Date(date).toLocaleTimeString('tr-TR',{timeZone:'Europe/Istanbul',hour:'2-digit',minute:'2-digit'});
export function RhythmLinks({open}:{open:(view:string)=>void}){return <><button className="map-link" onClick={()=>open('report')}><BookOpen/><div><h2>Sabah raporu</h2><p>Emir, uyarılar, yerler ve bekleyen kararlar.</p></div><ChevronRight/></button><button className="map-link" onClick={()=>open('journal')}><Flag/><div><h2>Sefer defteri</h2><p>Tamamlanan hamlelerin bıraktığı iz.</p></div><ChevronRight/></button></>;}

export function MorningReportView({state,dictations,online,busy,action,opened,answer,select,home,horizon}:{state:State;dictations:Dictation[];online:boolean;busy:boolean;action:Action;opened:(date:string)=>void;answer:(d:Dictation)=>void;select:()=>void;home:()=>void;horizon:(eventId?:string,conflictId?:string)=>void}){
 const [reordering,setReordering]=useState(false),noted=useRef('');
 const date=dayKey(),saved=state.reports?.[date]??Object.values(state.reports??{}).sort((a,b)=>b.date.localeCompare(a.date))[0];
 const report:MorningReport=saved??buildMorningReport(state,dictations,new Date());
 const order=report.date===date?ensureOrder(state):report.order;
 useEffect(()=>{if(online&&saved&&noted.current!==saved.date){noted.current=saved.date;opened(saved.date);}},[online,saved,opened]);
 const disabled=busy||!online,sections=[['I','Emir',order.slots.length],['II','Uyarı',report.alerts.length],['III','Yer',report.places.today.length+report.places.tomorrow.length],['IV','Karar',report.decisions.questions.length+report.decisions.drafts.length]] as const;
 const route=order.slots.map(s=>regions[s.frontType??state.fronts[s.frontId]?.type??'general']).filter((r,i,a)=>i===0||r!==a[i-1]);
 
 function due(frontId:string){const ev=occurrences(Object.values(state.events??{}).filter(e=>e.frontId===frontId),date,addDays(date,366))[0];return ev?.date?daysBetween(date,ev.date):null;}
 return <div className="morning-report">
  <p className="rhythm-meta">{dateLabel(report.date)} · {timeLabel(report.generatedAt)}’DE HAZIRLANDI</p>
  {!online&&<div className="notice"><WifiOff size={18}/>Bağlantı yok. Rapor {timeLabel(report.generatedAt)}’deki haliyle gösteriliyor; dikte cihazda saklanır.</div>}
  {!saved&&<p className="quiet">İlk rapor hazırlanıyor; son kayıtlarından önizleme gösteriliyor.</p>}
  <nav className="report-contents" aria-label="Rapor bölümleri">{sections.map(([roman,label,count],i)=><button key={roman} onClick={()=>document.getElementById('report-section-'+i)?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'})}><span>{roman}</span>{label} <b>{count||'yok'}</b></button>)}</nav>
  <section className="report-section" id="report-section-0"><ReportHeading roman="I" title="Günün emri" count={order.slots.length}/>
   {!!order.slots.length&&<><div className="report-route" aria-label="Günün güzergâhı"><span>✳</span>{order.slots.map((s,i)=><span className={s.doneAt?'passed':due(s.frontId)!==null&&due(s.frontId)!<=2?'critical':due(s.frontId)!==null&&due(s.frontId)!<=7?'urgent':''} key={s.frontId}>{s.doneAt?'✓':String(i+1).padStart(2,'0')}</span>)}</div><p className="quiet route-description">Güzergâh: Karargâh{route.length?' → '+route.join(' → '):''}</p></>}
   {!order.slots.length?<p>Bugün için önerilen cephe yok. İstersen bir cephe ekleyebilirsin.</p>:order.slots.map((slot,i)=>{const f=state.fronts[slot.frontId],days=due(slot.frontId);return <article className={'report-move '+(slot.doneAt?'is-passed':'')} key={slot.frontId}><span className="report-rank">{slot.doneAt?'✓':String(i+1).padStart(2,'0')}</span><div><p className="quiet">{slot.frontTitle??f?.title??'Cephe'} · {regions[slot.frontType??f?.type??'general']}</p><h3>{slot.text}</h3><p className="quiet">↳ {slot.reason}</p>{slot.doneAt&&<small>GEÇİLDİ · {timeLabel(slot.doneAt)}</small>}</div>{days!==null&&<span className={'due-chip '+(days<=7?'urgent':'')}>{days===0?'BUGÜN':days===1?'YARIN':days+' GÜN'}</span>}</article>;})}
   <div className="row-actions"><button disabled={disabled||order.slots.length<2} onClick={()=>setReordering(true)}>Sırayı düzenle</button><button disabled={disabled} onClick={select}>Cephe ekle / çıkar</button></div>
  </section>
  <section className="report-section" id="report-section-1"><ReportHeading roman="II" title="Uyarılar" count={report.alerts.length}/>{!report.alerts.length?<p>Uyarı yok.</p>:report.alerts.map(alert=>{const seen=alert.conflictId?state.seenConflicts?.includes(alert.conflictId):!!alert.seenAt;return <article className={'report-alert '+(seen?'is-seen':'')} key={alert.id}><div className="rhythm-meta"><span>{alert.kind==='conflict'?'SAAT ÇAKIŞMASI':'HAZIRLIK DARALIYOR'}</span><span>{seen?'GÖRÜLDÜ':timeLabel(alert.createdAt)+'’TE YAKALANDI'}</span></div><p>{alert.text}</p><div className="row-actions"><button disabled={disabled} onClick={()=>horizon(alert.eventId,alert.conflictId)}>{alert.kind==='conflict'?'Başka saat için mail taslağı':'Belgeleri gör'}</button><button disabled={disabled} onClick={()=>action({kind:'reportAlertSeen',reportDate:report.date,alertId:alert.id,seen:!seen})}>{seen?'Geri al':'Görüldü'}</button></div></article>;})}</section>
  <section className="report-section" id="report-section-2"><ReportHeading roman="III" title="Bugün ve yarın" count={report.places.today.length+report.places.tomorrow.length}/><Places title={'BUGÜN · '+dateLabel(report.date)} events={report.places.today}/><Places title={'YARIN · '+dateLabel(addDays(report.date,1))} events={report.places.tomorrow}/></section>
  <section className="report-section" id="report-section-3"><ReportHeading roman="IV" title="Kararını bekleyenler" count={report.decisions.questions.length+report.decisions.drafts.length}/>{!report.decisions.questions.length&&!report.decisions.drafts.length&&<p>Kararını bekleyen bir şey yok.</p>}{report.decisions.questions.map(q=>{const source=dictations.find(d=>d.id===q.id),answered=!!q.answeredAt||source?.status==='answered';return <article className="report-decision" key={q.id}><p>{q.text}</p>{answered?<><p className="gold">✓ Yanıtın kaydedildi{q.answer?': '+q.answer:'.'}</p>{q.answerChangeId&&<button disabled={disabled} onClick={()=>action({kind:'undo',changeId:q.answerChangeId})}>Geri al</button>}</>:<button disabled={disabled||!source} onClick={()=>source&&answer(source)}>Yanıtla</button>}</article>;})}{report.decisions.drafts.map(d=><article className="report-decision" key={d.id}><h3>{d.title}</h3><p className="quiet">Gönderen sensin; Berthier göndermez.</p><button disabled={disabled} onClick={()=>horizon(undefined,d.conflictId)}>Taslağı aç</button></article>)}</section>
  <p className="rhythm-meta report-end">RAPORUN SONU · SABAH BİLDİRİM TERCİHİ {state.notificationPreferences?.morningTime??'08:30'}</p>
  <div className="report-approval">{order.approvedAt?<><p className="gold"><Check size={17}/>Onaylandı · {timeLabel(order.approvedAt)}</p><div className="row-actions"><button disabled={disabled} onClick={()=>action({kind:'reportUnapprove',reportDate:report.date})}>Geri al</button><button onClick={home}>Karargâh’a git</button></div></>:order.slots.length?<button className="primary" disabled={disabled||!state.setup||report.date!==date} onClick={()=>action({kind:'approve'})}>Emri onayla <span>{order.slots.length} CEPHE</span></button>:<button className="primary" onClick={home}>Karargâh’a dön</button>}{!online&&<small>Onay için bağlantı gerekiyor. Diktelerin cihazda saklanır.</small>}</div>
  <RouteReorder open={reordering} onOpenChange={setReordering} state={state} order={order} disabled={disabled} action={action}/>
 </div>;
}
function ReportHeading({roman,title,count}:{roman:string;title:string;count:number}){return <h2 className="report-heading"><span>{roman}</span>{title}<small>{count||'yok'}</small></h2>;}
function Places({title,events}:{title:string;events:CalendarEvent[]}){return <div className="report-places"><h3 className="rhythm-meta">{title}</h3>{!events.length?<p>Olunacak yer yok.</p>:events.map(e=><article key={e.id+e.date}><h4>{e.location}</h4><p>{e.time??'Saat netleşecek'} · {e.title}</p><span className="rhythm-meta gold">YANINA AL</span>{e.bring.length?<ul>{e.bring.map((b,i)=><li key={i}>{b}</li>)}</ul>:<p className="quiet">Kaydedilmiş bir şey yok.</p>}</article>)}</div>;}

export function ExpeditionJournal({state,online,busy,action}:{state:State;online:boolean;busy:boolean;action:Action}){
 const days=expeditionDays(state),metrics=expeditionMetrics(state),start=state.expedition?.startedOn??dayKey();
 const elapsed=Math.max(1,daysBetween(start,dayKey())+1);
 return <div className="expedition-journal"><p className="rhythm-meta">İKİ HAFTALIK SEFER · {Math.min(elapsed,14)}. GÜN / 14 · {dateLabel(start)} – {dateLabel(addDays(start,13))}</p><div className="journal-strip" aria-label="İki haftalık sefer">{Array.from({length:14},(_,i)=>{const d=addDays(start,i),entry=days.find(x=>x.date===d);return <div title={dateLabel(d)} className={d===dayKey()?'today':d>dayKey()?'future':entry?.completed?'recorded':'empty'} key={d}><span/><small>{d.slice(8)}</small></div>;})}</div>
 <div className="journal-totals"><span>ALINAN KAMP <b>{days.reduce((sum,d)=>sum+d.completed,0)}</b></span><span>KAPANAN CEPHE <b>{days.reduce((sum,d)=>sum+d.closedFronts.length,0)}</b></span></div>
 {days.filter(d=>d.status!=='future').slice().reverse().map(d=><article className="journal-day" key={d.date}><div className="journal-day-heading"><h2>{dateLabel(d.date)}</h2><span className={d.status==='completed'?'gold':''}>{d.status==='completed'?'SEFER TAMAMLANDI':d.status==='rest'||!d.total?'KARARGÂHTA':'SÜRÜYOR'}</span></div><div className="journal-seals" aria-hidden="true"><span>✳</span>{d.slots.map((s,i)=><span key={s.frontId} className={s.doneAt?'passed':''}>{s.doneAt?'⚑':i+1}</span>)}</div><p>{d.summary}</p>{d.closedFronts.map(f=><p className="closed-seal" key={f.id}>⚑ CEPHE KAPANDI · {f.title}</p>)}</article>)}
 <details className="expedition-metrics"><summary>Seferin ölçümleri</summary><div><p><b>%{Math.round((metrics.completionRate??0)*100)}</b> · {metrics.completed}/{metrics.total} emirdeki hamle tamamlandı.</p><p>Rapor açılışından onaya: <b>{metrics.averageApprovalSeconds===null?'Henüz ölçüm yok':metrics.averageApprovalSeconds<60?Math.round(metrics.averageApprovalSeconds)+' sn':(metrics.averageApprovalSeconds/60).toFixed(1)+' dk'}</b></p><p>Elle düzenleme: <b>{metrics.manualEdits}</b> · Ayar değişikliği: <b>{metrics.settingChanges}</b></p><p className="quiet">14. günde tek soru sorulur: Kilitlenmeler seyreldi mi? Hükmü sen verirsin.</p></div></details>
 {elapsed>=14&&<section className="reflection"><h2>Kilitlenmeler seyreldi mi?</h2>{state.expedition?.reflection?<p className="gold">Yanıtın: {state.expedition.reflection.answer}</p>:<div className="row-actions">{['Evet','Kısmen','Hayır'].map(answer=><button key={answer} disabled={busy||!online} onClick={()=>action({kind:'expeditionReflection',answer})}>{answer}</button>)}</div>}</section>}
 </div>;
}
