import type {Front,FrontType} from './domain';

export type Point=[number,number];
export type Box=[number,number,number,number];
export type CampPosition={type:FrontType;point:Point};
export type Positions=Record<string,CampPosition>;
export const WORLD={X0:-380,Y0:-420,X1:1180,Y1:1520,ST:6,PS:12,LV:.036,HQ:[400,640] as Point};
const RIDGE:Point[]=[[-420,300],[-150,250],[100,175],[300,225],[470,135],[640,190],[860,110],[1200,60]];
const VAL:Point[]=[[520,660],[590,530],[660,400],[715,270],[770,130],[840,-60],[900,-260]];
export const RIVER:Point[]=[[760,155],[741,205],[715,270],[690,335],[660,400],[627,462],[590,530],[556,594],[520,660],[512,715],[528,770],[534,825],[515,878],[492,930],[470,990],[458,1048],[436,1108],[404,1168],[380,1240],[352,1320],[336,1420],[318,1540]];
const HILLS=[[160,880,.06,120],[420,1010,.045,150],[650,940,.07,110],[250,1190,.055,130],[600,1230,.05,140],[40,1060,.06,110],[-120,820,.08,140]];
export const REGION_NAMES:Record<FrontType,string>={course:'Ders Ovası',lane:'Kulvar Dağları',application:'Başvuru Geçidi',general:'Genel Düzlük'};
const smooth=(a:number,b:number,x:number)=>{const t=Math.max(0,Math.min(1,(x-a)/(b-a)));return t*t*(3-2*t);};
const smin=(a:number,b:number,k:number)=>{const q=Math.max(k-Math.abs(a-b),0)/k;return Math.min(a,b)-q*q*k*.25;};
export function distanceToLine(x:number,y:number,p:Point[]){let best=Infinity,s=0,acc=0;for(let i=0;i<p.length-1;i++){const [ax,ay]=p[i],dx=p[i+1][0]-ax,dy=p[i+1][1]-ay,l2=dx*dx+dy*dy,l=Math.sqrt(l2);const t=Math.max(0,Math.min(1,((x-ax)*dx+(y-ay)*dy)/(l2||1))),d=(ax+dx*t-x)**2+(ay+dy*t-y)**2;if(d<best){best=d;s=acc+t*l;}acc+=l;}return {d:Math.sqrt(best),s};}
const perm=(()=>{const a=Array.from({length:256},(_,i)=>i);let s=1337;for(let i=255;i>0;i--){s=s*16807%2147483647;const j=Math.floor(s/2147483647*(i+1));[a[i],a[j]]=[a[j],a[i]];}return Uint8Array.from({length:512},(_,i)=>a[i&255]);})();
function noise(x:number,y:number){const X=Math.floor(x),Y=Math.floor(y),fx=x-X,fy=y-Y,xi=X&255,yi=Y&255,u=fx**3*(fx*(fx*6-15)+10),v=fy**3*(fy*(fy*6-15)+10);const grad=(q:number,dx:number,dy:number)=>[dx+dy,dy-dx,dx-dy,-dx-dy,dx,-dx,dy,-dy][q&7];const a=perm[xi]+yi,b=perm[xi+1]+yi,g00=grad(perm[a],fx,fy),g10=grad(perm[b],fx-1,fy),g01=grad(perm[a+1],fx,fy-1),g11=grad(perm[b+1],fx-1,fy-1),x1=g00+(g10-g00)*u,x2=g01+(g11-g01)*u;return x1+(x2-x1)*v;}
function fbm(x:number,y:number,o:number,sd:number){let s=0,a=.5,f=1;for(let i=0;i<o;i++){s+=a*noise(x*f+sd*(i+1),y*f-sd*(i+1)*.7);f*=2.03;a*=.5;}return s;}
function ridged(x:number,y:number){let r=0,a=.5,f=1,w=1;for(let i=0;i<4;i++){let q=1-Math.abs(noise(x*f+i*17.3,y*f-i*9.1));q=q*q*w;w=Math.min(1,Math.max(0,q*2));r+=q*a;f*=2.05;a*=.5;}return r/.94;}
/** Deterministic, domain-warped relief from the approved map reference. */
export function terrainHeight(x:number,y:number){const C=WORLD,wx=x+70*noise(x/420+3.1,y/420+7.7),wy=y+70*noise(x/420+11.3,y/420+1.9);let h=.115+.05*fbm(wx/300,wy/300,3,5.2);for(const [hx,hy,amp,r] of HILLS)h+=amp*Math.exp(-((wx-hx)**2+(wy-hy)**2)/(2*r*r));const se=Math.exp(-((wx-950)**2+(wy-640)**2)/(2*210*210));if(se>.01)h+=.52*se*(.7+.5*fbm(wx/150,wy/150,3,9.1));const mm=smooth(340,40,distanceToLine(wx,wy,RIDGE).d);if(mm>0)h+=mm**1.25*(.16+.84*ridged(wx/210,wy/210));const pr=distanceToLine(x,y,RIVER),south=smooth(680,900,y);if(south>0)h+=.055*Math.min(1,pr.d/340)*south;const pv=distanceToLine(x,y,VAL),fl=.05+.3*Math.exp(-(((pv.s-560)/115)**2));h=smin(h,fl+.95*(pv.d/170)**1.5,.09);const fq=smooth(265,125,Math.hypot(x-C.HQ[0],y-C.HQ[1]));if(fq>0)h=h*(1-fq)+(.095+.006*noise(x/90,y/90))*fq;h-=.014*Math.exp(-pr.d*pr.d/512);const e=Math.min(x-C.X0,C.X1-x,y-C.Y0,C.Y1-y);return .09+(h-.09)*smooth(0,240,e);}

export function simplify(p:Point[],eps=1.2,closed=false):Point[]{if(p.length<3)return p;if(closed){let far=1;for(let i=2;i<p.length;i++)if(Math.hypot(p[i][0]-p[0][0],p[i][1]-p[0][1])>Math.hypot(p[far][0]-p[0][0],p[far][1]-p[0][1]))far=i;return [...simplify(p.slice(0,far+1),eps).slice(0,-1),...simplify([...p.slice(far),p[0]],eps).slice(0,-1)];}const keep=new Uint8Array(p.length);keep[0]=keep[p.length-1]=1;const stack:Point[]=[[0,p.length-1]];while(stack.length){const [s,e]=stack.pop()!,[ax,ay]=p[s],dx=p[e][0]-ax,dy=p[e][1]-ay,len=Math.hypot(dx,dy)||1e-9;let md=-1,mi=-1;for(let i=s+1;i<e;i++){const d=Math.abs((p[i][0]-ax)*dy-(p[i][1]-ay)*dx)/len;if(d>md){md=d;mi=i;}}if(md>eps){keep[mi]=1;stack.push([s,mi],[mi,e]);}}return p.filter((_,i)=>keep[i]);}
export function curve(p:Point[],closed=false){if(!p.length)return '';const n=p.length,f=(v:number)=>Math.round(v*10)/10;let d=`M${f(p[0][0])} ${f(p[0][1])}`;for(let i=0;i<(closed?n:n-1);i++){const p0=p[closed?(i-1+n)%n:Math.max(0,i-1)],p1=p[i],p2=p[(i+1)%n],p3=p[closed?(i+2)%n:Math.min(n-1,i+2)];d+=`C${f(p1[0]+(p2[0]-p0[0])/6)} ${f(p1[1]+(p2[1]-p0[1])/6)} ${f(p2[0]-(p3[0]-p1[0])/6)} ${f(p2[1]-(p3[1]-p1[1])/6)} ${f(p2[0])} ${f(p2[1])}`;}return d+(closed?'Z':'');}
export type ContourPolygon={points:Point[];closed:boolean;bounds:Box;d:string};
export type Terrain={heights:Float32Array;nx:number;ny:number;contours:{d:string;major:boolean;polygons?:ContourPolygon[]}[];river:string;raster:string;pathHeights:Float32Array;roughness:Float32Array;pnx:number;pny:number};
const yieldFrame=()=>new Promise<void>(resolve=>setTimeout(resolve,0));
let terrainPromise:Promise<Terrain>|undefined;
/** Shared once per application session; row batches keep input and first paint responsive. */
export function loadTerrain(){return terrainPromise??=(async()=>{const C=WORLD,st=C.ST,nx=Math.round((C.X1-C.X0)/st)+1,ny=Math.round((C.Y1-C.Y0)/st)+1,H=new Float32Array(nx*ny);let hmax=0;for(let j=0;j<ny;j++){for(let i=0;i<nx;i++){const v=terrainHeight(C.X0+i*st,C.Y0+j*st);H[j*nx+i]=v;hmax=Math.max(hmax,v);}if(j%12===0)await yieldFrame();}
 const NL=Math.floor(hmax/C.LV),maps=Array.from({length:NL+1},()=>new Map<number,{p:Point;n:number[]}>());const add=(m:typeof maps[number],k1:number,p1:Point,k2:number,p2:Point)=>{if(!m.has(k1))m.set(k1,{p:p1,n:[]});if(!m.has(k2))m.set(k2,{p:p2,n:[]});m.get(k1)!.n.push(k2);m.get(k2)!.n.push(k1);};
 for(let j=0;j<ny-1;j++){for(let i=0;i<nx-1;i++){const o=j*nx+i,a=H[o],b=H[o+1],c=H[o+nx+1],d=H[o+nx],l0=Math.max(1,Math.ceil(Math.min(a,b,c,d)/C.LV)),l1=Math.min(NL,Math.floor(Math.max(a,b,c,d)/C.LV)),x0=C.X0+i*st,y0=C.Y0+j*st,kt=o*2,kl=o*2+1,kr=(o+1)*2+1,kb=(o+nx)*2;for(let l=l0;l<=l1;l++){const L=l*C.LV,code=(a>L?8:0)|(b>L?4:0)|(c>L?2:0)|(d>L?1:0),m=maps[l],T=():Point=>[x0+st*(L-a)/(b-a),y0],R=():Point=>[x0+st,y0+st*(L-b)/(c-b)],B=():Point=>[x0+st*(L-d)/(c-d),y0+st],F=():Point=>[x0,y0+st*(L-a)/(d-a)];switch(code){case 1:case 14:add(m,kl,F(),kb,B());break;case 2:case 13:add(m,kb,B(),kr,R());break;case 3:case 12:add(m,kl,F(),kr,R());break;case 4:case 11:add(m,kt,T(),kr,R());break;case 6:case 9:add(m,kt,T(),kb,B());break;case 7:case 8:add(m,kt,T(),kl,F());break;case 5:case 10:if(((a+b+c+d)/4>L)===(code===5)){add(m,kt,T(),kl,F());add(m,kr,R(),kb,B());}else{add(m,kt,T(),kr,R());add(m,kl,F(),kb,B());}break;}}}if(j%20===0)await yieldFrame();}
 const contours:Terrain['contours']=[];for(let l=1;l<=NL;l++){const m=maps[l],seen=new Set<number>(),paths:string[]=[],polygons:ContourPolygon[]=[];const walk=(start:number)=>{const keys=[start];seen.add(start);let cur=start,prev=-1;for(;;){const next=m.get(cur)!.n.find(q=>q!==prev&&!seen.has(q));if(next===undefined)break;seen.add(next);keys.push(next);prev=cur;cur=next;}const closed=keys.length>2&&m.get(cur)!.n.includes(start),p=keys.map(k=>m.get(k)!.p),xs=p.map(q=>q[0]),ys=p.map(q=>q[1]);if(Math.max(...xs)-Math.min(...xs)+Math.max(...ys)-Math.min(...ys)<34)return;const simple=simplify(p,1.2,closed);if(simple.length>=(closed?4:2)){const d=curve(simple,closed);paths.push(d);polygons.push({points:simple,closed,d,bounds:[Math.min(...xs),Math.min(...ys),Math.max(...xs),Math.max(...ys)]});}};for(const [k,v] of m)if(v.n.length===1&&!seen.has(k))walk(k);for(const k of m.keys())if(!seen.has(k))walk(k);contours.push({d:paths.join(''),major:l%5===0,polygons});await yieldFrame();}
 const pnx=Math.floor((nx-1)/2)+1,pny=Math.floor((ny-1)/2)+1,pathHeights=new Float32Array(pnx*pny),roughness=new Float32Array(pnx*pny);for(let j=0;j<pny;j++)for(let i=0;i<pnx;i++){pathHeights[j*pnx+i]=H[j*2*nx+i*2];roughness[j*pnx+i]=1+.35*(noise((C.X0+i*C.PS)/70+40.2,(C.Y0+j*C.PS)/70-13.7)*.5+.5);}const terrain:Terrain={heights:H,nx,ny,contours,river:curve(RIVER),raster:'',pathHeights,roughness,pnx,pny};if(typeof document!=='undefined')terrain.raster=await rasterize(terrain);return terrain;})().catch(error=>{terrainPromise=undefined;throw error;});}
const HY:[number,number[]][]=[[0,[20,21,23]],[.07,[25,26,28]],[.095,[28,29,31]],[.16,[31,32,34]],[.3,[36,37,39]],[.5,[42,43,46]],[.75,[49,50,53]],[1,[57,58,61]],[1.3,[70,71,74]]];
async function rasterize(g:Terrain){const {nx,ny,heights:H}=g,st=WORLD.ST,shade=new Float32Array(nx*ny),ln=Math.hypot(.52,.58,.63),lx=-.52/ln,ly=-.58/ln,lz=.63/ln;for(let j=0;j<ny;j++)for(let i=0;i<nx;i++){const o=j*nx+i,gx=(H[i<nx-1?o+1:o]-H[i>0?o-1:o])/(2*st),gy=(H[j<ny-1?o+nx:o]-H[j>0?o-nx:o])/(2*st),xx=-230*gx,yy=-230*gy;shade[o]=(xx*lx+yy*ly+lz)/Math.hypot(xx,yy,1)-lz;}const sc=2,w=Math.round((WORLD.X1-WORLD.X0)/sc),h=Math.round((WORLD.Y1-WORLD.Y0)/sc),canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d');if(!ctx)return '';const im=ctx.createImageData(w,h);let sd=99;for(let y=0;y<h;y++){const gy=(y+.5)*sc/st,j=Math.min(ny-2,Math.floor(gy)),fy=gy-j;for(let x=0;x<w;x++){const gx=(x+.5)*sc/st,i=Math.min(nx-2,Math.floor(gx)),fx=gx-i,o=j*nx+i,at=(a:Float32Array)=>(a[o]*(1-fx)+a[o+1]*fx)*(1-fy)+(a[o+nx]*(1-fx)+a[o+nx+1]*fx)*fy,v=at(H),s=at(shade);let k=1;while(k<HY.length-1&&HY[k][0]<v)k++;const [lo,A]=HY[k-1],[hi,B]=HY[k],t=Math.max(0,Math.min(1,(v-lo)/(hi-lo))),q=(y*w+x)*4;sd=sd*16807%2147483647;const grain=(sd/2147483647-.5)*2.2;for(let c=0;c<3;c++){let z=A[c]+(B[c]-A[c])*t;z=s>0?z+([95,96,98][c]-z)*s*.35:z*(1+s*.5);im.data[q+c]=z+grain;}im.data[q+3]=255;}if(y%40===0)await yieldFrame();}ctx.putImageData(im,0,0);return canvas.toDataURL('image/jpeg',.9);}

const denseContours=new WeakMap<ContourPolygon,Point[]>();
/** Deform only polygons touched by a completion wave; the saved base contours stay immutable. */
export function rippleContourPaths(terrain:Terrain,center:Point,elapsed:number,final=false):string[]{
 const sources=[{delay:0,duration:1150,radius:230,amplitude:9,sigma:18,wavelength:34},...(final?[{delay:480,duration:2000,radius:560,amplitude:8,sigma:26,wavelength:52}]:[])];
 const waves=sources.flatMap(s=>{const t=(elapsed-s.delay)/s.duration;return t>0&&t<1?[{...s,radius:s.radius*(1-(1-t)**2),amplitude:s.amplitude*(1-t)**1.6}]:[];});
 if(!waves.length)return terrain.contours.map(line=>line.d);
 return terrain.contours.map(line=>line.polygons?.map(polygon=>{
  const [x0,y0,x1,y1]=polygon.bounds;
  const hit=waves.some(w=>{const nearest=Math.hypot(Math.max(x0-center[0],0,center[0]-x1),Math.max(y0-center[1],0,center[1]-y1)),farthest=Math.hypot(Math.max(Math.abs(x0-center[0]),Math.abs(x1-center[0])),Math.max(Math.abs(y0-center[1]),Math.abs(y1-center[1])));return nearest<=w.radius+3*w.sigma&&farthest>=w.radius-3*w.sigma;});
  if(!hit)return polygon.d;
  let dense=denseContours.get(polygon);if(!dense){dense=[];for(let i=0;i<(polygon.closed?polygon.points.length:polygon.points.length-1);i++){const a=polygon.points[i],b=polygon.points[(i+1)%polygon.points.length],steps=Math.max(1,Math.ceil(Math.hypot(b[0]-a[0],b[1]-a[1])/7));for(let j=0;j<steps;j++)dense.push([a[0]+(b[0]-a[0])*j/steps,a[1]+(b[1]-a[1])*j/steps]);}if(!polygon.closed)dense.push(polygon.points.at(-1)!);denseContours.set(polygon,dense);}
  return curve(dense.map(([x,y]):Point=>{const dx=x-center[0],dy=y-center[1],r=Math.hypot(dx,dy);if(r<.01)return [x,y];let displacement=0;for(const w of waves){const distance=r-w.radius;if(Math.abs(distance)>3*w.sigma)continue;displacement+=w.amplitude*Math.exp(-distance*distance/(2*w.sigma*w.sigma))*Math.sin(distance*Math.PI*2/w.wavelength)*Math.min(1,r/10);}return [x+dx/r*displacement,y+dy/r*displacement];}),polygon.closed);
 }).join('')??line.d);
}

const terrainRouteCaches=new WeakMap<Terrain,Map<string,Point[]>>();
/** The search grid expands for overflow camps; its resolution is bounded to keep large atlases usable. */
export function terrainRoute(g:Terrain,a:Point,b:Point):Point[]{
 let cache=terrainRouteCaches.get(g);if(!cache){cache=new Map();terrainRouteCaches.set(g,cache);}
 const key=a.join(',')+'>'+b.join(','),reverse=b.join(',')+'>'+a.join(',');
 const hit=cache.get(key);if(hit)return hit;const rev=cache.get(reverse);if(rev)return [...rev].reverse();
 let ps=WORLD.PS,x0=WORLD.X0,y0=WORLD.Y0,nx=g.pnx,ny=g.pny,H=g.pathHeights,R=g.roughness;
 const xmax=x0+(nx-1)*ps,ymax=y0+(ny-1)*ps;
 if([a,b].some(p=>p[0]<x0||p[0]>xmax||p[1]<y0||p[1]>ymax)){
  const x1=Math.max(xmax,a[0],b[0])+ps,y1=Math.max(ymax,a[1],b[1])+ps;
  x0=Math.min(x0,a[0],b[0])-ps;y0=Math.min(y0,a[1],b[1])-ps;
  ps=WORLD.PS*Math.max(1,Math.ceil(Math.sqrt((x1-x0)*(y1-y0)/50000)/WORLD.PS));
  nx=Math.ceil((x1-x0)/ps)+1;ny=Math.ceil((y1-y0)/ps)+1;H=new Float32Array(nx*ny);R=new Float32Array(nx*ny);
  for(let y=0;y<ny;y++)for(let x=0;x<nx;x++){const i=y*nx+x,wx=x0+x*ps,wy=y0+y*ps;H[i]=terrainHeight(wx,wy);R[i]=1+.35*(noise(wx/70+40.2,wy/70-13.7)*.5+.5);}
 }
 const N=nx*ny,cl=(v:number,m:number)=>Math.max(0,Math.min(m,v));
 const id=(p:Point)=>cl(Math.round((p[1]-y0)/ps),ny-1)*nx+cl(Math.round((p[0]-x0)/ps),nx-1);
 const start=id(a),target=id(b),tx=target%nx,ty=Math.floor(target/nx),cost=new Float64Array(N).fill(Infinity),from=new Int32Array(N).fill(-1),finished=new Uint8Array(N),heap:{n:number;f:number}[]=[];
 const push=(n:number,f:number)=>{heap.push({n,f});let i=heap.length-1;while(i){const p=(i-1)>>1;if(heap[p].f<=heap[i].f)break;[heap[p],heap[i]]=[heap[i],heap[p]];i=p;}};
 const pop=()=>{const top=heap[0].n,last=heap.pop()!;if(heap.length){heap[0]=last;let i=0;for(;;){const l=i*2+1,r=l+1;let m=i;if(l<heap.length&&heap[l].f<heap[m].f)m=l;if(r<heap.length&&heap[r].f<heap[m].f)m=r;if(m===i)break;[heap[m],heap[i]]=[heap[i],heap[m]];i=m;}}return top;};
 cost[start]=0;push(start,0);const dirs=[[1,0,1],[-1,0,1],[0,1,1],[0,-1,1],[1,1,Math.SQRT2],[1,-1,Math.SQRT2],[-1,1,Math.SQRT2],[-1,-1,Math.SQRT2]];
 while(heap.length){const u=pop();if(finished[u])continue;finished[u]=1;if(u===target)break;const ux=u%nx,uy=Math.floor(u/nx),hu=H[u];for(const [dx,dy,dl] of dirs){const vx=ux+dx,vy=uy+dy;if(vx<0||vy<0||vx>=nx||vy>=ny)continue;const v=vy*nx+vx;if(finished[v])continue;const len=dl*ps,slope=Math.abs(H[v]-hu)/len,c=len*(1+(slope/.0042)**2+.7*(hu+H[v])*.5)*(R[u]+R[v])*.5,next=cost[u]+c;if(next<cost[v]){cost[v]=next;from[v]=u;push(v,next+Math.hypot(vx-tx,vy-ty)*ps);}}}
 const path:Point[]=[];for(let n=target;n>=0;n=from[n]){path.push([x0+n%nx*ps,y0+Math.floor(n/nx)*ps]);if(n===start)break;}path.reverse();
 let points:Point[]=[a,...path.slice(1,-1),b];
 for(let pass=0;pass<4;pass++){const next=points.slice();for(let i=1;i<points.length-1;i++)next[i]=[(points[i-1][0]+2*points[i][0]+points[i+1][0])/4,(points[i-1][1]+2*points[i][1]+points[i+1][1])/4];points=next;}
 if(cache.size>=600)cache.delete(cache.keys().next().value!);cache.set(key,points);return points;
}

export function hashId(id:string){let h=2166136261;for(let i=0;i<id.length;i++){h^=id.charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0;}
function candidate(type:FrontType,seed:number,attempt:number):Point{const a=hashId(seed+':'+attempt)/4294967296,b=hashId(seed+':y:'+attempt)/4294967296;if(attempt<500){if(type==='lane')return [60+a*560,40+b*365];if(type==='course')return [40+a*675,850+b*460];if(type==='general')return [110+a*355,430+b*360];const y=-80+b*620;return [520+(660-y)*.37+(a-.5)*115,y];}const i=attempt-500,row=Math.floor(i/18),col=i%18;if(type==='lane')return [-220+col*64,-150-row*64];if(type==='course')return [-220+col*64,1400+row*64];if(type==='general')return [-120-row*64,450+col*64];return [960+row*64,-200+col*64];}
/** Existing allocations are immutable. Overflow sectors grow without a front-count cap. */
export function allocateCamps(fronts:Pick<Front,'id'|'type'>[],previous:Positions={}):Positions{const out:Positions={};for(const [id,v] of Object.entries(previous))if(v&&Object.hasOwn(REGION_NAMES,v.type)&&Array.isArray(v.point)&&v.point.length===2&&v.point.every(Number.isFinite))out[id]=v;const occupied=Object.values(out).map(v=>v.point);for(const f of [...fronts].sort((a,b)=>a.id.localeCompare(b.id))){if(out[f.id]?.type===f.type)continue;const seed=hashId(f.id);let attempt=0,p:Point;do{p=candidate(f.type,seed,attempt++);}while(Math.hypot(p[0]-WORLD.HQ[0],p[1]-WORLD.HQ[1])<95||occupied.some(q=>Math.hypot(p[0]-q[0],p[1]-q[1])<170));out[f.id]={type:f.type,point:p};occupied.push(p);}return out;}
export type View={x:number;y:number;k:number};
export function fitView(points:Point[],width:number,height:number,top=36,bottom=48):View{const p=[WORLD.HQ,...points],xs=p.map(v=>v[0]),ys=p.map(v=>v[1]),x0=Math.min(...xs),x1=Math.max(...xs),y0=Math.min(...ys),y1=Math.max(...ys),k=Math.min(1.15,Math.max(30,width-110)/Math.max(160,x1-x0),Math.max(30,height-top-bottom-56)/Math.max(160,y1-y0));return {k,x:width/2-(x0+x1)/2*k,y:top+(height-top-bottom)/2-(y0+y1)/2*k};}
export function urgency(days:number|null,held=false,done=false,critical=2,approaching=7){return done?'done':held||days===null?'calm':days<=critical?'critical':days<=Math.max(critical,approaching)?'approaching':'calm';}
export function dayLabel(days:number|null,held=false){return held?'BEKLETİLİYOR':days===null?'TARİHSİZ':days<0?`${Math.abs(days)} GÜN GEÇTİ`:days===0?'BUGÜN':days===1?'YARIN':`${days} GÜN`;}
export type LabelMark={id:string;x:number;y:number;r:number;width:number;height:number;priority:number;force?:boolean};
export const overlaps=(a:Box,b:Box)=>a[0]<b[2]&&a[2]>b[0]&&a[1]<b[3]&&a[3]>b[1];
export function placeLabels(marks:LabelMark[],width:number,height:number,extra:Box[]=[]){const boxes:Box[]=[...marks.map(m=>[m.x-m.r,m.y-m.r,m.x+m.r,m.y+m.r] as Box),...extra],placed:Box[]=[],result:Record<string,Point>={};const rectDistance=(b:Box,m:LabelMark)=>Math.hypot(Math.max(b[0]-m.x,0,m.x-b[2]),Math.max(b[1]-m.y,0,m.y-b[3]));for(const m of [...marks].sort((a,b)=>b.priority-a.priority)){if(!m.width||m.x<0||m.x>width||m.y<0||m.y>height)continue;const w=Math.min(m.width,width-8),h=m.height,g=m.r+4,candidates:Point[]=[[-w/2,g],[g,-h/2],[-g-w,-h/2],[-w/2,-g-h],[g,g],[-g-w,g],[g,-g-h],[-g-w,-g-h]];let best:{p:Point;box:Box;score:number}|undefined;for(const [dx,dy] of candidates){const x=Math.max(4,Math.min(width-w-4,m.x+dx)),y=Math.max(4,Math.min(height-h-4,m.y+dy)),b:Box=[x,y,x+w,y+h],own=rectDistance(b,m),hq=marks.find(q=>q.id==='__hq');if(hq&&m!==hq&&overlaps(b,[hq.x-22,hq.y-22,hq.x+22,hq.y+22]))continue;const hits=[...boxes,...placed].filter(q=>overlaps(b,q)),owns=marks.every(q=>q===m||rectDistance(b,q)>=own+10);if(!hits.length&&owns){best={p:[x,y],box:b,score:Infinity};break;}const overlap=hits.reduce((sum,q)=>sum+Math.max(0,Math.min(b[2],q[2])-Math.max(b[0],q[0]))*Math.max(0,Math.min(b[3],q[3])-Math.max(b[1],q[1])),0),score=(owns?100000:0)-overlap-own;if(m.force&&(!best||score>best.score))best={p:[x,y],box:b,score};}if(best){result[m.id]=best.p;placed.push(best.box);}}return {labels:result,occupied:[...boxes,...placed]};}
